import { $IOHelper } from "@package/com/tom/cpm/shared/io";
import { $Set } from "@package/java/util";

declare module "@package/com/tom/cpl/nbt" {
    export class $NBTTagList extends $NBTTag {
        getTagType(): number;
        removeTag(arg0: number): $NBTTag;
        tagCount(): number;
        appendTag(arg0: $NBTTag): void;
        getCompoundTagAt(arg0: number): $NBTTagCompound;
        hasNoTags(): boolean;
        getIntArrayAt(arg0: number): number[];
        getStringTagAt(arg0: number): string;
        getFloatAt(arg0: number): number;
        getDoubleAt(arg0: number): number;
        get(arg0: number): $NBTTag;
        set(arg0: number, arg1: $NBTTag): void;
        static TAG_INT: number;
        static TAG_FLOAT: number;
        static TAG_BYTE_ARRAY: number;
        static TAG_INT_ARRAY: number;
        static TAG_DOUBLE: number;
        static TAG_STRING: number;
        static TAG_BYTE: number;
        static TAG_ANY_NUMERIC: number;
        static TAG_COMPOUND: number;
        static TAG_SHORT: number;
        static TAG_END: number;
        static TAG_LIST: number;
        static TAG_LONG_ARRAY: number;
        static TAG_LONG: number;
        constructor();
        get tagType(): number;
    }
    export class $NBTTagCompound extends $NBTTag {
        removeTag(arg0: string): void;
        getCompoundTag(arg0: string): $NBTTagCompound;
        setByteArray(arg0: string, arg1: number[]): void;
        getString(arg0: string): string;
        getTag(arg0: string): $NBTTag;
        setInteger(arg0: string, arg1: number): void;
        tagCount(): number;
        getTagId(arg0: string): number;
        getKeySet(): $Set<string>;
        setIntArray(arg0: string, arg1: number[]): void;
        setLongArray(arg0: string, arg1: number[]): void;
        hasKey(arg0: string): boolean;
        hasKey(arg0: string, arg1: number): boolean;
        getInteger(arg0: string): number;
        getByteArray(arg0: string): number[];
        getIntArray(arg0: string): number[];
        getLongArray(arg0: string): number[];
        setString(arg0: string, arg1: string): void;
        getTagList(arg0: string, arg1: number): $NBTTagList;
        setTag(arg0: string, arg1: $NBTTag): void;
        getBoolean(arg0: string): boolean;
        getByte(arg0: string): number;
        getShort(arg0: string): number;
        getLong(arg0: string): number;
        getFloat(arg0: string): number;
        getDouble(arg0: string): number;
        merge(arg0: $NBTTagCompound): void;
        setBoolean(arg0: string, arg1: boolean): void;
        setByte(arg0: string, arg1: number): void;
        setShort(arg0: string, arg1: number): void;
        setLong(arg0: string, arg1: number): void;
        setFloat(arg0: string, arg1: number): void;
        setDouble(arg0: string, arg1: number): void;
        static TAG_INT: number;
        static TAG_FLOAT: number;
        static TAG_BYTE_ARRAY: number;
        static TAG_INT_ARRAY: number;
        static TAG_DOUBLE: number;
        static TAG_STRING: number;
        static TAG_BYTE: number;
        static TAG_ANY_NUMERIC: number;
        static TAG_COMPOUND: number;
        static TAG_SHORT: number;
        static TAG_END: number;
        static TAG_LIST: number;
        static TAG_LONG_ARRAY: number;
        static TAG_LONG: number;
        constructor();
        get keySet(): $Set<string>;
    }
    export class $NBTTag {
        static createNewByType(arg0: number): $NBTTag;
        write(arg0: $IOHelper): void;
        read(arg0: $IOHelper): void;
        getId(): number;
        copy(): $NBTTag;
        static TAG_INT: number;
        static TAG_FLOAT: number;
        static TAG_BYTE_ARRAY: number;
        static TAG_INT_ARRAY: number;
        static TAG_DOUBLE: number;
        static TAG_STRING: number;
        static TAG_BYTE: number;
        static TAG_ANY_NUMERIC: number;
        static TAG_COMPOUND: number;
        static TAG_SHORT: number;
        static TAG_END: number;
        static TAG_LIST: number;
        static TAG_LONG_ARRAY: number;
        static TAG_LONG: number;
        constructor();
        get id(): number;
    }
}
