import { $Outliner } from "@package/net/createmod/catnip/outliner";
import { $SceneBuilder, $SceneBuildingUtil } from "@package/net/createmod/ponder/api/scene";
import { $Entity } from "@package/net/minecraft/world/entity";
import { $CallbackInfo } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $Camera } from "@package/net/minecraft/client";
import { $List, $Set, $Collection_ } from "@package/java/util";
import { $PonderUI } from "@package/net/createmod/ponder/foundation/ui";
import { $SuperRenderTypeBuffer } from "@package/net/createmod/catnip/render";
import { $Consumer_, $Function_, $Supplier } from "@package/java/util/function";
import { $BlockPos } from "@package/net/minecraft/core";
import { $WorldSectionElement, $PonderElement, $ElementLink } from "@package/net/createmod/ponder/api/element";
import { $Object, $Class } from "@package/java/lang";
import { $PonderLevel } from "@package/net/createmod/ponder/api/level";
import { $BoundingBox } from "@package/net/minecraft/world/level/levelgen/structure";
import { $Pair } from "@package/net/createmod/catnip/data";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $LerpedFloat } from "@package/net/createmod/catnip/animation";
import { $PonderLocalization } from "@package/net/createmod/ponder/foundation/registration";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $StoryBoardEntry$SceneOrderingEntry, $StoryBoardEntry$SceneOrderingEntry_ } from "@package/net/createmod/ponder/api/registration";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $PonderSceneExtension } from "@package/dev/simulated_team/simulated/mixin_interface/ponder";
import { $ScreenElement } from "@package/net/createmod/catnip/gui/element";
import { $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $Vec3_, $Vec3, $Vec2 } from "@package/net/minecraft/world/phys";
export * as element from "@package/net/createmod/ponder/foundation/element";
export * as instruction from "@package/net/createmod/ponder/foundation/instruction";
export * as registration from "@package/net/createmod/ponder/foundation/registration";
export * as ui from "@package/net/createmod/ponder/foundation/ui";

declare module "@package/net/createmod/ponder/foundation" {
    export class $PonderScene implements $PonderSceneExtension {
        getTags(): $List<$PonderTag>;
        applyTo<E extends $PonderElement, F>(arg0: $ElementLink<E>, arg1: $Function_<E, F>): F;
        fadeOut(): void;
        isFinished(): boolean;
        getTransform(): $PonderScene$SceneTransform;
        getYOffset(): number;
        getElements(): $Set<$PonderElement>;
        getNamespace(): string;
        getString(arg0: string): string;
        tick(): void;
        addElement(arg0: $PonderElement): void;
        getOrderingEntries(): $List<$StoryBoardEntry$SceneOrderingEntry>;
        getSceneBuildingUtil(): $SceneBuildingUtil;
        renderOverlay(arg0: $PonderUI, arg1: $GuiGraphics, arg2: number): void;
        deselect(): void;
        getWorld(): $PonderLevel;
        handler$imd000$simulated$headTick(arg0: $CallbackInfo): void;
        simulated$setOldShadowOffset(arg0: $Vec3_): void;
        redirect$imd000$simulated$onCameraSet(arg0: $PonderScene$SceneCamera, arg1: number, arg2: number, arg3: $SuperRenderTypeBuffer, arg4: $GuiGraphics, arg5: number): void;
        handler$imd000$simulated$tailBegin(arg0: $CallbackInfo): void;
        setPointOfInterest(arg0: $Vec3_): void;
        rayTraceScene(arg0: $Vec3_, arg1: $Vec3_): $Pair<$ItemStack, $BlockPos>;
        getBaseWorldSection(): $WorldSectionElement;
        getSceneProgress(): number;
        renderScene(arg0: $SuperRenderTypeBuffer, arg1: $GuiGraphics, arg2: number): void;
        forEachVisible<T extends $PonderElement>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        getPointOfInterest(): $Vec3;
        seekToTime(arg0: number): void;
        addToSceneTime(arg0: number): void;
        stopCounting(): void;
        markKeyframe(arg0: number): void;
        linkElement<E extends $PonderElement>(arg0: E, arg1: $ElementLink<E>): void;
        resolveOptional<E extends $PonderElement>(arg0: $ElementLink<E>): (E) | undefined;
        forEachWorldEntity<T extends $Entity>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        registerText(arg0: string): $Supplier<string>;
        registerText(arg0: string, ...arg1: $Object[]): $Supplier<string>;
        getKeyframeCount(): number;
        getKeyframeTime(arg0: number): number;
        getOutliner(): $Outliner;
        setFinished(arg0: boolean): void;
        getBasePlateOffsetX(): number;
        getBasePlateOffsetZ(): number;
        shouldHidePlatformShadow(): boolean;
        getBasePlateSize(): number;
        getScaleFactor(): number;
        getCurrentTime(): number;
        setNextUpEnabled(arg0: boolean): void;
        isNextUpEnabled(): boolean;
        simulated$toggleRenderBasePlateShadow(): void;
        simulated$getBasePlateAnimationTimer(arg0: number): number;
        simulated$getShadowOffset(arg0: number): $Vec3;
        simulated$setShadowOffset(arg0: $Vec3_): void;
        simulated$moveShadowOffset(arg0: $Vec3_): void;
        simulated$setScaleFactor(arg0: number): void;
        simulated$getScale(arg0: number): number;
        simulated$setYOffset(arg0: number): void;
        simulated$getYOffset(arg0: number): number;
        getTitle(): string;
        getTotalTime(): number;
        runWith<E extends $PonderElement>(arg0: $ElementLink<E>, arg1: $Consumer_<E>): void;
        reset(): void;
        begin(): void;
        builder(): $SceneBuilder;
        getBounds(): $BoundingBox;
        getLocation(): $ResourceLocation;
        resolve<E extends $PonderElement>(arg0: $ElementLink<E>): E;
        forEach(arg0: $Consumer_<$PonderElement>): void;
        forEach<T extends $PonderElement>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        getId(): $ResourceLocation;
        static TITLE_KEY: string;
        constructor(arg0: $PonderLevel, arg1: $PonderLocalization, arg2: string, arg3: $ResourceLocation_, arg4: $Collection_<$ResourceLocation_>, arg5: $Collection_<$StoryBoardEntry$SceneOrderingEntry_>);
        get tags(): $List<$PonderTag>;
        get transform(): $PonderScene$SceneTransform;
        get YOffset(): number;
        get elements(): $Set<$PonderElement>;
        get namespace(): string;
        get orderingEntries(): $List<$StoryBoardEntry$SceneOrderingEntry>;
        get sceneBuildingUtil(): $SceneBuildingUtil;
        get world(): $PonderLevel;
        get baseWorldSection(): $WorldSectionElement;
        get sceneProgress(): number;
        get keyframeCount(): number;
        get outliner(): $Outliner;
        get basePlateOffsetX(): number;
        get basePlateOffsetZ(): number;
        get basePlateSize(): number;
        get scaleFactor(): number;
        get currentTime(): number;
        get title(): string;
        get totalTime(): number;
        get bounds(): $BoundingBox;
        get location(): $ResourceLocation;
        get id(): $ResourceLocation;
    }
    export class $PonderScene$SceneTransform {
        tick(): void;
        sceneToScreen(arg0: $Vec3_, arg1: number): $Vec2;
        screenToScene(arg0: number, arg1: number, arg2: number, arg3: number): $Vec3;
        updateScreenParams(arg0: number, arg1: number, arg2: number): void;
        updateSceneRVE(arg0: number): void;
        apply(arg0: $PoseStack, arg1: number): $PoseStack;
        apply(arg0: $PoseStack): $PoseStack;
        xRotation: $LerpedFloat;
        yRotation: $LerpedFloat;
        constructor(arg0: $PonderScene);
    }
    export class $PonderScene$SceneCamera extends $Camera {
        set(arg0: number, arg1: number): void;
        eyeHeightOld: number;
        static FOG_DISTANCE_SCALE: number;
        eyeHeight: number;
        constructor();
    }
    export class $PonderTag implements $ScreenElement {
        getMainItem(): $ItemStack;
        getDescription(): string;
        getTitle(): string;
        render(arg0: $GuiGraphics, arg1: number, arg2: number): void;
        getId(): $ResourceLocation;
        constructor(arg0: $ResourceLocation_, arg1: $ResourceLocation_, arg2: $ItemStack_, arg3: $ItemStack_);
        get mainItem(): $ItemStack;
        get description(): string;
        get title(): string;
        get id(): $ResourceLocation;
    }
}
