import { $JsonObject_ } from "@package/com/google/gson";
import { $Codec, $DataResult } from "@package/com/mojang/serialization";
import { $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $Enum } from "@package/java/lang";
import { $Collection_ } from "@package/java/util";
import { $StreamCodec } from "@package/net/minecraft/network/codec";

declare module "@package/net/silentchaos512/lib/util" {
    export class $Color {
        static tryParse(arg0: string, arg1: number): $Color;
        getColor(): number;
        getAlpha(): number;
        getRed(): number;
        getGreen(): number;
        getBlue(): number;
        blendWith(arg0: $Color): $Color;
        getRedInt(): number;
        getGreenInt(): number;
        getBlueInt(): number;
        getAlphaInt(): number;
        static blend(arg0: $Color, arg1: $Color, arg2: number): $Color;
        static blend(arg0: $ColorBlendAlgorithm_, arg1: $Collection_<$Color>): $Color;
        static blend(arg0: number, arg1: number): number;
        static blend(arg0: $ColorBlendAlgorithm_, arg1: $Collection_<$Color>, arg2: boolean): $Color;
        static blend(arg0: number, arg1: number, arg2: number): number;
        static blend(arg0: $Color, arg1: $Color): $Color;
        static format(arg0: number): string;
        format(): string;
        static from(arg0: $JsonObject_, arg1: string, arg2: number): $Color;
        static validate(arg0: string): boolean;
        write(arg0: $FriendlyByteBuf): void;
        static read(arg0: $FriendlyByteBuf): $Color;
        static read(arg0: string): $DataResult<$Color>;
        static parseInt(arg0: string): number;
        static parse(arg0: string): $Color;
        static TURQUOISE: $Color;
        static MEDIUMPURPLE: $Color;
        static BEIGE: $Color;
        static CHOCOLATE: $Color;
        static MEDIUMAQUAMARINE: $Color;
        static CHARTREUSE: $Color;
        static PALEVIOLETRED: $Color;
        static LIGHTSLATEGREY: $Color;
        static DARKGREEN: $Color;
        static BLANCHEDALMOND: $Color;
        static CADETBLUE: $Color;
        static DARKVIOLET: $Color;
        static MEDIUMSPRINGGREEN: $Color;
        static BLACK: $Color;
        static GREENYELLOW: $Color;
        static SLATEGREY: $Color;
        static SEAGREEN: $Color;
        static PAPAYAWHIP: $Color;
        static DARKGREY: $Color;
        static OLIVEDRAB: $Color;
        static CODEC: $Codec<$Color>;
        static ROSYBROWN: $Color;
        static MEDIUMBLUE: $Color;
        static LIGHTGREY: $Color;
        static LIGHTSEAGREEN: $Color;
        static WHEAT: $Color;
        static INDIGO: $Color;
        static DARKMAGENTA: $Color;
        static DARKGOLDENROD: $Color;
        static GOLDENROD: $Color;
        static SALMON: $Color;
        static LAVENDER: $Color;
        static CYAN: $Color;
        static FORESTGREEN: $Color;
        static VALUE_WHITE: number;
        static BURLYWOOD: $Color;
        static LIGHTSKYBLUE: $Color;
        static GOLD: $Color;
        static GRAY: $Color;
        static NAVAJOWHITE: $Color;
        static BLUE: $Color;
        static LIGHTGREEN: $Color;
        static DEEPPINK: $Color;
        static PALEGREEN: $Color;
        static CORNFLOWERBLUE: $Color;
        static DARKSLATEGREY: $Color;
        static PINK: $Color;
        static ORANGERED: $Color;
        static DARKSEAGREEN: $Color;
        static LIGHTSTEELBLUE: $Color;
        static MINTCREAM: $Color;
        static DIMGREY: $Color;
        static ORANGE: $Color;
        static SPRINGGREEN: $Color;
        static FUCHSIA: $Color;
        static GAINSBORO: $Color;
        static MEDIUMTURQUOISE: $Color;
        static LIGHTCORAL: $Color;
        static LIGHTYELLOW: $Color;
        static INDIANRED: $Color;
        static ROYALBLUE: $Color;
        static DEEPSKYBLUE: $Color;
        static LIGHTPINK: $Color;
        static MAROON: $Color;
        static RED: $Color;
        static LAVENDERBLUSH: $Color;
        static HOTPINK: $Color;
        static DARKKHAKI: $Color;
        static SANDYBROWN: $Color;
        static TEAL: $Color;
        static MEDIUMSLATEBLUE: $Color;
        static SKYBLUE: $Color;
        static DARKORCHID: $Color;
        static OLDLACE: $Color;
        static TAN: $Color;
        static DARKRED: $Color;
        static LEMONCHIFFON: $Color;
        static SADDLEBROWN: $Color;
        static MIDNIGHTBLUE: $Color;
        static HONEYDEW: $Color;
        static LINEN: $Color;
        static WHITESMOKE: $Color;
        static STREAM_CODEC: $StreamCodec<$FriendlyByteBuf, $Color>;
        static LIGHTSLATEGRAY: $Color;
        static NAVY: $Color;
        static SLATEBLUE: $Color;
        static DARKOLIVEGREEN: $Color;
        static VIOLET: $Color;
        static MEDIUMVIOLETRED: $Color;
        static ALICEBLUE: $Color;
        static FIREBRICK: $Color;
        static PALEGOLDENROD: $Color;
        static MISTYROSE: $Color;
        static SLATEGRAY: $Color;
        static KHAKI: $Color;
        static AQUA: $Color;
        static DARKBLUE: $Color;
        static BLUEVIOLET: $Color;
        static IVORY: $Color;
        static SNOW: $Color;
        static LIGHTGRAY: $Color;
        static CORNSILK: $Color;
        static REBECCAPURPLE: $Color;
        static STEELBLUE: $Color;
        static ANTIQUEWHITE: $Color;
        static DARKSALMON: $Color;
        static LIGHTBLUE: $Color;
        static DARKGRAY: $Color;
        static PEACHPUFF: $Color;
        static PLUM: $Color;
        static LAWNGREEN: $Color;
        static MOCCASIN: $Color;
        static POWDERBLUE: $Color;
        static SIENNA: $Color;
        static MAGENTA: $Color;
        static YELLOW: $Color;
        static LIGHTGOLDENRODYELLOW: $Color;
        static LIMEGREEN: $Color;
        static DARKORANGE: $Color;
        static CORAL: $Color;
        static OLIVE: $Color;
        static SILVER: $Color;
        static AZURE: $Color;
        static ORCHID: $Color;
        static DIMGRAY: $Color;
        static FLORALWHITE: $Color;
        static MEDIUMORCHID: $Color;
        static DARKSLATEGRAY: $Color;
        static PALETURQUOISE: $Color;
        static AQUAMARINE: $Color;
        static PERU: $Color;
        static BROWN: $Color;
        static TOMATO: $Color;
        static WHITE: $Color;
        static LIGHTCYAN: $Color;
        static MEDIUMSEAGREEN: $Color;
        static YELLOWGREEN: $Color;
        static CRIMSON: $Color;
        static DARKCYAN: $Color;
        static PURPLE: $Color;
        static SEASHELL: $Color;
        static GREEN: $Color;
        static LIGHTSALMON: $Color;
        static DARKSLATEBLUE: $Color;
        static LIME: $Color;
        static GHOSTWHITE: $Color;
        static DARKTURQUOISE: $Color;
        static THISTLE: $Color;
        static BISQUE: $Color;
        static DODGERBLUE: $Color;
        static GREY: $Color;
        constructor(arg0: number);
        constructor(arg0: number, arg1: number, arg2: number);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: number, arg1: number, arg2: number);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        get color(): number;
        get alpha(): number;
        get red(): number;
        get green(): number;
        get blue(): number;
        get redInt(): number;
        get greenInt(): number;
        get blueInt(): number;
        get alphaInt(): number;
    }
    export class $ColorBlendAlgorithm extends $Enum<$ColorBlendAlgorithm> {
        static values(): $ColorBlendAlgorithm[];
        static valueOf(arg0: string): $ColorBlendAlgorithm;
        static ADDITIVE: $ColorBlendAlgorithm;
        static MIXBOX: $ColorBlendAlgorithm;
    }
    /**
     * Values that may be interpreted as {@link $ColorBlendAlgorithm}.
     */
    export type $ColorBlendAlgorithm_ = "additive" | "mixbox";
}
