import { $LevelReader } from "@package/net/minecraft/world/level";
import { $OPStorage, $IOPStorage } from "@package/com/brandon3055/brandonscore/api/power";
import { $MCDataOutput, $MCDataInput } from "@package/codechicken/lib/data";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $Component } from "@package/net/minecraft/network/chat";
import { $IItemHandler } from "@package/net/neoforged/neoforge/items";
import { $IRSSwitchable$RSMode_, $IRSSwitchable$RSMode } from "@package/com/brandon3055/brandonscore/lib";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $ClientboundBlockEntityDataPacket } from "@package/net/minecraft/network/protocol/game";
import { $Set, $Collection_ } from "@package/java/util";
import { $Consumer_, $BiConsumer_, $Predicate_ } from "@package/java/util/function";
import { $Nameable } from "@package/net/minecraft/world";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $HolderLookup$Provider, $BlockPos_, $Direction_, $Direction } from "@package/net/minecraft/core";
import { $IDataRetainingTile } from "@package/com/brandon3055/brandonscore/api";
import { $INBTSerializable } from "@package/net/neoforged/neoforge/common/util";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $IDataManagerProvider, $IDataManager, $IManagedData, $ManagedBool } from "@package/com/brandon3055/brandonscore/lib/datamanager";
import { $Logger } from "@package/org/apache/logging/log4j";
import { $Runnable_, $Object, $Runnable } from "@package/java/lang";
import { $PacketCustom } from "@package/codechicken/lib/packet";
import { $BlockEntityType_, $BlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $BlockCapability } from "@package/net/neoforged/neoforge/capabilities";

declare module "@package/com/brandon3055/brandonscore/blocks" {
    export class $TileCapabilityManager {
        getCapability<T>(arg0: $BlockCapability<T, $Direction_>, arg1: $Direction_): T;
        detectAndSendChanges(): void;
        detectAndSendChangesToListeners(arg0: $Collection_<$Player>): void;
        clearSide<T>(arg0: $BlockCapability<T, $Direction_>, arg1: $Direction_): void;
        setManaged<T extends $INBTSerializable<$CompoundTag>>(arg0: string, arg1: $BlockCapability<never, $Direction_>, arg2: T, ...arg3: $Direction_[]): $SerializationFlags<T>;
        setInternalManaged<T extends $INBTSerializable<$CompoundTag>>(arg0: string, arg1: $BlockCapability<never, $Direction_>, arg2: T): $SerializationFlags<T>;
        setCapSideValidator(arg0: $Object, arg1: $Predicate_<$Direction>): void;
        invalidate(): void;
        receiveCapSyncData(arg0: $MCDataInput): void;
        deserialize(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        serialize(arg0: boolean): $CompoundTag;
        setSide<T>(arg0: $BlockCapability<never, $Direction_>, arg1: T, arg2: $Direction_): void;
        remove(arg0: $BlockCapability<never, $Direction_>, ...arg1: $Direction_[]): void;
        set<T>(arg0: $BlockCapability<never, $Direction_>, arg1: T, ...arg2: $Direction_[]): void;
        constructor(arg0: $TileBCore);
    }
    export class $TileBCore extends $BlockEntity implements $IDataManagerProvider, $IDataRetainingTile, $Nameable {
        writeToItemStack(arg0: $HolderLookup$Provider, arg1: $CompoundTag_, arg2: boolean): void;
        readFromItemStack(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        updateBlock(): void;
        hasCustomName(): boolean;
        getCustomName(): $Component;
        setCustomName(arg0: string): void;
        onNeighborChange(arg0: $BlockPos_): void;
        sendPacketToServer(arg0: $Consumer_<$MCDataOutput>, arg1: number): void;
        addTickable<T extends $Runnable>(arg0: T): T;
        detectAndSendChanges(arg0: boolean): void;
        getUpdatePacket(): $ClientboundBlockEntityDataPacket;
        getAccessingPlayers(): $Set<$Player>;
        writeExtraNBT(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        readExtraNBT(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        createServerBoundPacket(arg0: number): $PacketCustom;
        createClientBoundPacket(arg0: number): $PacketCustom;
        sendPacketToClients(arg0: $Collection_<$Player>, arg1: $Consumer_<$MCDataOutput>, arg2: number): void;
        sendPacketToClients(arg0: $Collection_<$Player>, arg1: $PacketCustom): void;
        writeExtraTileAndStack(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        readExtraTileAndStack(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        onTileLoaded(): void;
        static sendEnergyTo(arg0: $LevelReader, arg1: $BlockPos_, arg2: number, arg3: $Direction_): number;
        sendEnergyTo(arg0: number, arg1: $Direction_): number;
        setupPowerSlot(arg0: $IItemHandler, arg1: number, arg2: $IOPStorage, arg3: boolean): void;
        setupPowerSlot(arg0: $IItemHandler, arg1: number, arg2: $IOPStorage, arg3: $ManagedBool): void;
        onSignalChange(arg0: boolean): void;
        getAccessDistanceSq(): number;
        receivePacketFromClient(arg0: $MCDataInput, arg1: $ServerPlayer, arg2: number): void;
        sendPacketToChunk(arg0: $Consumer_<$MCDataOutput>, arg1: number): void;
        setClientSidePacketHandler(arg0: number, arg1: $Consumer_<$MCDataInput>): void;
        setServerSidePacketHandler(arg0: number, arg1: $BiConsumer_<$MCDataInput, $ServerPlayer>): void;
        dirtyBlock(): void;
        removeTickable(arg0: $Runnable_): boolean;
        setSavedDataObject(arg0: string, arg1: $INBTSerializable<$CompoundTag_>): void;
        setItemSavedDataObject(arg0: string, arg1: $INBTSerializable<$CompoundTag_>): void;
        static sendEnergyToAll(arg0: $LevelReader, arg1: $BlockPos_, arg2: number, arg3: number): number;
        sendEnergyToAll(arg0: number, arg1: number): number;
        installIOTracker(arg0: $OPStorage): void;
        onInterval(arg0: number): boolean;
        setRSMode(arg0: $IRSSwitchable$RSMode_): void;
        cycleRSMode(arg0: boolean): void;
        isTileEnabled(): boolean;
        hasRSSignal(): boolean;
        getRSSignal(): number;
        enablePlayerAccessTracking(arg0: boolean): void;
        onPlayerCloseContainer(arg0: $Player): void;
        posSeed(): number;
        toggleDebugOutput(arg0: $Player): boolean;
        getDisplayName(): $Component;
        tick(): void;
        onPlayerOpenContainer(arg0: $Player): void;
        receivePacketFromServer(arg0: $MCDataInput, arg1: number): void;
        getCapManager(): $TileCapabilityManager;
        sendPacketToClient(arg0: $ServerPlayer, arg1: $Consumer_<$MCDataOutput>, arg2: number): void;
        sendPacketToClient(arg0: $Consumer_<$MCDataOutput>, arg1: number): $PacketCustom;
        getRSMode(): $IRSSwitchable$RSMode;
        debugEnabled(): boolean;
        getTime(): number;
        getName(): $Component;
        register<M extends $IManagedData>(arg0: M): M;
        debug(arg0: $Object): void;
        saveToItem(): boolean;
        getDataManager(): $IDataManager;
        static ATTACHMENTS_NBT_KEY: string;
        static LOGGER: $Logger;
        constructor(arg0: $BlockEntityType_<never>, arg1: $BlockPos_, arg2: $BlockState_);
        get updatePacket(): $ClientboundBlockEntityDataPacket;
        get accessingPlayers(): $Set<$Player>;
        get accessDistanceSq(): number;
        get tileEnabled(): boolean;
        get RSSignal(): number;
        get displayName(): $Component;
        get capManager(): $TileCapabilityManager;
        get time(): number;
        get name(): $Component;
        get dataManager(): $IDataManager;
    }
    export class $SerializationFlags<D extends $INBTSerializable<$CompoundTag>> {
        saveItem(): $SerializationFlags<D>;
        saveTile(): $SerializationFlags<D>;
        lazyLoadDefault(arg0: $HolderLookup$Provider): void;
        syncTile(): $SerializationFlags<D>;
        syncContainer(): $SerializationFlags<D>;
        saveBoth(): $SerializationFlags<D>;
        getData(): D;
        constructor(arg0: string, arg1: D);
        get data(): D;
    }
}
