import { $MultiBufferSource$BufferSource } from "@package/net/minecraft/client/renderer";
import { $Component, $Component_ } from "@package/net/minecraft/network/chat";
import { $Minecraft } from "@package/net/minecraft/client";
import { $List } from "@package/java/util";
import { $GuiElement } from "@package/codechicken/lib/gui/modular/elements";
import { $Consumer_ } from "@package/java/util/function";
import { $Screen } from "@package/net/minecraft/client/gui/screens";
import { $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $TriConsumer_ } from "@package/org/apache/logging/log4j/util";
import { $GuiProvider, $GuiRender, $GuiProvider_ } from "@package/codechicken/lib/gui/modular/lib";
import { $Slot } from "@package/net/minecraft/world/inventory";
import { $Font } from "@package/net/minecraft/client/gui";
import { $Runnable_ } from "@package/java/lang";
import { $GeoParam_, $GeoRef, $GuiParent } from "@package/codechicken/lib/gui/modular/lib/geometry";
export * as elements from "@package/codechicken/lib/gui/modular/elements";
export * as lib from "@package/codechicken/lib/gui/modular/lib";
export * as sprite from "@package/codechicken/lib/gui/modular/sprite";

declare module "@package/codechicken/lib/gui/modular" {
    export class $ModularGui implements $GuiParent<$ModularGui> {
        doesFloatingItemDisableToolTips(): boolean;
        vanillaSlotRendering(): boolean;
        getSlotHandler(arg0: $Slot): $GuiElement<never>;
        getJeiExclusions(): $List<$GuiElement<never>>;
        setJeiHighlightTime(arg0: number): void;
        getJeiDropTargets(): $List<$GuiElement<never>>;
        getScreen(): $Screen;
        isPauseScreen(): boolean;
        mouseMoved(arg0: number, arg1: number): void;
        xMin(): number;
        yMin(): number;
        xMax(): number;
        yMax(): number;
        mouseScrolled(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        charTyped(arg0: string, arg1: number): boolean;
        keyPressed(arg0: number, arg1: number, arg2: number): boolean;
        setScreen(arg0: $Screen): void;
        renderBackground(): boolean;
        onTick(arg0: $Runnable_): void;
        keyReleased(arg0: number, arg1: number, arg2: number): boolean;
        mouseClicked(arg0: number, arg1: number, arg2: number): boolean;
        mouseReleased(arg0: number, arg1: number, arg2: number): boolean;
        setCursor(arg0: $ResourceLocation_): void;
        onResize(arg0: $Runnable_): void;
        renderScreenBackground(arg0: boolean): void;
        getParentScreen(): $Screen;
        getGuiTitle(): $Component;
        closeOnEscape(): boolean;
        onGuiClose(): void;
        adoptChild(arg0: $GuiElement<never>): void;
        scaledScreenWidth(): number;
        scaledScreenHeight(): number;
        getModularGui(): $ModularGui;
        getJeiHighlightTime(): number;
        computeMouseX(): number;
        computeMouseY(): number;
        setGuiTitle(arg0: $Component_): void;
        setPauseScreen(arg0: boolean): void;
        setCloseOnEscape(arg0: boolean): void;
        getDirectRoot(): $GuiElement<never>;
        initStandardGui(arg0: number, arg1: number): $ModularGui;
        initFullscreenGui(): $ModularGui;
        setVanillaSlotRendering(arg0: boolean): void;
        /**
         * @deprecated
         */
        createRender(arg0: $MultiBufferSource$BufferSource): $GuiRender;
        setSlotHandler(arg0: $Slot, arg1: $GuiElement<never>): void;
        setFloatingItemDisablesToolTips(arg0: boolean): void;
        onKeyPressPre(arg0: $TriConsumer_<number, number, number>): void;
        onKeyPressPost(arg0: $TriConsumer_<number, number, number>): void;
        removeChild(arg0: $GuiElement<never>): void;
        getProvider(): $GuiProvider;
        addChild(arg0: $GuiElement<never>): void;
        addChild(arg0: $Consumer_<$ModularGui>): $ModularGui;
        tick(): void;
        xSize(): number;
        ySize(): number;
        getChildren(): $List<$GuiElement<never>>;
        onScreenInit(arg0: $Minecraft, arg1: $Font, arg2: number, arg3: number): void;
        onMouseClickPre(arg0: $TriConsumer_<number, number, number>): void;
        onMouseClickPost(arg0: $TriConsumer_<number, number, number>): void;
        renderOverlay(arg0: $GuiRender, arg1: number): boolean;
        onClose(arg0: $Runnable_): void;
        font(): $Font;
        render(arg0: $GuiRender, arg1: number): void;
        mc(): $Minecraft;
        getRoot(): $GuiElement<never>;
        isDescendantOf(arg0: $GuiElement<never>): boolean;
        blockMouseOver(arg0: $GuiElement<never>, arg1: number, arg2: number): boolean;
        get(arg0: $GeoParam_): $GeoRef;
        getValue(arg0: $GeoParam_): number;
        constructor(arg0: $GuiProvider_);
        constructor(arg0: $GuiProvider_, arg1: $Screen);
        get jeiExclusions(): $List<$GuiElement<never>>;
        get jeiDropTargets(): $List<$GuiElement<never>>;
        set cursor(value: $ResourceLocation_);
        get parentScreen(): $Screen;
        get modularGui(): $ModularGui;
        get directRoot(): $GuiElement<never>;
        set floatingItemDisablesToolTips(value: boolean);
        get provider(): $GuiProvider;
        get children(): $List<$GuiElement<never>>;
        get root(): $GuiElement<never>;
    }
}
