import { $MultiBufferSource_ } from "@package/net/minecraft/client/renderer";
import { $Pair } from "@package/com/mojang/datafixers/util";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $SoundBuffer } from "@package/com/mojang/blaze3d/audio";
import { $EntityType, $Entity } from "@package/net/minecraft/world/entity";
import { $Camera } from "@package/net/minecraft/client";
import { $UUID, $UUID_, $ArrayList, $Map, $Set } from "@package/java/util";
import { $Animation } from "@package/org/figuramc/figura/animation";
import { $PlayerRenderer } from "@package/net/minecraft/client/renderer/entity/player";
import { $EntityModel } from "@package/net/minecraft/client/model";
import { $Consumer_ } from "@package/java/util/function";
import { $Direction_ } from "@package/net/minecraft/core";
import { $PermissionPack$PlayerPermissionPack, $Permissions } from "@package/org/figuramc/figura/permissions";
import { $FiguraModelPart, $ParentType_ } from "@package/org/figuramc/figura/model";
import { $FiguraTexture } from "@package/org/figuramc/figura/model/rendering/texture";
import { $FiguraOutputStream, $FiguraBuffer, $FiguraInputStream } from "@package/org/figuramc/figura/lua/api/data";
import { $Object } from "@package/java/lang";
import { $ItemStackAPI, $BlockStateAPI } from "@package/org/figuramc/figura/lua/api/world";
import { $LivingEntityRenderer } from "@package/net/minecraft/client/renderer/entity";
import { $Component } from "@package/net/minecraft/network/chat";
import { $ModelPart } from "@package/net/minecraft/client/model/geom";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $FiguraLuaRuntime } from "@package/org/figuramc/figura/lua";
import { $RefilledNumber, $Version } from "@package/org/figuramc/figura/utils";
import { $NativeImage } from "@package/com/mojang/blaze3d/platform";
import { $EntityRenderMode_, $PartFilterScheme_, $EntityRenderMode, $AvatarRenderer } from "@package/org/figuramc/figura/model/rendering";
import { $FiguraMat4 } from "@package/org/figuramc/figura/math/matrix";
import { $EntityAPI } from "@package/org/figuramc/figura/lua/api/entity";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $FiguraVec3 } from "@package/org/figuramc/figura/math/vector";
import { $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $LuaValue, $Varargs } from "@package/org/luaj/vm2";

declare module "@package/org/figuramc/figura/avatar" {
    export class $Avatar$Instructions {
        post(): $Avatar$Instructions;
        use(amount: number): void;
        getTotal(): number;
        reset(remaining: number): void;
        pre: number;
        max: number;
        remaining: number;
        constructor(remaining: number);
        get total(): number;
    }
    export class $Avatar {
        renderItem(stack: $PoseStack, bufferSource: $MultiBufferSource_, part: $FiguraModelPart, light: number, overlay: number): boolean;
        applyAnimations(): void;
        clearAnimations(): void;
        useItemEvent(stack: $ItemStackAPI, type: string, particleCount: number): boolean;
        damageEvent(sourceType: string, sourceCause: $EntityAPI<never>, sourceDirect: $EntityAPI<never>, sourcePosition: $FiguraVec3): void;
        chatSendMessageEvent(message: string): string;
        itemRenderEvent(item: $ItemStackAPI, mode: string, pos: $FiguraVec3, rot: $FiguraVec3, scale: $FiguraVec3, leftHanded: boolean, stack: $PoseStack, bufferSource: $MultiBufferSource_, light: number, overlay: number): boolean;
        worldRender(entity: $Entity, camX: number, camY: number, camZ: number, stack: $PoseStack, bufferSource: $MultiBufferSource_, lightFallback: number, tickDelta: number, mode: $EntityRenderMode_): void;
        firstPersonWorldRender(watcher: $Entity, bufferSource: $MultiBufferSource_, matrices: $PoseStack, camera: $Camera, tickDelta: number): void;
        postWorldRenderEvent(delta: number): void;
        chatReceivedMessageEvent(message: string, json: string): $Pair<string, number>;
        keyPressEvent(key: number, action: number, modifiers: number): boolean;
        charTypedEvent(chars: string, modifiers: number, codePoint: number): void;
        mousePressEvent(button: number, action: number, modifiers: number): boolean;
        mouseScrollEvent(delta: number): boolean;
        mouseMoveEvent(x: number, y: number): boolean;
        tick(): void;
        arrowRenderEvent(delta: number, arrow: $EntityAPI<never>): boolean;
        tridentRenderEvent(delta: number, trident: $EntityAPI<never>): boolean;
        playSoundEvent(id: string, pos: $FiguraVec3, vol: number, pitch: number, loop: boolean, category: string, file: string): boolean;
        resourceReloadEvent(): void;
        capeRender(entity: $Entity, bufferSource: $MultiBufferSource_, stack: $PoseStack, light: number, tickDelta: number, cloak: $ModelPart): void;
        elytraRender(entity: $Entity, bufferSource: $MultiBufferSource_, stack: $PoseStack, light: number, tickDelta: number, model: $EntityModel<never>): void;
        hudRender(stack: $PoseStack, bufferSource: $MultiBufferSource_, entity: $Entity, tickDelta: number): void;
        skullRender(stack: $PoseStack, bufferSource: $MultiBufferSource_, light: number, direction: $Direction_, yaw: number): boolean;
        headRender(stack: $PoseStack, bufferSource: $MultiBufferSource_, light: number, useComplexity: boolean): boolean;
        renderPortrait(gui: $GuiGraphics, x: number, y: number, size: number, modelScale: number, upsideDown: boolean): boolean;
        renderTrident(stack: $PoseStack, bufferSource: $MultiBufferSource_, delta: number, light: number): boolean;
        clearSounds(): void;
        clearParticles(): void;
        closeBuffers(): void;
        tickEvent(): void;
        runPing(id: number, data: number[]): void;
        skullRenderEvent(delta: number, block: $BlockStateAPI, item: $ItemStackAPI, entity: $EntityAPI<never>, mode: string): boolean;
        loadSound(name: string, data: number[]): void;
        registerTexture(name: string, image: $NativeImage, ignoreSize: boolean): $FiguraTexture;
        firstPersonRender(stack: $PoseStack, bufferSource: $MultiBufferSource_, player: $Player, playerRenderer: $PlayerRenderer, arm: $ModelPart, light: number, tickDelta: number): void;
        updateMatrices(entityRenderer: $LivingEntityRenderer<never, never>, stack: $PoseStack): void;
        renderEvent(delta: number, poseMatrix: $FiguraMat4): void;
        postRenderEvent(delta: number, poseMatrix: $FiguraMat4): void;
        punish(amount: number): void;
        pivotPartRender(parent: $ParentType_, consumer: $Consumer_<$PoseStack>): boolean;
        renderArrow(stack: $PoseStack, bufferSource: $MultiBufferSource_, delta: number, light: number): boolean;
        totemEvent(): boolean;
        render(delta: number): void;
        render(entity: $Entity, yaw: number, delta: number, alpha: number, stack: $PoseStack, bufferSource: $MultiBufferSource_, light: number, overlay: number, entityRenderer: $LivingEntityRenderer<never, never>, filter: $PartFilterScheme_, translucent: boolean, glowing: boolean): void;
        closeStreams(): void;
        loadScript(name: string, chunk: string): $LuaValue;
        run(toRun: $Object, limit: $Avatar$Instructions, ...args: $Object[]): $Varargs;
        load(nbt: $CompoundTag_): void;
        clean(): void;
        hasTexture: boolean;
        nbt: $CompoundTag;
        permissionsToTick: $Set<$Permissions>;
        complexity: $Avatar$Instructions;
        renderer: $AvatarRenderer;
        customSounds: $Map<string, $SoundBuffer>;
        soundsRemaining: $RefilledNumber;
        color: string;
        openInputStreams: $ArrayList<$FiguraInputStream>;
        versionStatus: number;
        loaded: boolean;
        isHost: boolean;
        minify: boolean;
        openBuffers: $ArrayList<$FiguraBuffer>;
        noPermissions: $Set<$Permissions>;
        customInstructions: $Map<string, $Avatar$Instructions>;
        entityName: string;
        permissions: $PermissionPack$PlayerPermissionPack;
        badgeToColor: $Map<string, string>;
        animations: $Map<number, $Animation>;
        scriptError: boolean;
        id: string;
        openOutputStreams: $ArrayList<$FiguraOutputStream>;
        lastPlayingSound: number;
        static firstPerson: boolean;
        owner: $UUID;
        particlesRemaining: $RefilledNumber;
        animationComplexity: number;
        init: $Avatar$Instructions;
        worldTick: $Avatar$Instructions;
        entityType: $EntityType<never>;
        resources: $Map<string, number[]>;
        version: $Version;
        animation: $Avatar$Instructions;
        renderMode: $EntityRenderMode;
        errorText: $Component;
        fileSize: number;
        name: string;
        luaRuntime: $FiguraLuaRuntime;
        authors: string;
        constructor(entity: $Entity);
        constructor(owner: $UUID_);
    }
}
