import { $NumberProviderWrapper } from "@package/com/almostreliable/lootjs/kube/wrappers";
import { $IsInBiomeWithTagConditionWrapper, $IsInDimensionTypeConditionWrapper, $IsInDimensionConditionWrapper, $IsInBiomeConditionWrapper, $EntityToSacrificeWrapper, $WeightedRecipeResultWrapper, $RecipeResultWrapper } from "@package/com/klikli_dev/occultism_kubejs/component";
import { $SpellData, $SpellRarity, $CastType } from "@package/io/redspace/ironsspellbooks/api/spells";
import { $KJSBotanyPotsPlugin$GrowthAmountBinding, $KJSBotanyPotsPlugin$DisplayStateBinding, $KJSBotanyPotsPlugin$DropItemBinding } from "@package/com/bobvarioa/kjsbotanypots";
import { $Minecraft } from "@package/net/minecraft/client";
import { $TargetEntityCastData } from "@package/io/redspace/ironsspellbooks/capabilities/magic";
import { $ParticleHelper } from "@package/io/redspace/ironsspellbooks/util";
import { $KJSTPluginUtils } from "@package/dev/uncandango/kubejstweaks/kubejs/plugin";
import { $CuriosApi } from "@package/top/theillusivec4/curios/api";
import { $SpiritRepairRegexDataJSComponentWrapper, $SpiritJSComponentWrapper } from "@package/com/sammy/malum/compat/kubejs/wrapper";
import { $RotationAxis, $NBTIOWrapper, $MobEffectUtil, $JsonUtils, $NotificationToastData, $JsonIO, $ID, $FluidAmounts } from "@package/dev/latvian/mods/kubejs/util";
import { $GustDefenseGoal, $SpellBarrageGoal, $WizardRecoverGoal, $WarlockAttackGoal, $WizardSupportGoal, $WizardAttackGoal, $WispAttackGoal } from "@package/io/redspace/ironsspellbooks/entity/mobs/goals";
import { $ItemFilter } from "@package/com/almostreliable/lootjs/core/filters";
import { $ConsoleJS, $PlatformWrapper } from "@package/dev/latvian/mods/kubejs/script";
import { $AuraBlockUtils, $AuraChunkUtils, $AuraItemUtils } from "@package/com/falaut/kubejsnaturesaura/utils";
import { $Items } from "@package/net/minecraft/world/item";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $KMath, $TextWrapper, $IngredientWrapper, $SizedIngredientWrapper, $UUIDWrapper, $ParticleOptionsWrapper, $RegistryWrapper, $EntitySelectorWrapper, $NBTWrapper, $BlockWrapper, $DirectionWrapper, $NativeEventWrapper, $JavaWrapper, $UtilsWrapper, $TextIcons, $ColorWrapper, $AABBWrapper, $StringUtilsWrapper, $ItemWrapper, $DataMapWrapper } from "@package/dev/latvian/mods/kubejs/plugin/builtin/wrapper";
import { $AnimationHolder, $Utils } from "@package/io/redspace/ironsspellbooks/api/util";
import { $Duration } from "@package/java/time";
import { $BlockStateProperties } from "@package/net/minecraft/world/level/block/state/properties";
import { $SoundType, $Blocks } from "@package/net/minecraft/world/level/block";
import { $LootEntry } from "@package/com/almostreliable/lootjs/core/entry";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $PotionRegistry } from "@package/io/redspace/ironsspellbooks/registries";
import { $Stats } from "@package/net/minecraft/stats";
import { $Matrix4f, $Vector4f, $Vector3f, $Quaternionf, $Matrix3f } from "@package/org/joml";
import { $ModelResourceLocation } from "@package/net/minecraft/client/resources/model";
import { $AbstractMap } from "@package/java/util";
import { $CapabilityCurios$CuriosCapabilityBuilder } from "@package/net/zhaiji/kubejscurios/curios";
import { $LootCondition, $Predicates, $LootFunction } from "@package/com/almostreliable/lootjs/loot";
import { $GeneratorsCreateOutput } from "@package/dev/bluephs/dgjs/wrapper";
import { $BlockPos, $Vec3i } from "@package/net/minecraft/core";
import { $LootType } from "@package/com/almostreliable/lootjs/core";
import { $IconTextures, $GuiTextures } from "@package/com/miiickey/kubejei/kubejs/util";
import { $OverlayTexture } from "@package/net/minecraft/client/renderer/texture";
import { $Math } from "@package/java/lang";
import { $ItemTags } from "@package/net/minecraft/tags";
import { $BlockStatePredicate } from "@package/dev/latvian/mods/kubejs/block/state";
import { $ICurioRenderer } from "@package/top/theillusivec4/curios/api/client";
import { $FluidWrapper } from "@package/dev/latvian/mods/kubejs/fluid";
import { $KubeCreateOutput } from "@package/dev/latvian/mods/kubejs/create/wrapper";
import { $AppliedKJSAPI$Devices, $AppliedKJSAPI$Compat, $AppliedKJSAPI$Crafting, $AppliedKJSAPI$Network, $AppliedKJSAPI$Recipes, $AppliedKJSAPI$Utils, $AppliedKJSAPI, $AppliedKJSAPI$Progression, $AppliedKJSAPI$Keys, $AppliedKJSAPI$Debug } from "@package/com/rollylindenshnizzer/appliedkjs";
import { $ProcessingOutput } from "@package/com/simibubi/create/content/processing/recipe";
import { $AbstractSpellWrapper } from "@package/com/squoshi/irons_spells_js/spell";
import { $MinMaxBounds$Doubles, $LocationPredicate, $ItemPredicate, $MobEffectsPredicate, $DistancePredicate, $EntityEquipmentPredicate, $EnchantmentPredicate, $BlockPredicate, $NbtPredicate, $LightPredicate, $FluidPredicate, $EntityPredicate } from "@package/net/minecraft/advancements/critereon";
import { $SchoolRegistry, $SpellRegistry } from "@package/io/redspace/ironsspellbooks/api/registry";
import { $AlmostKube } from "@package/com/almostreliable/unified/compat/kube";
import { $Potions } from "@package/net/minecraft/world/item/alchemy";
import { $BasicOptions } from "@package/net/darkhax/botanypots/common/impl/data/display/types";
import { $DamageSource } from "@package/net/minecraft/world/damagesource";

declare module "@side-only/server/bindings" {
}

export {};

declare global {
    let global: {};
    let Platform: typeof $PlatformWrapper;
    let console: $ConsoleJS;
    let JavaMath: typeof $Math;
    let ID: typeof $ID;
    let Duration: typeof $Duration;
    let KMath: typeof $KMath;
    let Utils: typeof $UtilsWrapper;
    let StringUtils: typeof $StringUtilsWrapper;
    let Java: typeof $JavaWrapper;
    let Text: typeof $TextWrapper;
    let Component: typeof $TextWrapper;
    let TextIcons: typeof $TextIcons;
    let UUID: typeof $UUIDWrapper;
    let JsonUtils: typeof $JsonUtils;
    let JsonIO: typeof $JsonIO;
    let Block: typeof $BlockWrapper;
    let Blocks: typeof $Blocks;
    let Item: typeof $ItemWrapper;
    let Items: typeof $Items;
    let Ingredient: typeof $IngredientWrapper;
    let NBT: typeof $NBTWrapper;
    let NBTIO: typeof $NBTIOWrapper;
    let Direction: typeof $DirectionWrapper;
    let Facing: typeof $DirectionWrapper;
    let AABB: typeof $AABBWrapper;
    let Stats: typeof $Stats;
    let FluidAmounts: typeof $FluidAmounts;
    let Notification: typeof $NotificationToastData;
    let SizedIngredient: typeof $SizedIngredientWrapper;
    let ParticleOptions: typeof $ParticleOptionsWrapper;
    let Registry: typeof $RegistryWrapper<any>;
    let DataMap: typeof $DataMapWrapper<any, any>;
    let EntitySelector: typeof $EntitySelectorWrapper;
    let Fluid: typeof $FluidWrapper;
    let SECOND: number;
    let MINUTE: number;
    let HOUR: number;
    let Color: typeof $ColorWrapper;
    let BlockStatePredicate: typeof $BlockStatePredicate;
    let Vec3d: typeof $Vec3;
    let Vec3i: typeof $Vec3i;
    let Vec3f: typeof $Vector3f;
    let Vec4f: typeof $Vector4f;
    let Matrix3f: typeof $Matrix3f;
    let Matrix4f: typeof $Matrix4f;
    let Quaternionf: typeof $Quaternionf;
    let RotationAxis: typeof $RotationAxis;
    let BlockPos: typeof $BlockPos;
    let DamageSource: typeof $DamageSource;
    let SoundType: typeof $SoundType;
    let BlockProperties: typeof $BlockStateProperties;
    let NativeEvents: typeof $NativeEventWrapper;
    let MobEffectUtil: typeof $MobEffectUtil;
    let Client: $Minecraft;
    let GLFWInput: $AbstractMap<any, any>;
    let CuriosJSCapabilityBuilder: $CapabilityCurios$CuriosCapabilityBuilder;
    let CuriosApi: typeof $CuriosApi;
    let CuriosRenderer: typeof $ICurioRenderer;
    let ModelResourceLocation: typeof $ModelResourceLocation;
    let OverlayTexture: typeof $OverlayTexture;
    let AuraBlock: $AuraBlockUtils;
    let AuraItem: $AuraItemUtils;
    let AuraChunk: $AuraChunkUtils;
    let IconTextures: typeof $IconTextures;
    let GuiTextures: typeof $GuiTextures;
    let SpellRarity: typeof $SpellRarity;
    let SchoolRegistry: typeof $SchoolRegistry;
    let CastType: typeof $CastType;
    let IronsSpellsParticleHelper: typeof $ParticleHelper;
    let SpellRegistry: typeof $SpellRegistry;
    let ItemTags: typeof $ItemTags;
    let Player: typeof $Player;
    let SpellData: typeof $SpellData;
    let Spell: typeof $AbstractSpellWrapper;
    let ISSAnimationHolder: typeof $AnimationHolder;
    let ISSUtils: typeof $Utils;
    let TargetEntityCastData: typeof $TargetEntityCastData;
    let Potions: typeof $Potions;
    let ISSPotionRegistry: typeof $PotionRegistry;
    let WizardAttackGoal: typeof $WizardAttackGoal;
    let WarlockAttackGoal: typeof $WarlockAttackGoal;
    let WizardRecoverGoal: typeof $WizardRecoverGoal;
    let WizardSupportGoal: typeof $WizardSupportGoal<any>;
    let SpellBarrageGoal: typeof $SpellBarrageGoal;
    let GustDefenseGoal: typeof $GustDefenseGoal;
    let WispAttackGoal: typeof $WispAttackGoal;
    let DisplayState: typeof $KJSBotanyPotsPlugin$DisplayStateBinding;
    let DisplayStateOptions: typeof $BasicOptions;
    let DropItem: typeof $KJSBotanyPotsPlugin$DropItemBinding;
    let GrowthAmount: typeof $KJSBotanyPotsPlugin$GrowthAmountBinding;
    let KJSTweaks: typeof $KJSTPluginUtils;
    let Output: typeof $GeneratorsCreateOutput;
    let DgjsProcessingOutput: typeof $ProcessingOutput;
    let LootType: typeof $LootType;
    let ItemFilter: typeof $ItemFilter;
    let LootEntry: typeof $LootEntry;
    let LootCondition: $LootCondition;
    let LootFunction: $LootFunction;
    let Range: typeof $MinMaxBounds$Doubles;
    let NumberProvider: typeof $NumberProviderWrapper;
    let Predicates: typeof $Predicates;
    let ItemPredicate: typeof $ItemPredicate;
    let EntityPredicate: typeof $EntityPredicate;
    let EntityEquipmentPredicate: typeof $EntityEquipmentPredicate;
    let LocationPredicate: typeof $LocationPredicate;
    let DistancePredicate: typeof $DistancePredicate;
    let BlockPredicate: typeof $BlockPredicate;
    let FluidPredicate: typeof $FluidPredicate;
    let LightPredicate: typeof $LightPredicate;
    let EnchantmentPredicate: typeof $EnchantmentPredicate;
    let MobEffectsPredicate: typeof $MobEffectsPredicate;
    let NbtPredicate: typeof $NbtPredicate;
    let RecipeResult: typeof $RecipeResultWrapper;
    let WeightedRecipeResult: typeof $WeightedRecipeResultWrapper;
    let EntityToSacrifice: typeof $EntityToSacrificeWrapper;
    let IsInBiomeCondition: typeof $IsInBiomeConditionWrapper;
    let IsInBiomeWithTagCondition: typeof $IsInBiomeWithTagConditionWrapper;
    let IsInDimensionCondition: typeof $IsInDimensionConditionWrapper;
    let IsInDimensionTypeCondition: typeof $IsInDimensionTypeConditionWrapper;
    let CreateItem: typeof $KubeCreateOutput;
    let CreateProcessingOutput: typeof $ProcessingOutput;
    let AE2: $AppliedKJSAPI;
    let AE2Compat: $AppliedKJSAPI$Compat;
    let AE2Utils: $AppliedKJSAPI$Utils;
    let AE2Recipes: $AppliedKJSAPI$Recipes;
    let AE2Network: $AppliedKJSAPI$Network;
    let AE2Keys: $AppliedKJSAPI$Keys;
    let AE2Crafting: $AppliedKJSAPI$Crafting;
    let AE2Devices: $AppliedKJSAPI$Devices;
    let AE2Debug: $AppliedKJSAPI$Debug;
    let AE2Progression: $AppliedKJSAPI$Progression;
    let AppliedKJS: $AppliedKJSAPI;
    let AppliedKJSCompat: $AppliedKJSAPI$Compat;
    let AppliedKJSUtils: $AppliedKJSAPI$Utils;
    let AppliedKJSRecipes: $AppliedKJSAPI$Recipes;
    let AppliedKJSNetwork: $AppliedKJSAPI$Network;
    let AppliedKJSKeys: $AppliedKJSAPI$Keys;
    let AppliedKJSCrafting: $AppliedKJSAPI$Crafting;
    let AppliedKJSDevices: $AppliedKJSAPI$Devices;
    let AppliedKJSDebug: $AppliedKJSAPI$Debug;
    let AppliedKJSProgression: $AppliedKJSAPI$Progression;
    let SpiritComponent: typeof $SpiritJSComponentWrapper;
    let RepairRegex: typeof $SpiritRepairRegexDataJSComponentWrapper;
    let AlmostUnified: typeof $AlmostKube;
}
