import { $Recipe, $Ingredient, $RecipeHolder_ } from "@package/net/minecraft/world/item/crafting";
import { $Codec } from "@package/com/mojang/serialization";
import { $ListTag_, $ListTag, $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $Either } from "@package/com/mojang/datafixers/util";
import { $HumanoidArm, $EquipmentSlot_, $Pose_, $EntityDimensions, $Entity$RemovalReason, $LivingEntity, $WalkAnimationState, $HumanoidArm_, $Pose, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $CallbackInfo, $CallbackInfoReturnable } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $PlayerAccessor as $PlayerAccessor$3 } from "@package/io/redspace/ironslib/mixin";
import { $LevelBlock } from "@package/dev/latvian/mods/kubejs/level";
import { $ItemPredicate_ } from "@package/dev/latvian/mods/kubejs/item";
import { $AnimationStack, $IAnimation } from "@package/dev/kosmx/playerAnim/api/layered";
import { $WeakReference } from "@package/java/lang/ref";
import { $SignatureValidator_, $Unit, $SignatureValidator, $OptionEnum } from "@package/net/minecraft/util";
import { $PlayerDamageShieldInvoker } from "@package/com/telepathicgrunt/the_bumblezone/mixin/items";
import { $InteractionResult, $MenuProvider, $InteractionHand, $InteractionHand_, $Nameable, $Container } from "@package/net/minecraft/world";
import { $CapeHolder } from "@package/dev/tr7zw/waveycapes/versionless";
import { $SoundEvent_, $SoundSource_ } from "@package/net/minecraft/sounds";
import { $PlayerFreezeExtension } from "@package/dev/ryanhcode/sable/mixinterface/player_freezing";
import { $FakePlayer } from "@package/net/neoforged/neoforge/common/util";
import { $Operation_ } from "@package/com/llamalad7/mixinextras/injector/wrapoperation";
import { $IPlayerExtension } from "@package/net/neoforged/neoforge/common/extensions";
import { $NotificationToastData_, $AttachedData } from "@package/dev/latvian/mods/kubejs/util";
import { $RegistryFriendlyByteBuf, $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $GameProfile } from "@package/com/mojang/authlib";
import { $StaminaProvider } from "@package/dev/cammiescorner/icarus/util";
import { $LocalIntRef } from "@package/com/llamalad7/mixinextras/sugar/ref";
import { $PlayerEnderChestContainer, $AbstractContainerMenu, $ClickAction_, $InventoryMenu } from "@package/net/minecraft/world/inventory";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";
import { $MerchantOffers } from "@package/net/minecraft/world/item/trading";
import { $Item_, $Item, $ItemCooldowns, $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $DynamicLightSource } from "@package/toni/sodiumdynamiclights";
import { $MutableComponent, $Component_, $ThrowingComponent, $Component } from "@package/net/minecraft/network/chat";
import { $IQuiverEntity } from "@package/net/mehvahdjukaar/supplementaries/common/entities";
import { $AnimationApplier } from "@package/dev/kosmx/playerAnim/impl/animation";
import { $MobEffectInstance, $MobEffect } from "@package/net/minecraft/world/effect";
import { $PlayerAccessor as $PlayerAccessor$2 } from "@package/fuzs/easymagic/mixin/accessor";
import { $FishingHook } from "@package/net/minecraft/world/entity/projectile";
import { $PlayerData } from "@package/dev/tr7zw/notenoughanimations/access";
import { $MinecraftPlayer } from "@package/dev/tr7zw/waveycapes/versionless/nms";
import { $Instant, $Duration_, $Duration } from "@package/java/time";
import { $IAnimatedPlayer } from "@package/dev/kosmx/playerAnim/impl";
import { $PlayerTypewriterExtension, $PlayerLaunchedPlungerExtension } from "@package/dev/simulated_team/simulated/mixin_interface";
import { $DroppedStacksExtension } from "@package/io/wispforest/accessories/pond";
import { $InventoryKJS, $PlayerKJS } from "@package/dev/latvian/mods/kubejs/core";
import { $AABB_, $Vec3, $AABB } from "@package/net/minecraft/world/phys";
import { $Stat_ } from "@package/net/minecraft/stats";
import { $Vector3dc } from "@package/org/joml";
import { $SlowFallingEntity } from "@package/dev/cammiescorner/icarus/api";
import { $PlayerAccessor as $PlayerAccessor$1 } from "@package/com/aetherteam/aether/mixin/mixins/common/accessor";
import { $AttackHand, $EntityPlayer_BetterCombat } from "@package/net/bettercombat/api";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $UUID_, $Set_, $Map, $OptionalInt, $Iterator, $UUID, $List, $Collection_, $List_, $Collection, $BitSet } from "@package/java/util";
import { $PlayerStatsJS, $KubeJSInventoryListener } from "@package/dev/latvian/mods/kubejs/player";
import { $AbstractHorse } from "@package/net/minecraft/world/entity/animal/horse";
import { $WardenSpawnTracker } from "@package/net/minecraft/world/entity/monster/warden";
import { $Supplier_, $Consumer_, $Predicate_ } from "@package/java/util/function";
import { $DataHolder } from "@package/dev/tr7zw/notenoughanimations/versionless/animations";
import { $AccessorPlayer } from "@package/com/illusivesoulworks/comforts/mixin";
import { $BlockPos, $GlobalPos, $BlockPos_, $GlobalPos_, $HolderLookup$Provider, $Holder, $Direction_, $NonNullList } from "@package/net/minecraft/core";
import { $Enum, $Record, $Class, $Object } from "@package/java/lang";
import { $GameType_, $BaseCommandBlock, $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $IntList, $Int2IntMap } from "@package/it/unimi/dsi/fastutil/ints";
import { $LaunchedPlungerEntity } from "@package/dev/simulated_team/simulated/content/entities/launched_plunger";
import { $TagKey_ } from "@package/net/minecraft/tags";
import { $Vector3 } from "@package/dev/tr7zw/waveycapes/versionless/util";
import { $PlayerAccessor } from "@package/net/mehvahdjukaar/supplementaries/mixins";
import { $PrivateKey, $PublicKey } from "@package/java/security";
import { $ItemEntity } from "@package/net/minecraft/world/entity/item";
import { $PlayerEntityAccessor } from "@package/net/bettercombat/mixin/player";
import { $BasicSimulation } from "@package/dev/tr7zw/waveycapes/versionless/sim";
import { $Trackable } from "@package/dev/uncandango/alltheleaks/mixin";
import { $PlayerEntityAccessor as $PlayerEntityAccessor$1 } from "@package/de/dafuqs/spectrum/api/entity";
import { $Stages } from "@package/dev/latvian/mods/kubejs/stages";
import { $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $StackedContentsRecipePickerAccessor } from "@package/umpaz/brewinandchewin/common/mixin";
import { $FoodProperties_, $FoodData } from "@package/net/minecraft/world/food";
import { $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $TemporaryPlayerData } from "@package/com/telepathicgrunt/the_bumblezone/entities";
import { $Scoreboard } from "@package/net/minecraft/world/scores";
import { $ISupportTransmog } from "@package/io/redspace/ironslib/game/client";
import { $SignBlockEntity, $StructureBlockEntity, $JigsawBlockEntity, $CommandBlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $PlayerAttackProperties } from "@package/net/bettercombat/logic";

declare module "@package/net/minecraft/world/entity/player" {
    export class $ProfileKeyPair extends $Record {
        dueRefresh(): boolean;
        refreshedAfter(): $Instant;
        publicKey(): $ProfilePublicKey;
        privateKey(): $PrivateKey;
        static CODEC: $Codec<$ProfileKeyPair>;
        constructor(arg0: $PrivateKey, arg1: $ProfilePublicKey_, arg2: $Instant);
    }
    /**
     * Values that may be interpreted as {@link $ProfileKeyPair}.
     */
    export type $ProfileKeyPair_ = { refreshedAfter?: $Instant, publicKey?: $ProfilePublicKey_, privateKey?: $PrivateKey,  } | [refreshedAfter?: $Instant, publicKey?: $ProfilePublicKey_, privateKey?: $PrivateKey, ];
    export class $ProfilePublicKey$Data extends $Record {
        hasExpired(arg0: $Duration_): boolean;
        hasExpired(): boolean;
        keySignature(): number[];
        expiresAt(): $Instant;
        write(arg0: $FriendlyByteBuf): void;
        key(): $PublicKey;
        static CODEC: $Codec<$ProfilePublicKey$Data>;
        constructor(arg0: $Instant, arg1: $PublicKey, arg2: number[]);
        constructor(arg0: $FriendlyByteBuf);
    }
    /**
     * Values that may be interpreted as {@link $ProfilePublicKey$Data}.
     */
    export type $ProfilePublicKey$Data_ = { keySignature?: number[], expiresAt?: $Instant, key?: $PublicKey,  } | [keySignature?: number[], expiresAt?: $Instant, key?: $PublicKey, ];
    export class $Abilities {
        loadSaveData(arg0: $CompoundTag_): void;
        getWalkingSpeed(): number;
        addSaveData(arg0: $CompoundTag_): void;
        getFlyingSpeed(): number;
        setFlyingSpeed(arg0: number): void;
        setWalkingSpeed(arg0: number): void;
        invulnerable: boolean;
        /**
         * @deprecated
         */
        mayfly: boolean;
        instabuild: boolean;
        mayBuild: boolean;
        flying: boolean;
        constructor();
    }
    export class $Inventory implements $Container, $Nameable {
        findSlotMatchingItem(arg0: $ItemStack_): number;
        setPickedItem(arg0: $ItemStack_): void;
        static isHotbarSlot(arg0: number): boolean;
        getDestroySpeed(arg0: $BlockState_): number;
        stillValid(arg0: $Player): boolean;
        dropAll(): void;
        getContainerSize(): number;
        removeItemNoUpdate(arg0: number): $ItemStack;
        getArmor(arg0: number): $ItemStack;
        setChanged(): void;
        removeFromSelected(arg0: boolean): $ItemStack;
        setItem(arg0: number, arg1: $ItemStack_): void;
        clearContent(): void;
        hasAnyMatching(arg0: $Predicate_<any>): boolean;
        fillStackedContents(arg0: $StackedContents): void;
        placeItemBackInInventory(arg0: $ItemStack_, arg1: boolean): void;
        placeItemBackInInventory(arg0: $ItemStack_): void;
        static getSelectionSize(): number;
        hasRemainingSpaceForItem(arg0: $ItemStack_, arg1: $ItemStack_): boolean;
        getFreeSlot(): number;
        getSuitableHotbarSlot(): number;
        pickSlot(arg0: number): void;
        findSlotMatchingUnusedItem(arg0: $ItemStack_): number;
        swapPaint(arg0: number): void;
        clearOrCountMatchingItems(arg0: $Predicate_<$ItemStack>, arg1: number, arg2: $Container): number;
        getSlotWithRemainingSpace(arg0: $ItemStack_): number;
        handler$mad000$moonlight$ml$fireDropEvent(ci: $CallbackInfo, var1: $Iterator<any>, list: $List_<any>, i: number): void;
        handler$mad000$moonlight$ml$restoreNotDropped(ci: $CallbackInfo, var1: $Iterator<any>, list: $List_<any>, i: number): void;
        getTimesChanged(): number;
        getSelected(): $ItemStack;
        removeItem(arg0: number, arg1: number): $ItemStack;
        removeItem(arg0: $ItemStack_): void;
        tick(): void;
        getItem(arg0: number): $ItemStack;
        replaceWith(arg0: $Inventory): void;
        addResource(arg0: number, arg1: $ItemStack_): number;
        getName(): $Component;
        load(arg0: $ListTag_): void;
        isEmpty(): boolean;
        add(arg0: $ItemStack_): boolean;
        add(arg0: number, arg1: $ItemStack_): boolean;
        contains(arg0: $TagKey_<$Item>): boolean;
        contains(arg0: $ItemStack_): boolean;
        contains(arg0: $Predicate_<$ItemStack>): boolean;
        save(arg0: $ListTag_): $ListTag;
        getMaxStackSize(): number;
        getMaxStackSize(arg0: $ItemStack_): number;
        canTakeItem(arg0: $Container, arg1: number, arg2: $ItemStack_): boolean;
        startOpen(arg0: $Player): void;
        stopOpen(arg0: $Player): void;
        canPlaceItem(arg0: number, arg1: $ItemStack_): boolean;
        countItem(arg0: $Item_): number;
        hasAnyOf(arg0: $Set_<$Item_>): boolean;
        hasCustomName(): boolean;
        getCustomName(): $Component;
        getDisplayName(): $Component;
        setTransferCooldown(arg0: number): void;
        canReceiveTransferCooldown(): boolean;
        lithium$itemInsertionTestRequiresStackSize1(): boolean;
        self(): $Container;
        clear(): void;
        getWidth(): number;
        getHeight(): number;
        setChanged(): void;
        asContainer(): $Container;
        getBlock(level: $Level_): $LevelBlock;
        isMutable(): boolean;
        setStackInSlot(slot: number, stack: $ItemStack_): void;
        getSlots(): number;
        getStackInSlot(slot: number): $ItemStack;
        insertItem(slot: number, stack: $ItemStack_, simulate: boolean): $ItemStack;
        extractItem(slot: number, amount: number, simulate: boolean): $ItemStack;
        getSlotLimit(slot: number): number;
        isItemValid(slot: number, stack: $ItemStack_): boolean;
        isEmpty(): boolean;
        clear(match: $ItemPredicate_): void;
        find(): number;
        find(match: $ItemPredicate_): number;
        count(match: $ItemPredicate_): number;
        count(): number;
        countNonEmpty(): number;
        countNonEmpty(match: $ItemPredicate_): number;
        getAllItems(): $List<$ItemStack>;
        insertItem(stack: $ItemStack_, simulate: boolean): $ItemStack;
        static NOT_FOUND_INDEX: number;
        armor: $NonNullList<$ItemStack>;
        static INVENTORY_SIZE: number;
        static POP_TIME_DURATION: number;
        static SLOT_OFFHAND: number;
        static ALL_ARMOR_SLOTS: number[];
        items: $NonNullList<$ItemStack>;
        compartments: $List<$NonNullList<$ItemStack>>;
        offhand: $NonNullList<$ItemStack>;
        selected: number;
        static HELMET_SLOT_ONLY: number[];
        player: $Player;
        constructor(arg0: $Player);
        set pickedItem(value: $ItemStack_);
        get containerSize(): number;
        static get selectionSize(): number;
        get freeSlot(): number;
        get suitableHotbarSlot(): number;
        get timesChanged(): number;
        get name(): $Component;
        get customName(): $Component;
        get displayName(): $Component;
        set transferCooldown(value: number);
        get width(): number;
        get height(): number;
        get mutable(): boolean;
        get slots(): number;
        get allItems(): $List<$ItemStack>;
    }
    export class $PlayerModelPart extends $Enum<$PlayerModelPart> {
        getBit(): number;
        getMask(): number;
        getName(): $Component;
        static values(): $PlayerModelPart[];
        static valueOf(arg0: string): $PlayerModelPart;
        getId(): string;
        static RIGHT_PANTS_LEG: $PlayerModelPart;
        static LEFT_PANTS_LEG: $PlayerModelPart;
        static JACKET: $PlayerModelPart;
        static RIGHT_SLEEVE: $PlayerModelPart;
        static HAT: $PlayerModelPart;
        static LEFT_SLEEVE: $PlayerModelPart;
        static CAPE: $PlayerModelPart;
        get bit(): number;
        get mask(): number;
        get id(): string;
    }
    /**
     * Values that may be interpreted as {@link $PlayerModelPart}.
     */
    export type $PlayerModelPart_ = "cape" | "jacket" | "left_sleeve" | "right_sleeve" | "left_pants_leg" | "right_pants_leg" | "hat";
    export class $StackedContents$RecipePicker implements $StackedContentsRecipePickerAccessor {
        tryPick(arg0: number, arg1: $IntList): boolean;
        tryPickAll(arg0: number, arg1: $IntList): number;
        brewinandchewin$getIngredients(): $List<$Ingredient>;
        brewinandchewin$getIngredientCount(): number;
        brewinandchewin$setIngredientCount(arg0: number): void;
        brewinandchewin$getItems(): number[];
        brewinandchewin$setItems(arg0: number[]): void;
        brewinandchewin$getItemCount(): number;
        brewinandchewin$setItemCount(arg0: number): void;
        brewinandchewin$getData(): $BitSet;
        brewinandchewin$setData(arg0: $BitSet): void;
        brewinandchewin$invokeGetUniqueAvailableIngredientItems(): number[];
        brewinandchewin$invokeGetIndex(arg0: boolean, arg1: number, arg2: number): number;
    }
    export class $ProfilePublicKey extends $Record {
        static createValidated(arg0: $SignatureValidator_, arg1: $UUID_, arg2: $ProfilePublicKey$Data_): $ProfilePublicKey;
        createSignatureValidator(): $SignatureValidator;
        data(): $ProfilePublicKey$Data;
        static EXPIRED_PROFILE_PUBLIC_KEY: $Component;
        static EXPIRY_GRACE_PERIOD: $Duration;
        static TRUSTED_CODEC: $Codec<$ProfilePublicKey>;
        constructor(arg0: $ProfilePublicKey$Data_);
    }
    /**
     * Values that may be interpreted as {@link $ProfilePublicKey}.
     */
    export type $ProfilePublicKey_ = { data?: $ProfilePublicKey$Data_,  } | [data?: $ProfilePublicKey$Data_, ];
    export class $Player$BedSleepingProblem extends $Enum<$Player$BedSleepingProblem> {
        static values(): $Player$BedSleepingProblem[];
        static valueOf(arg0: string): $Player$BedSleepingProblem;
        getMessage(): $Component;
        static OBSTRUCTED: $Player$BedSleepingProblem;
        static NOT_POSSIBLE_HERE: $Player$BedSleepingProblem;
        static NOT_POSSIBLE_NOW: $Player$BedSleepingProblem;
        static NOT_SAFE: $Player$BedSleepingProblem;
        static OTHER_PROBLEM: $Player$BedSleepingProblem;
        static TOO_FAR_AWAY: $Player$BedSleepingProblem;
        get message(): $Component;
    }
    /**
     * Values that may be interpreted as {@link $Player$BedSleepingProblem}.
     */
    export type $Player$BedSleepingProblem_ = "not_possible_here" | "not_possible_now" | "too_far_away" | "obstructed" | "other_problem" | "not_safe";
    export class $ChatVisiblity extends $Enum<$ChatVisiblity> implements $OptionEnum {
        static byId(arg0: number): $ChatVisiblity;
        static values(): $ChatVisiblity[];
        static valueOf(arg0: string): $ChatVisiblity;
        getKey(): string;
        getId(): number;
        getCaption(): $Component;
        static SYSTEM: $ChatVisiblity;
        static HIDDEN: $ChatVisiblity;
        static FULL: $ChatVisiblity;
        get key(): string;
        get id(): number;
        get caption(): $Component;
    }
    /**
     * Values that may be interpreted as {@link $ChatVisiblity}.
     */
    export type $ChatVisiblity_ = "full" | "system" | "hidden";
    export class $StackedContents {
        getBiggestCraftableStack(arg0: $RecipeHolder_<never>, arg1: number, arg2: $IntList): number;
        getBiggestCraftableStack(arg0: $RecipeHolder_<never>, arg1: $IntList): number;
        static fromStackingIndex(arg0: number): $ItemStack;
        accountStack(arg0: $ItemStack_, arg1: number): void;
        accountStack(arg0: $ItemStack_): void;
        accountSimpleStack(arg0: $ItemStack_): void;
        static getStackingIndex(arg0: $ItemStack_): number;
        canCraft(arg0: $Recipe<never>, arg1: $IntList): boolean;
        canCraft(arg0: $Recipe<never>, arg1: $IntList, arg2: number): boolean;
        clear(): void;
        contents: $Int2IntMap;
        constructor();
    }
    export class $ProfilePublicKey$ValidationException extends $ThrowingComponent {
        constructor(arg0: $Component_);
    }
    export class $Player extends $LivingEntity implements $IPlayerExtension, $PlayerAttackProperties, $EntityPlayer_BetterCombat, $PlayerAccessor, $IQuiverEntity, $DroppedStacksExtension, $TemporaryPlayerData, $PlayerDamageShieldInvoker, $PlayerAccessor$3, $ISupportTransmog, $Trackable, $PlayerData, $PlayerAccessor$2, $IAnimatedPlayer, $StaminaProvider, $SlowFallingEntity, $PlayerEntityAccessor, $PlayerAccessor$1, $PlayerTypewriterExtension, $PlayerLaunchedPlungerExtension, $DynamicLightSource, $PlayerFreezeExtension, $AccessorPlayer, $CapeHolder, $PlayerEntityAccessor$1, $PlayerKJS {
        getCooldowns(): $ItemCooldowns;
        getAbilities(): $Abilities;
        respawn(): void;
        attack(arg0: $Entity): void;
        resetAttackStrengthTicker(): void;
        /**
         * Checks, whether the player is in Creative mode.
         */
        isCreative(): boolean;
        displayClientMessage(arg0: $Component_, arg1: boolean): void;
        isLocalPlayer(): boolean;
        getGameProfile(): $GameProfile;
        isReducedDebugInfo(): boolean;
        isTextFilteringEnabled(): boolean;
        getAttackStrengthScale(arg0: number): number;
        /**
         * @deprecated
         */
        getDestroySpeed(arg0: $BlockState_): number;
        getComboCount(): number;
        setComboCount(comboCount: number): void;
        getCurrentAttack(): $AttackHand;
        toBeDroppedStacks(): $Collection<any>;
        blockActionRestricted(arg0: $Level_, arg1: $BlockPos_, arg2: $GameType_): boolean;
        mayBuild(): boolean;
        static createAttributes(): $AttributeSupplier$Builder;
        isAffectedByFluids(): boolean;
        getScoreboard(): $Scoreboard;
        handler$jmg00d$simplyswords$tick(ci: $CallbackInfo): void;
        stopSleepInBed(arg0: boolean, arg1: boolean): void;
        closeMenu(): void;
        handler$hep000$bettercombat$post_Tick(ci: $CallbackInfo): void;
        handler$dgg001$notenoughanimations$tick(info: $CallbackInfo): void;
        isSecondaryUseActive(): boolean;
        wrapOperation$nah000$spectrum$forceSwimmingState(arg0: $Player, arg1: $Pose_, arg2: $Operation_<any>): void;
        playNotifySound(arg0: $SoundEvent_, arg1: $SoundSource_, arg2: number, arg3: number): void;
        redirect$knf000$sable$fixRidingBoundingBox(arg0: $AABB_, arg1: $AABB_): $AABB;
        getShoulderEntityLeft(): $CompoundTag;
        getShoulderEntityRight(): $CompoundTag;
        handler$jmg000$simplyswords$tickMovement(ci: $CallbackInfo): void;
        getScore(): number;
        setScore(arg0: number): void;
        increaseScore(arg0: number): void;
        startAutoSpinAttack(arg0: number, arg1: number, arg2: $ItemStack_): void;
        resetStat(arg0: $Stat_<never>): void;
        setLastDeathLocation(arg0: ($GlobalPos_) | undefined): void;
        getDigSpeed(arg0: $BlockState_, arg1: $BlockPos_): number;
        /**
         * @deprecated
         */
        hasCorrectToolForDrops(arg0: $BlockState_): boolean;
        hasCorrectToolForDrops(arg0: $BlockState_, arg1: $Level_, arg2: $BlockPos_): boolean;
        handler$gfa000$icarus$readStamina(arg0: $CompoundTag_, arg1: $CallbackInfo): void;
        getLastDeathLocation(): ($GlobalPos) | undefined;
        handler$gfa000$icarus$saveStamina(arg0: $CompoundTag_, arg1: $CallbackInfo): void;
        handler$jch000$railways$addModDataVersions(arg0: $CompoundTag_, arg1: $CallbackInfo): void;
        disableShield(): void;
        canHarmPlayer(arg0: $Player): boolean;
        causeFoodExhaustion(arg0: number): void;
        openTextEdit(arg0: $SignBlockEntity, arg1: boolean): void;
        openMinecartCommandBlock(arg0: $BaseCommandBlock): void;
        openCommandBlock(arg0: $CommandBlockEntity): void;
        openStructureBlock(arg0: $StructureBlockEntity): void;
        openJigsawBlock(arg0: $JigsawBlockEntity): void;
        openHorseInventory(arg0: $AbstractHorse, arg1: $Container): void;
        openMenu(arg0: $MenuProvider): $OptionalInt;
        sendMerchantOffers(arg0: number, arg1: $MerchantOffers, arg2: number, arg3: number, arg4: boolean, arg5: boolean): void;
        openItemGui(arg0: $ItemStack_, arg1: $InteractionHand_): void;
        interactOn(arg0: $Entity, arg1: $InteractionHand_): $InteractionResult;
        modifyExpressionValue$fkc000$additionalentityattributes$additionalEntityAttributes$applyCriticalBonusDamage(arg0: number): number;
        modify$hep000$bettercombat$getHand(hand: $InteractionHand_): $InteractionHand;
        modifyExpressionValue$ndh000$universalenchants$attack(isSweepingSupported: boolean): boolean;
        entityInteractionRange(): number;
        sweepAttack(): void;
        crit(arg0: $Entity): void;
        magicCrit(arg0: $Entity): void;
        redirect$hep000$bettercombat$getMainHandStack_Redirect(instance: $Player): $ItemStack;
        redirect$hep000$bettercombat$setStackInHand_Redirect(instance: $Player, handArg: $InteractionHand_, itemStack: $ItemStack_): void;
        hasContainerOpen(): boolean;
        updateTutorialInventoryAction(arg0: $ItemStack_, arg1: $ItemStack_, arg2: $ClickAction_): void;
        startSleepInBed(arg0: $BlockPos_): $Either<$Player$BedSleepingProblem, $Unit>;
        isSleepingLongEnough(): boolean;
        getSleepTimer(): number;
        awardRecipes(arg0: $Collection_<$RecipeHolder_<never>>): number;
        triggerRecipeCrafted(arg0: $RecipeHolder_<never>, arg1: $List_<$ItemStack_>): void;
        awardRecipesByKey(arg0: $List_<$ResourceLocation_>): void;
        resetRecipes(arg0: $Collection_<$RecipeHolder_<never>>): number;
        handler$nah000$spectrum$updateSwimming(arg0: $CallbackInfo): void;
        tryResetCurrentImpulseContext(): void;
        resetCurrentImpulseContext(): void;
        tryToStartFallFlying(): boolean;
        handler$ngc000$brandonscore$tryToStartFallFlying(arg0: $CallbackInfoReturnable<any>, arg1: $ItemStack_): void;
        startFallFlying(): void;
        stopFallFlying(): void;
        giveExperiencePoints(arg0: number): void;
        localvar$nah000$spectrum$addExperience(arg0: number): number;
        getXpNeededForNextLevel(): number;
        giveExperienceLevels(arg0: number): void;
        getEnchantmentSeed(): number;
        onEnchantmentPerformed(arg0: $ItemStack_, arg1: number): void;
        handler$ekd000$taxfreelevels$rememberExperienceLevel(enchantedItem: $ItemStack_, experienceLevels: number, ci: $CallbackInfo, previousLevel: $LocalIntRef): void;
        handler$ekh000$taxfreelevels$flattenEnchantmentCost(enchantedItem: $ItemStack_, experienceLevels: number, ci: $CallbackInfo, previousLevel: $LocalIntRef): void;
        getWardenSpawnTracker(): ($WardenSpawnTracker) | undefined;
        getFoodData(): $FoodData;
        canEat(arg0: boolean): boolean;
        isHurt(): boolean;
        mayUseItemAt(arg0: $BlockPos_, arg1: $Direction_, arg2: $ItemStack_): boolean;
        onUpdateAbilities(): void;
        getEnderChestInventory(): $PlayerEnderChestContainer;
        handler$hep000$bettercombat$getEquippedStack_Pre(slot: $EquipmentSlot_, cir: $CallbackInfoReturnable<any>): void;
        setEntityOnShoulder(arg0: $CompoundTag_): boolean;
        handler$jmg000$simplyswords$dropShoulderEntities(ci: $CallbackInfo): void;
        isModelPartShown(arg0: $PlayerModelPart_): boolean;
        setReducedDebugInfo(arg0: boolean): void;
        setMainArm(arg0: $HumanoidArm_): void;
        getCurrentItemAttackStrengthDelay(): number;
        canUseGameMasterBlocks(): boolean;
        handler$elg000$artifacts$eat(level: $Level_, stack: $ItemStack_, properties: $FoodProperties_, cir: $CallbackInfoReturnable<any>): void;
        isScoping(): boolean;
        blockInteractionRange(): number;
        canInteractWithEntity(arg0: $Entity, arg1: number): boolean;
        canInteractWithEntity(arg0: $AABB_, arg1: number): boolean;
        canInteractWithBlock(arg0: $BlockPos_, arg1: number): boolean;
        setIgnoreFallDamageFromCurrentImpulse(arg0: boolean): void;
        isIgnoringFallDamageFromCurrentImpulse(): boolean;
        getSuffixes(): $Collection<$MutableComponent>;
        refreshDisplayName(): void;
        setForcedPose(arg0: $Pose_): void;
        getForcedPose(): $Pose;
        getMainHandIdleAnimation(): string;
        getOffHandIdleAnimation(): string;
        supplementaries$getQuiver(): $ItemStack;
        supplementaries$setQuiver(quiver: $ItemStack_): void;
        addToBeDroppedStacks(list: $Collection_<any>): void;
        bumblezonePlayerTickOffGroundInHeavyAir(): number;
        irons_lib$getArmorBySlotRaw(arg0: $EquipmentSlot_): $ItemStack;
        atl$getBaseClass(): $Class<any>;
        setRotateBodyToHead(rotateBodyToHead: boolean): void;
        isUpdated(frameId: number): number;
        setUpdated(frameId: number): void;
        getLastHeldItems(): $ItemStack[];
        getItemSwapAnimationTimer(): number;
        setItemSwapAnimationTimer(count: number): void;
        getLastAnimationSwapTick(): number;
        setLastAnimationSwapTick(count: number): void;
        setPoseOverwrite(state: $Pose_): void;
        getPoseOverwrite(): $Pose;
        getLastRotations(): number[];
        setLastRotations(lastRotations: number[]): void;
        getSideSword(): $ItemStack;
        setSideSword(sideSword: $ItemStack_): void;
        isRotateBodyToHead(): boolean;
        getAnimationStack(): $AnimationStack;
        playerAnimator_getAnimation(id: $ResourceLocation_): $IAnimation;
        playerAnimator_getAnimation(): $AnimationApplier;
        playerAnimator_setAnimation(id: $ResourceLocation_, animation: $IAnimation): $IAnimation;
        icarus$getStamina(): number;
        icarus$getMaxStamina(): number;
        icarus$modifyStamina(arg0: number): void;
        icarus$setSlowFalling(arg0: boolean): void;
        icarus$isSlowFalling(): boolean;
        icarus$setStamina(arg0: number): void;
        simulated$getCurrentTypewriter(): $BlockPos;
        simulated$setCurrentTypewriter(arg0: $BlockPos_): void;
        simulated$setLaunchedPlunger(arg0: $LaunchedPlungerEntity): void;
        simulated$getLaunchedPlunger(): $LaunchedPlungerEntity;
        simplySwords$invokeDropShoulderEntities(): void;
        sable$getFrozenToSubLevel(): $UUID;
        sable$getFrozenToSubLevelAnchor(): $Vector3dc;
        sable$tickStopFreezing(): void;
        sable$teleport(): void;
        setDirty(): void;
        getWCUUID(): $UUID;
        getSimulation(): $BasicSimulation;
        setSimulation(simulation: $BasicSimulation): void;
        getLastPlayerAnimatorPosition(): $Vector3;
        setLastPlayerAnimatorPosition(lastPlayerAnimatorPosition: $Vector3): void;
        spectrum$setSleepTimer(arg0: number): void;
        getStages(): $Stages;
        getInventory(): $InventoryKJS;
        getCraftingGrid(): $InventoryKJS;
        getData(): $AttachedData<any>;
        getInventoryChangeListener(): $KubeJSInventoryListener;
        static getDataPlayerModeCustomisation$irons_lib_$md$68cb88$0(): $EntityDataAccessor<any>;
        awardStat(arg0: $ResourceLocation_): void;
        awardStat(arg0: $Stat_<never>, arg1: number): void;
        awardStat(arg0: $Stat_<never>): void;
        awardStat(arg0: $ResourceLocation_, arg1: number): void;
        getLuck(): number;
        getDefaultDimensions(arg0: $Pose_): $EntityDimensions;
        bumblezonePlayerInHeavyAir(): boolean;
        isDisableBodyRotation(): boolean;
        setDisableBodyRotation(disableBodyRotation: boolean): void;
        sable$freezeTo(arg0: $UUID_, arg1: $Vector3dc): void;
        addItem(arg0: $ItemStack_): boolean;
        getPrefixes(): $Collection<$MutableComponent>;
        drop(arg0: $ItemStack_, arg1: boolean, arg2: boolean): $ItemEntity;
        drop(arg0: $ItemStack_, arg1: boolean): $ItemEntity;
        getData(holder: $DataHolder<any>, builder: $Supplier_<any>): $Object;
        openMenu(arg0: $MenuProvider, arg1: $BlockPos_): $OptionalInt;
        openMenu(arg0: $MenuProvider, arg1: $Consumer_<$RegistryFriendlyByteBuf>): $OptionalInt;
        mayFly(): boolean;
        isCloseEnough(arg0: $Entity, arg1: number): boolean;
        isFakePlayer(): boolean;
        supplementaries$hasQuiver(): boolean;
        startTracking(): void;
        wrap(): $WeakReference<$Trackable>;
        /**
         * @deprecated
         */
        getAnimation(): $AnimationApplier;
        updateSimulation(partCount: number): void;
        simulate(abstractClientPlayer: $MinecraftPlayer): void;
        incorrectSimulation(sim: $BasicSimulation): boolean;
        createSimulation(): $BasicSimulation;
        getSelectedSlot(): number;
        notify(title: $Component_, text: $Component_): void;
        notify(builder: $NotificationToastData_): void;
        getStats(): $PlayerStatsJS;
        isMiningBlock(): boolean;
        /**
         * Checks if the player is fake.
         */
        isFake(): this is $FakePlayer;
        sendInventoryUpdate(): void;
        give(item: $ItemStack_): void;
        giveInHand(item: $ItemStack_): void;
        setSelectedSlot(index: number): void;
        getMouseItem(): $ItemStack;
        setMouseItem(item: $ItemStack_): void;
        addFood(hunger: number, saturation: number): void;
        getFoodLevel(): number;
        setFoodLevel(foodLevel: number): void;
        getSaturation(): number;
        setSaturation(saturation: number): void;
        addExhaustion(exhaustion: number): void;
        addXP(xp: number): void;
        addXPLevels(levels: number): void;
        setXp(xp: number): void;
        getXp(): number;
        setXpLevel(levels: number): void;
        getXpLevel(): number;
        boostElytraFlight(): void;
        getOpenInventory(): $AbstractContainerMenu;
        addItemCooldown(item: $Item_, ticks: number): void;
        sendData(channel: string, data: $CompoundTag_): void;
        sendData(channel: string): void;
        invokeSetShoulderEntityRight(arg0: $CompoundTag_): void;
        invokeSetShoulderEntityLeft(arg0: $CompoundTag_): void;
        bumblezone$callHurtCurrentlyUsedShield(arg0: number): void;
        setEnchantmentSeed(arg0: number): void;
        callHurtCurrentlyUsedShield(arg0: number): void;
        setSleepCounter(arg0: number): void;
        serializeNBT(arg0: $HolderLookup$Provider): $Player;
        lastHurtByPlayerTime: number;
        static DEFAULT_BASE_GRAVITY: number;
        xRot: number;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        yHeadRot: number;
        yCloakO: number;
        noPhysics: boolean;
        yo: number;
        yBodyRotO: number;
        removalReason: $Entity$RemovalReason;
        zza: number;
        swingingArm: $InteractionHand;
        static CRAFTING_SLOT_OFFSET: number;
        static ID_TAG: string;
        static WAKE_UP_DURATION: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        icarus$flightStamina: number;
        walkDist: number;
        lastHurt: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        static STANDING_DIMENSIONS: $EntityDimensions;
        yya: number;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        static DEFAULT_MODEL_CUSTOMIZATION: number;
        hurtDuration: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        static SWIMMING_BB_HEIGHT: number;
        static DEFAULT_ENTITY_INTERACTION_RANGE: number;
        dead: boolean;
        verticalCollision: boolean;
        verticalCollisionBelow: boolean;
        experienceLevel: number;
        static DEFAULT_BABY_SCALE: number;
        static ATTRIBUTES_FIELD: string;
        static PERSISTED_NBT_TAG: string;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        zCloak: number;
        flyDist: number;
        currentImpulseImpactPos: $Vec3;
        static PASSENGERS_TAG: string;
        xCloakO: number;
        wasOnFire: boolean;
        attackAnim: number;
        zOld: number;
        timeOffs: number;
        wasTouchingWater: boolean;
        activeEffects: $Map<$Holder<$MobEffect>, $MobEffectInstance>;
        rotA: number;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        static ENDER_SLOT_OFFSET: number;
        static ARMOR_SLOT_OFFSET: number;
        static SLEEP_DURATION: number;
        static HELD_ITEM_SLOT: number;
        yCloak: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        xCloak: number;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        lastHurtByPlayer: $Player;
        asbTickCount: number;
        static BOARDING_COOLDOWN: number;
        static MAX_HEALTH: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        static DEFAULT_EYE_HEIGHT: number;
        level: $Level;
        yRot: number;
        static CROUCH_BB_HEIGHT: number;
        moveDist: number;
        enchantmentSeed: number;
        zCloakO: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        bob: number;
        experienceProgress: number;
        create_diesel_generators$turretPos: $BlockPos;
        totalExperience: number;
        xOld: number;
        wasInPowderSnow: boolean;
        containerMenu: $AbstractContainerMenu;
        hurtTime: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        static DEFAULT_MAIN_HAND: $HumanoidArm;
        deathTime: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        jumping: boolean;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static DEFAULT_VEHICLE_ATTACHMENT: $Vec3;
        inventoryMenu: $InventoryMenu;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        lastDamageStamp: number;
        levelCallback: $EntityInLevelCallback;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        fishing: $FishingHook;
        removeArrowTime: number;
        walkDistO: number;
        static SWIMMING_BB_WIDTH: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        yBodyRot: number;
        blocksBuilding: boolean;
        takeXpDelay: number;
        static DEFAULT_BLOCK_INTERACTION_RANGE: number;
        oBob: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        invulnerableDuration: number;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        effectsDirty: boolean;
        currentExplosionCause: $Entity;
        constructor(arg0: $Level_, arg1: $BlockPos_, arg2: number, arg3: $GameProfile);
        get cooldowns(): $ItemCooldowns;
        get abilities(): $Abilities;
        get creative(): boolean;
        get localPlayer(): boolean;
        get gameProfile(): $GameProfile;
        get textFilteringEnabled(): boolean;
        get currentAttack(): $AttackHand;
        get affectedByFluids(): boolean;
        get scoreboard(): $Scoreboard;
        get secondaryUseActive(): boolean;
        get shoulderEntityLeft(): $CompoundTag;
        get shoulderEntityRight(): $CompoundTag;
        get sleepingLongEnough(): boolean;
        get sleepTimer(): number;
        get xpNeededForNextLevel(): number;
        get wardenSpawnTracker(): ($WardenSpawnTracker) | undefined;
        get foodData(): $FoodData;
        get hurt(): boolean;
        get enderChestInventory(): $PlayerEnderChestContainer;
        set entityOnShoulder(value: $CompoundTag_);
        set mainArm(value: $HumanoidArm_);
        get currentItemAttackStrengthDelay(): number;
        get scoping(): boolean;
        set ignoreFallDamageFromCurrentImpulse(value: boolean);
        get ignoringFallDamageFromCurrentImpulse(): boolean;
        get suffixes(): $Collection<$MutableComponent>;
        get mainHandIdleAnimation(): string;
        get offHandIdleAnimation(): string;
        get lastHeldItems(): $ItemStack[];
        get animationStack(): $AnimationStack;
        get WCUUID(): $UUID;
        get stages(): $Stages;
        get inventory(): $InventoryKJS;
        get craftingGrid(): $InventoryKJS;
        get inventoryChangeListener(): $KubeJSInventoryListener;
        static get dataPlayerModeCustomisation$irons_lib_$md$68cb88$0(): $EntityDataAccessor<any>;
        get luck(): number;
        get prefixes(): $Collection<$MutableComponent>;
        get fakePlayer(): boolean;
        get animation(): $AnimationApplier;
        get stats(): $PlayerStatsJS;
        get miningBlock(): boolean;
        get fake(): boolean;
        get openInventory(): $AbstractContainerMenu;
        set sleepCounter(value: number);
    }
}
