import { $ItemStack } from "@package/net/minecraft/world/item";
import { $Avatar } from "@package/org/figuramc/figura/avatar";
import { $FiguraTexture } from "@package/org/figuramc/figura/model/rendering/texture";
import { $FiguraVec3 } from "@package/org/figuramc/figura/math/vector";
import { $Object } from "@package/java/lang";
import { $LuaFunction } from "@package/org/luaj/vm2";

declare module "@package/org/figuramc/figura/lua/api/action_wheel" {
    export class $ActionWheelAPI {
        getPage(pageTitle: string): $Object;
        mouseScroll(avatar: $Avatar, delta: number): boolean;
        __index(arg: string): $Object;
        __newindex(key: string, value: $Object): void;
        setPage(page: $Object): $ActionWheelAPI;
        getSelected(): number;
        getSelectedAction(): $Action;
        getCurrentPage(): $Page;
        newPage(title: string): $Page;
        newAction(): $Action;
        isEnabled(): boolean;
        execute(index: number, right: boolean): $ActionWheelAPI;
        execute(avatar: $Avatar, left: boolean): boolean;
        rightClick: $LuaFunction;
        leftClick: $LuaFunction;
        scroll: $LuaFunction;
        currentPage: $Page;
        constructor(owner: $Avatar);
        get selected(): number;
        get selectedAction(): $Action;
        get enabled(): boolean;
    }
    export class $Page {
        __index(arg: string): $Object;
        __newindex(key: string, value: boolean): void;
        getGroupCount(): number;
        getSlotsShift(): number;
        getGreatestSlot(): number;
        setSlotsShift(shift: number): $Page;
        slotsShift(shift: number): $Page;
        shouldKeepSlots(): boolean;
        setKeepSlots(bool: boolean): $Page;
        setAction(index: number, action: $Action): $Page;
        getSize(): number;
        slots(shift: number): $Action[];
        slots(): $Action[];
        newAction(index: number): $Action;
        getTitle(): string;
        getAction(index: number): $Action;
        getActions(shift: number): $Object;
        action(index: number, action: $Action): $Page;
        keepSlots: boolean;
        constructor(title: string);
        get groupCount(): number;
        get greatestSlot(): number;
        get size(): number;
        get title(): string;
    }
    export class $Action {
        onScroll(_function: $LuaFunction): $Action;
        setTitle(title: string): $Action;
        getColor(selected: boolean): $FiguraVec3;
        getColor(): $FiguraVec3;
        onLeftClick(_function: $LuaFunction): $Action;
        setTexture(texture: $FiguraTexture, u: number, v: number, width: number, height: number, scale: number): $Action;
        mouseScroll(avatar: $Avatar, delta: number): void;
        __index(arg: string): $Object;
        __newindex(key: string, value: $Object): void;
        hoverTexture(texture: $FiguraTexture, u: number, v: number, width: number, height: number, scale: number): $Action;
        texture(texture: $FiguraTexture, u: number, v: number, width: number, height: number, scale: number): $Action;
        setItem(item: $Object): $Action;
        toggleTitle(title: string): $Action;
        hoverItem(item: $Object): $Action;
        toggleItem(item: $Object): $Action;
        toggleColor(x: $Object, y: number, z: number): $Action;
        toggleTexture(texture: $FiguraTexture, u: number, v: number, width: number, height: number, scale: number): $Action;
        getHoverColor(): $FiguraVec3;
        setHoverColor(x: $Object, y: number, z: number): $Action;
        setHoverItem(item: $Object): $Action;
        setHoverTexture(texture: $FiguraTexture, u: number, v: number, width: number, height: number, scale: number): $Action;
        setOnLeftClick(_function: $LuaFunction): $Action;
        setOnRightClick(_function: $LuaFunction): $Action;
        setOnToggle(_function: $LuaFunction): $Action;
        setOnUntoggle(_function: $LuaFunction): $Action;
        onUntoggle(_function: $LuaFunction): $Action;
        setOnScroll(_function: $LuaFunction): $Action;
        getToggleTitle(): string;
        setToggleTitle(title: string): $Action;
        getToggleColor(): $FiguraVec3;
        setToggleColor(x: $Object, y: number, z: number): $Action;
        setToggleItem(item: $Object): $Action;
        setToggleTexture(texture: $FiguraTexture, u: number, v: number, width: number, height: number, scale: number): $Action;
        setColor(x: $Object, y: number, z: number): $Action;
        getItem(selected: boolean): $ItemStack;
        toggled(bool: boolean): $Action;
        setToggled(bool: boolean): $Action;
        onRightClick(_function: $LuaFunction): $Action;
        hoverColor(x: $Object, y: number, z: number): $Action;
        onToggle(_function: $LuaFunction): $Action;
        isToggled(): boolean;
        color(x: $Object, y: number, z: number): $Action;
        item(item: $Object): $Action;
        title(title: string): $Action;
        getTitle(): string;
        getTexture(selected: boolean): $Action$TextureData;
        execute(avatar: $Avatar, left: boolean): void;
        rightClick: $LuaFunction;
        static TOGGLE_COLOR: $FiguraVec3;
        leftClick: $LuaFunction;
        untoggle: $LuaFunction;
        scroll: $LuaFunction;
        toggle: $LuaFunction;
        static HOVER_COLOR: $FiguraVec3;
        constructor();
    }
}
