import { $LivingEntityRenderer } from "@package/net/minecraft/client/renderer/entity";
import { $ModelPart } from "@package/net/minecraft/client/model/geom";
import { $Avatar } from "@package/org/figuramc/figura/avatar";
import { $List, $Map_, $Map, $List_ } from "@package/java/util";
import { $SpriteTask, $BlockTask, $TextTask, $RenderTask, $ItemTask, $EntityTask } from "@package/org/figuramc/figura/model/rendertasks";
import { $ImmediateAvatarRenderer, $Vertex } from "@package/org/figuramc/figura/model/rendering";
import { $FiguraMat3, $FiguraMat4 } from "@package/org/figuramc/figura/math/matrix";
import { $EntityModel } from "@package/net/minecraft/client/model";
import { $Function } from "@package/java/util/function";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $RenderTypes, $FiguraTexture, $FiguraTextureSet$OverrideType, $FiguraTextureSet, $RenderTypes_ } from "@package/org/figuramc/figura/model/rendering/texture";
import { $FiguraVec2, $FiguraVec3 } from "@package/org/figuramc/figura/math/vector";
import { $Enum, $Comparable, $Object } from "@package/java/lang";
import { $LuaFunction, $Varargs } from "@package/org/luaj/vm2";
export * as rendertasks from "@package/org/figuramc/figura/model/rendertasks";
export * as rendering from "@package/org/figuramc/figura/model/rendering";

declare module "@package/org/figuramc/figura/model" {
    export class $VanillaModelProvider extends $Enum<$VanillaModelProvider> {
        static values(): $VanillaModelProvider[];
        static valueOf(name: string): $VanillaModelProvider;
        static HEAD: $VanillaModelProvider;
        static LEFT_ARM: $VanillaModelProvider;
        static RIGHT_ELYTRON: $VanillaModelProvider;
        static LEFT_SLEEVE: $VanillaModelProvider;
        static CAPE: $VanillaModelProvider;
        static RIGHT_LEG: $VanillaModelProvider;
        static LEFT_LEG: $VanillaModelProvider;
        static LEFT_ELYTRON: $VanillaModelProvider;
        static FAKE_CAPE: $VanillaModelProvider;
        static JACKET: $VanillaModelProvider;
        static RIGHT_SLEEVE: $VanillaModelProvider;
        func: $Function<$EntityModel<never>, $ModelPart>;
        static RIGHT_PANTS: $VanillaModelProvider;
        static HAT: $VanillaModelProvider;
        static LEFT_PANTS: $VanillaModelProvider;
        static BODY: $VanillaModelProvider;
        static RIGHT_ARM: $VanillaModelProvider;
    }
    /**
     * Values that may be interpreted as {@link $VanillaModelProvider}.
     */
    export type $VanillaModelProvider_ = "head" | "body" | "left_arm" | "right_arm" | "left_leg" | "right_leg" | "hat" | "jacket" | "left_sleeve" | "right_sleeve" | "left_pants" | "right_pants" | "cape" | "fake_cape" | "left_elytron" | "right_elytron";
    export class $VanillaModelData$PartData {
        visible: boolean;
        pos: $FiguraVec3;
        rot: $FiguraVec3;
        scale: $FiguraVec3;
        constructor();
    }
    export class $PartCustomization$PartCustomizationStack {
        push(customization: $PartCustomization): void;
        pop(): void;
        peek(): $PartCustomization;
        isEmpty(): boolean;
        constructor();
        get empty(): boolean;
    }
    export class $ParentType extends $Enum<$ParentType> {
        static get(name: string): $ParentType;
        static values(): $ParentType[];
        static valueOf(name: string): $ParentType;
        static RightArm: $ParentType;
        static LeftBootPivot: $ParentType;
        static RightShoulderPivot: $ParentType;
        static RightSpyglassPivot: $ParentType;
        static RightBootPivot: $ParentType;
        aliases: string[];
        static LeftSpyglassPivot: $ParentType;
        static LeftShoulderPivot: $ParentType;
        static World: $ParentType;
        isRenderLayer: boolean;
        static LeggingsPivot: $ParentType;
        static Item: $ParentType;
        static RightElytra: $ParentType;
        static ChestplatePivot: $ParentType;
        static LeftItemPivot: $ParentType;
        provider: $VanillaModelProvider;
        static Hud: $ParentType;
        static LeftElytraPivot: $ParentType;
        static Trident: $ParentType;
        static RightLeggingPivot: $ParentType;
        static Camera: $ParentType;
        static Body: $ParentType;
        static HelmetPivot: $ParentType;
        static Arrow: $ParentType;
        static LeftLeg: $ParentType;
        static Head: $ParentType;
        static LeftParrotPivot: $ParentType;
        offset: $FiguraVec3;
        static RightElytraPivot: $ParentType;
        static RightParrotPivot: $ParentType;
        static Portrait: $ParentType;
        static Cape: $ParentType;
        static LeftLeggingPivot: $ParentType;
        isSeparate: boolean;
        static LeftArm: $ParentType;
        static RightLeg: $ParentType;
        static LeftElytra: $ParentType;
        static Skull: $ParentType;
        isPivot: boolean;
        static None: $ParentType;
        static HelmetItemPivot: $ParentType;
        static RightItemPivot: $ParentType;
    }
    /**
     * Values that may be interpreted as {@link $ParentType}.
     */
    export type $ParentType_ = "none" | "head" | "body" | "leftarm" | "rightarm" | "leftleggingpivot" | "rightleggingpivot" | "leftleg" | "rightleg" | "leftelytrapivot" | "rightelytrapivot" | "leftelytra" | "rightelytra" | "cape" | "world" | "hud" | "camera" | "skull" | "portrait" | "arrow" | "trident" | "item" | "leftitempivot" | "rightitempivot" | "leftspyglasspivot" | "rightspyglasspivot" | "leftparrotpivot" | "rightparrotpivot" | "helmetitempivot" | "helmetpivot" | "chestplatepivot" | "leftshoulderpivot" | "rightshoulderpivot" | "leggingspivot" | "leftbootpivot" | "rightbootpivot";
    export class $VanillaModelData {
        update(parent: $ParentType_, part: $ModelPart): void;
        update(parent: $ParentType_, model: $EntityModel<never>): void;
        update(entityRenderer: $LivingEntityRenderer<never, never>): void;
        partMap: $Map<$ParentType, $VanillaModelData$PartData>;
        constructor();
    }
    export class $FiguraModelPart implements $Comparable<$FiguraModelPart> {
        getVisible(): boolean;
        setVisible(bool: boolean): $FiguraModelPart;
        addTask(renderTask: $RenderTask): $RenderTask;
        setOverlay(whiteOverlay: $Object, hurtOverlay: number): $FiguraModelPart;
        matrix(matrix: $FiguraMat4): $FiguraModelPart;
        setLight(light: $Object, skyLight: number): $FiguraModelPart;
        getVertices(textureID: string): $List<$Vertex>;
        getOverlay(): $FiguraVec2;
        getColor(): $FiguraVec3;
        light(light: $Object, skyLight: number): $FiguraModelPart;
        getScale(): $FiguraVec3;
        rot(x: $Object, y: number, z: number): $FiguraModelPart;
        setPos(x: $Object, y: number, z: number): $FiguraModelPart;
        newItem(name: string): $ItemTask;
        setRot(x: $Object, y: number, z: number): $FiguraModelPart;
        moveTo(part: $FiguraModelPart): $FiguraModelPart;
        newEntity(name: string): $EntityTask;
        getPos(): $FiguraVec3;
        setOpacity(opacity: number): $FiguraModelPart;
        getTextures(): $List<$FiguraTexture>;
        __index(key: string): $Object;
        __newindex(key: string, value: $LuaFunction): void;
        getNormalMatrix(): $FiguraMat3;
        setPrimaryRenderType(type: string): $FiguraModelPart;
        setSecondaryRenderType(type: string): $FiguraModelPart;
        primaryTexture(type: string, x: $Object): $FiguraModelPart;
        secondaryTexture(type: string, x: $Object): $FiguraModelPart;
        applyVanillaTransforms(vanillaModelData: $VanillaModelData): void;
        applyExtraTransforms(currentTransforms: $PartCustomization): void;
        resetVanillaTransforms(): void;
        pushVerticesImmediate(avatarRenderer: $ImmediateAvatarRenderer, remainingComplexity: number[]): boolean;
        getOffsetPivot(): $FiguraVec3;
        getPositionMatrix(): $FiguraMat4;
        getPrimaryRenderType(): string;
        getSecondaryRenderType(): string;
        uvMatrix(matrix: $FiguraMat3): $FiguraModelPart;
        getTruePos(): $FiguraVec3;
        uv(x: $Object, y: number): $FiguraModelPart;
        primaryColor(r: $Object, g: number, b: number): $FiguraModelPart;
        secondaryColor(r: $Object, g: number, b: number): $FiguraModelPart;
        getLight(): $FiguraVec2;
        getSecondaryColor(): $FiguraVec3;
        getPrimaryColor(): $FiguraVec3;
        offsetScale(x: $Object, y: number, z: number): $FiguraModelPart;
        getTask(name: string): $Object;
        removeChild(part: $FiguraModelPart): $FiguraModelPart;
        overrideVanillaScale(): boolean;
        overrideVanillaPos(): boolean;
        overrideVanillaRot(): boolean;
        offsetPivot(x: $Object, y: number, z: number): $FiguraModelPart;
        animPosition(vec: $FiguraVec3, merge: boolean): void;
        getAnimPos(): $FiguraVec3;
        animRotation(vec: $FiguraVec3, merge: boolean): void;
        getAnimRot(): $FiguraVec3;
        globalAnimRot(vec: $FiguraVec3, merge: boolean): void;
        animScale(vec: $FiguraVec3, merge: boolean): void;
        getAnimScale(): $FiguraVec3;
        setPreRender(_function: $LuaFunction): $FiguraModelPart;
        setMidRender(_function: $LuaFunction): $FiguraModelPart;
        setPostRender(_function: $LuaFunction): $FiguraModelPart;
        getTrueRot(): $FiguraVec3;
        getTrueScale(): $FiguraVec3;
        setPivot(x: $Object, y: number, z: number): $FiguraModelPart;
        setOffsetPivot(x: $Object, y: number, z: number): $FiguraModelPart;
        getTruePivot(): $FiguraVec3;
        getPositionMatrixRaw(): $FiguraMat4;
        getNormalMatrixRaw(): $FiguraMat3;
        primaryRenderType(type: string): $FiguraModelPart;
        secondaryRenderType(type: string): $FiguraModelPart;
        getPrimaryTexture(): $Varargs;
        getSecondaryTexture(): $Object;
        getPrimaryDefinedTextures(value: number): $Object;
        getSecondaryDefinedTextures(value: number): $Object;
        setPrimaryTexture(type: string, x: $Object): $FiguraModelPart;
        setSecondaryTexture(type: string, x: $Object): $FiguraModelPart;
        partToWorldMatrix(): $FiguraMat4;
        getTextureSize(): $FiguraVec2;
        setUVPixels(x: $Object, y: number): $FiguraModelPart;
        uvPixels(x: $Object, y: number): $FiguraModelPart;
        getUVPixels(): $FiguraVec2;
        setUVMatrix(matrix: $FiguraMat3): $FiguraModelPart;
        getUVMatrix(): $FiguraMat3;
        setParentType(parent: string): $FiguraModelPart;
        getParentType(): string;
        getAllVertices(): $Map<string, $List<$Vertex>>;
        setColor(r: $Object, g: number, b: number): $FiguraModelPart;
        addChild(part: $FiguraModelPart): $FiguraModelPart;
        pivot(x: $Object, y: number, z: number): $FiguraModelPart;
        getChildren(): $Map<number, $FiguraModelPart>;
        visible(bool: boolean): $FiguraModelPart;
        setScale(x: $Object, y: number, z: number): $FiguraModelPart;
        newText(name: string): $TextTask;
        setMatrix(matrix: $FiguraMat4): $FiguraModelPart;
        getRot(): $FiguraVec3;
        offsetRot(x: $Object, y: number, z: number): $FiguraModelPart;
        getOffsetRot(): $FiguraVec3;
        setOffsetRot(x: $Object, y: number, z: number): $FiguraModelPart;
        getOffsetScale(): $FiguraVec3;
        setOffsetScale(x: $Object, y: number, z: number): $FiguraModelPart;
        setUV(x: $Object, y: number): $FiguraModelPart;
        getOpacity(): number;
        newPart(name: string, parentType: string): $FiguraModelPart;
        setPrimaryColor(r: $Object, g: number, b: number): $FiguraModelPart;
        setSecondaryColor(r: $Object, g: number, b: number): $FiguraModelPart;
        getPivot(): $FiguraVec3;
        isChildOf(part: $FiguraModelPart): boolean;
        newSprite(name: string): $SpriteTask;
        removeTask(x: $Object): $FiguraModelPart;
        getUV(): $FiguraVec2;
        color(r: $Object, g: number, b: number): $FiguraModelPart;
        pos(x: $Object, y: number, z: number): $FiguraModelPart;
        parentType(parent: string): $FiguraModelPart;
        opacity(opacity: number): $FiguraModelPart;
        overlay(whiteOverlay: $Object, hurtOverlay: number): $FiguraModelPart;
        newBlock(name: string): $BlockTask;
        getName(): string;
        remove(): $FiguraModelPart;
        compareTo(o: $FiguraModelPart): number;
        scale(x: $Object, y: number, z: number): $FiguraModelPart;
        getParent(): $FiguraModelPart;
        getType(): string;
        copy(name: string): $FiguraModelPart;
        parent: $FiguraModelPart;
        renderTasks: $Map<string, $RenderTask>;
        postRender: $LuaFunction;
        midRender: $LuaFunction;
        textures: $List<$FiguraTextureSet>;
        customization: $PartCustomization;
        vertices: $Map<number, $List<$Vertex>>;
        preRender: $LuaFunction;
        textureWidth: number;
        savedCustomization: $PartCustomization;
        animationOverride: number;
        textureHeight: number;
        children: $List<$FiguraModelPart>;
        facesByTexture: $List<number>;
        name: string;
        animated: boolean;
        savedPartToWorldMat: $FiguraMat4;
        lastAnimationPriority: number;
        playerCustomization: $PartCustomization;
        constructor(owner: $Avatar, name: string, customization: $PartCustomization, vertices: $Map_<number, $List_<$Vertex>>, children: $List_<$FiguraModelPart>);
        get normalMatrix(): $FiguraMat3;
        get positionMatrix(): $FiguraMat4;
        get truePos(): $FiguraVec3;
        get animPos(): $FiguraVec3;
        get animRot(): $FiguraVec3;
        get trueRot(): $FiguraVec3;
        get trueScale(): $FiguraVec3;
        get truePivot(): $FiguraVec3;
        get positionMatrixRaw(): $FiguraMat4;
        get normalMatrixRaw(): $FiguraMat3;
        get textureSize(): $FiguraVec2;
        get allVertices(): $Map<string, $List<$Vertex>>;
        get type(): string;
    }
    export class $TextureCustomization {
        getOverrideType(): $FiguraTextureSet$OverrideType;
        getTexture(avatar: $Avatar, textureSet: $FiguraTextureSet): $FiguraTexture;
        getValue(): $Object;
        constructor(first: $FiguraTextureSet$OverrideType, second: $Object);
        get overrideType(): $FiguraTextureSet$OverrideType;
        get value(): $Object;
    }
    export class $PartCustomization$PartType extends $Enum<$PartCustomization$PartType> {
        static values(): $PartCustomization$PartType[];
        static valueOf(name: string): $PartCustomization$PartType;
        static GROUP: $PartCustomization$PartType;
        static MESH: $PartCustomization$PartType;
        static CUBE: $PartCustomization$PartType;
    }
    /**
     * Values that may be interpreted as {@link $PartCustomization$PartType}.
     */
    export type $PartCustomization$PartType_ = "mesh" | "cube" | "group";
    export class $PartCustomization {
        getScale(): $FiguraVec3;
        setPos(pos: $FiguraVec3): void;
        setPos(x: number, y: number, z: number): void;
        setRot(x: number, y: number, z: number): void;
        setRot(rot: $FiguraVec3): void;
        getPos(): $FiguraVec3;
        getNormalMatrix(): $FiguraMat3;
        setPrimaryRenderType(type: $RenderTypes_): void;
        setSecondaryRenderType(type: $RenderTypes_): void;
        getOffsetPivot(): $FiguraVec3;
        getPositionMatrix(): $FiguraMat4;
        getPrimaryRenderType(): $RenderTypes;
        getSecondaryRenderType(): $RenderTypes;
        offsetPos(pos: $FiguraVec3): void;
        offsetPos(x: number, y: number, z: number): void;
        offsetScale(scale: $FiguraVec3): void;
        offsetScale(x: number, y: number, z: number): void;
        addOffsetPivot(x: number, y: number, z: number): void;
        addOffsetPivot(pivot: $FiguraVec3): void;
        addOffsetPos(pos: $FiguraVec3): void;
        addOffsetPos(x: number, y: number, z: number): void;
        addOffsetRot(x: number, y: number, z: number): void;
        addOffsetRot(rot: $FiguraVec3): void;
        offsetPivot(x: number, y: number, z: number): void;
        offsetPivot(pivot: $FiguraVec3): void;
        getOffsetPos(): $FiguraVec3;
        getAnimPos(): $FiguraVec3;
        setAnimPos(x: number, y: number, z: number): void;
        getAnimRot(): $FiguraVec3;
        setAnimRot(x: number, y: number, z: number): void;
        getAnimScale(): $FiguraVec3;
        setAnimScale(x: number, y: number, z: number): void;
        setPivot(x: number, y: number, z: number): void;
        setPivot(pivot: $FiguraVec3): void;
        applyToStack(stack: $PoseStack): void;
        addOffsetScale(x: number, y: number, z: number): void;
        addOffsetScale(scale: $FiguraVec3): void;
        setScale(x: number, y: number, z: number): void;
        setScale(scale: $FiguraVec3): void;
        copyTo(target: $PartCustomization): void;
        setMatrix(matrix: $FiguraMat4): void;
        getRot(): $FiguraVec3;
        offsetRot(x: number, y: number, z: number): void;
        offsetRot(rot: $FiguraVec3): void;
        getOffsetRot(): $FiguraVec3;
        getOffsetScale(): $FiguraVec3;
        recalculate(): void;
        setPositionMatrix(matrix: $FiguraMat4): void;
        setNormalMatrix(matrix: $FiguraMat3): void;
        copyIntoGlobalPoseStack(): $PoseStack;
        getPivot(): $FiguraVec3;
        modify(other: $PartCustomization): void;
        visible: boolean;
        color: $FiguraVec3;
        overlay: number;
        positionMatrix: $FiguraMat4;
        needsMatrixRecalculation: boolean;
        vanillaVisible: boolean;
        secondaryTexture: $TextureCustomization;
        color2: $FiguraVec3;
        normalMatrix: $FiguraMat3;
        stackScale: $FiguraVec3;
        light: number;
        primaryTexture: $TextureCustomization;
        alpha: number;
        uvMatrix: $FiguraMat3;
        partType: $PartCustomization$PartType;
        static GLOBAL_CUSTOMIZATION_POSE_STACK: $PoseStack;
        constructor();
        set matrix(value: $FiguraMat4);
    }
}
