import { $Codec } from "@package/com/mojang/serialization";
import { $IVertexOperation } from "@package/codechicken/lib/render/pipeline";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $LivingEntity, $Entity } from "@package/net/minecraft/world/entity";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $VoxelShape } from "@package/net/minecraft/world/phys/shapes";
import { $List_ } from "@package/java/util";
import { $DoubleBuffer, $IntBuffer, $FloatBuffer } from "@package/java/nio";
import { $CCRenderState } from "@package/codechicken/lib/render";
import { $BlockPos, $BlockPos_, $Direction_, $Vec3i } from "@package/net/minecraft/core";
import { $Copyable } from "@package/codechicken/lib/util";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $ByteBuf } from "@package/io/netty/buffer";
import { $Vec3_, $AABB_, $Vec3, $AABB } from "@package/net/minecraft/world/phys";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $StreamCodec } from "@package/net/minecraft/network/codec";
import { $Vector4f, $Matrix4f, $Quaterniond, $Quaternionf, $Vector3f } from "@package/org/joml";

declare module "@package/codechicken/lib/vec" {
    export class $ITransformation<Vector, Transformation extends $ITransformation<Vector, Transformation>> implements $Copyable<Transformation> {
        $plus$plus(arg0: Transformation): Transformation;
        isRedundant(): boolean;
        at(arg0: Vector): Transformation;
        inverse(): Transformation;
        apply(arg0: Vector): void;
        merge(arg0: Transformation): Transformation;
        with(arg0: Transformation): Transformation;
        constructor();
        get redundant(): boolean;
    }
    export class $Cuboid6 implements $Copyable<$Cuboid6> {
        aabb(): $AABB;
        volume(): number;
        writeToNBT(arg0: $CompoundTag_): $CompoundTag;
        subtract(arg0: number): $Cuboid6;
        subtract(arg0: number, arg1: number, arg2: number): $Cuboid6;
        subtract(arg0: $Vec3_): $Cuboid6;
        subtract(arg0: $BlockPos_): $Cuboid6;
        subtract(arg0: $Vec3i): $Cuboid6;
        subtract(arg0: $Vector3): $Cuboid6;
        shape(): $VoxelShape;
        intersects(arg0: $Cuboid6): boolean;
        expandSide(arg0: $Direction_, arg1: number): $Cuboid6;
        enclose(arg0: $Cuboid6): $Cuboid6;
        enclose(arg0: number, arg1: number, arg2: number): $Cuboid6;
        enclose(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): $Cuboid6;
        enclose(arg0: $Vector3): $Cuboid6;
        equalsT(arg0: $Cuboid6): boolean;
        shrinkSide(arg0: $Direction_, arg1: number): $Cuboid6;
        getSideSize(arg0: $Direction_): number;
        center(): $Vector3;
        getSide(arg0: $Direction_): number;
        getSide(arg0: number): number;
        setSide(arg0: $Direction_, arg1: number): $Cuboid6;
        setSide(arg0: number, arg1: number): $Cuboid6;
        expand(arg0: $Vector3): $Cuboid6;
        expand(arg0: number, arg1: number, arg2: number): $Cuboid6;
        expand(arg0: number): $Cuboid6;
        add(arg0: number): $Cuboid6;
        add(arg0: number, arg1: number, arg2: number): $Cuboid6;
        add(arg0: $BlockPos_): $Cuboid6;
        add(arg0: $Vector3): $Cuboid6;
        add(arg0: $Vec3i): $Cuboid6;
        apply(arg0: $Transformation): $Cuboid6;
        offset(arg0: $Cuboid6): $Cuboid6;
        contains(arg0: number, arg1: number, arg2: number): boolean;
        contains(arg0: $Vector3): boolean;
        set(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): $Cuboid6;
        set(arg0: $AABB_): $Cuboid6;
        set(arg0: $Vec3i, arg1: $Vec3i): $Cuboid6;
        set(arg0: $Vector3, arg1: $Vector3): $Cuboid6;
        set(arg0: $Cuboid6): $Cuboid6;
        copy(): $Cuboid6;
        min: $Vector3;
        max: $Vector3;
        static full: $Cuboid6;
        constructor(arg0: $AABB_);
        constructor(arg0: $Vec3i, arg1: $Vec3i);
        constructor(arg0: $Vector3, arg1: $Vector3);
        constructor();
        constructor(arg0: $CompoundTag_);
        constructor(arg0: $Cuboid6);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number);
    }
    export class $Rotation extends $Transformation {
        static rotationTo(arg0: number, arg1: number): number;
        static rotateSide(arg0: number, arg1: number): number;
        toQuat(): $Quat;
        static getSidedRotation(arg0: $Player, arg1: number): number;
        static sideOrientation(arg0: number, arg1: number): $Transformation;
        static getSideFromLookAngle(arg0: $LivingEntity): number;
        apply(arg0: $Vector3): void;
        merge(arg0: $Transformation): $Transformation;
        static sideRotMap: number[];
        static rotSideMap: number[];
        static sideRotOffsets: number[];
        static operationIndex: number;
        static axes: $Vector3[];
        angle: number;
        static quarterRotations: $Transformation[];
        axis: $Vector3;
        static sideRotations: $Transformation[];
        constructor(arg0: $Quat);
        constructor(arg0: number, arg1: $Vector3);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: $Rotation);
    }
    export class $TransformationList extends $Transformation {
        reverseCompile(): $Matrix4;
        prepend(arg0: $Transformation): $TransformationList;
        compile(): $Matrix4;
        apply(arg0: $Vector3): void;
        copy(): $TransformationList;
        static operationIndex: number;
        constructor(...arg0: $Transformation[]);
        constructor(arg0: $List_<$Transformation>);
        constructor(arg0: $TransformationList);
    }
    export class $Vector3 implements $Copyable<$Vector3> {
        distanceSquared(arg0: $Vector3): number;
        vector3f(): $Vector3f;
        vec3(): $Vec3;
        angle(arg0: $Vector3): number;
        project(arg0: $Vector3): $Vector3;
        static fromBlockPos(arg0: $BlockPos_): $Vector3;
        perpendicular(): $Vector3;
        writeToNBT(arg0: $CompoundTag_): $CompoundTag;
        static fromNBT(arg0: $CompoundTag_): $Vector3;
        static fromArray(arg0: number[]): $Vector3;
        static fromArray(arg0: number[]): $Vector3;
        subtract(arg0: $Vec3i): $Vector3;
        subtract(arg0: $Vector3): $Vector3;
        subtract(arg0: $Vec3_): $Vector3;
        subtract(arg0: number): $Vector3;
        subtract(arg0: number, arg1: number, arg2: number): $Vector3;
        divide(arg0: $Vec3i): $Vector3;
        divide(arg0: number): $Vector3;
        divide(arg0: number, arg1: number, arg2: number): $Vector3;
        divide(arg0: $Vector3): $Vector3;
        isZero(): boolean;
        negate(): $Vector3;
        vector4f(): $Vector4f;
        equalsT(arg0: $Vector3): boolean;
        static fromVec3i(arg0: $Vec3i): $Vector3;
        static fromTile(arg0: $BlockEntity): $Vector3;
        zCrossProduct(): $Vector3;
        xCrossProduct(): $Vector3;
        magSquared(): number;
        static fromBlockPosCenter(arg0: $BlockPos_): $Vector3;
        static fromEntity(arg0: $Entity): $Vector3;
        static fromEntityCenter(arg0: $Entity): $Vector3;
        static fromTileCenter(arg0: $BlockEntity): $Vector3;
        static fromAxes(arg0: number[]): $Vector3;
        static fromAxes(arg0: number[]): $Vector3;
        toArrayD(): number[];
        toArrayF(): number[];
        yCrossProduct(): $Vector3;
        scalarProject(arg0: $Vector3): number;
        YZintercept(arg0: $Vector3, arg1: number): $Vector3;
        XZintercept(arg0: $Vector3, arg1: number): $Vector3;
        XYintercept(arg0: $Vector3, arg1: number): $Vector3;
        isAxial(): boolean;
        $tilde(): $Vector3;
        unary_$tilde(): $Vector3;
        $plus(arg0: $Vector3): $Vector3;
        $minus(arg0: $Vector3): $Vector3;
        $times(arg0: number): $Vector3;
        $times(arg0: $Vector3): $Vector3;
        $div(arg0: number): $Vector3;
        $dot$times(arg0: $Vector3): number;
        crossProduct(arg0: $Vector3): $Vector3;
        dotProduct(arg0: $Vector3): number;
        dotProduct(arg0: number, arg1: number, arg2: number): number;
        pos(): $BlockPos;
        mag(): number;
        distance(arg0: $Vector3): number;
        multiply(arg0: number, arg1: number, arg2: number): $Vector3;
        multiply(arg0: number): $Vector3;
        multiply(arg0: $Vector3): $Vector3;
        rotate(arg0: $Quat): $Vector3;
        rotate(arg0: number, arg1: $Vector3): $Vector3;
        normalize(): $Vector3;
        translation(): $Translation;
        getSide(arg0: number): number;
        setSide(arg0: number, arg1: number): $Vector3;
        floor(): $Vector3;
        ceil(): $Vector3;
        add(arg0: number, arg1: number, arg2: number): $Vector3;
        add(arg0: $Vector3): $Vector3;
        add(arg0: $Vec3_): $Vector3;
        add(arg0: $Vec3i): $Vector3;
        add(arg0: number): $Vector3;
        apply(arg0: $Transformation): $Vector3;
        set(arg0: $Vec3i): $Vector3;
        set(arg0: number[]): $Vector3;
        set(arg0: number): $Vector3;
        set(arg0: number, arg1: number, arg2: number): $Vector3;
        set(arg0: $Vector3): $Vector3;
        set(arg0: number[]): $Vector3;
        copy(): $Vector3;
        static ZERO: $Vector3;
        static CODEC: $Codec<$Vector3>;
        static ONE: $Vector3;
        static X_POS: $Vector3;
        static Z_NEG: $Vector3;
        static X_NEG: $Vector3;
        static STREAM_CODEC: $StreamCodec<$ByteBuf, $Vector3>;
        static Z_POS: $Vector3;
        static CENTER: $Vector3;
        static Y_NEG: $Vector3;
        x: number;
        y: number;
        z: number;
        static Y_POS: $Vector3;
        constructor(arg0: $Vector3);
        constructor(arg0: number, arg1: number, arg2: number);
        constructor();
        constructor(arg0: number[]);
        constructor(arg0: number[]);
        constructor(arg0: $Vec3_);
        get zero(): boolean;
        get axial(): boolean;
    }
    export class $Matrix4 extends $Transformation {
        translate(arg0: $Vector3): $Matrix4;
        translate(arg0: $Vec3i): $Matrix4;
        translate(arg0: number, arg1: number, arg2: number): $Matrix4;
        toMatrix4f(): $Matrix4f;
        setIdentity(): $Matrix4;
        multMatrix(arg0: $Vector4f): void;
        toFloatBuffer(): $FloatBuffer;
        toDoubleBuffer(): $DoubleBuffer;
        static gluProject(arg0: $Vector3, arg1: $Matrix4, arg2: $Matrix4, arg3: $IntBuffer): $Vector3;
        transpose(): $Matrix4;
        toArrayD(): number[];
        toArrayF(): number[];
        leftMultiply(arg0: $Matrix4): $Matrix4;
        multiply(arg0: $Matrix4): $Matrix4;
        rotate(arg0: number, arg1: $Vector3): $Matrix4;
        rotate(arg0: $Rotation): $Matrix4;
        scale(arg0: number): $Matrix4;
        scale(arg0: number, arg1: number, arg2: number): $Matrix4;
        scale(arg0: $Vector3): $Matrix4;
        apply(arg0: $Transformation): $Matrix4;
        apply(arg0: $Vector3): void;
        set(arg0: $Matrix4f): $Matrix4;
        set(arg0: $PoseStack): $Matrix4;
        set(arg0: number[]): $Matrix4;
        set(arg0: $FloatBuffer): $Matrix4;
        set(arg0: number[]): $Matrix4;
        set(arg0: $Matrix4): $Matrix4;
        set(arg0: $DoubleBuffer): $Matrix4;
        save(arg0: $FloatBuffer): void;
        save(arg0: $DoubleBuffer): void;
        copy(): $Matrix4;
        m20: number;
        m31: number;
        m30: number;
        m00: number;
        m11: number;
        m22: number;
        m33: number;
        m10: number;
        m21: number;
        m32: number;
        m02: number;
        m13: number;
        m01: number;
        m12: number;
        m23: number;
        m03: number;
        static operationIndex: number;
        constructor(arg0: number[]);
        constructor(arg0: number[]);
        constructor(arg0: $DoubleBuffer);
        constructor(arg0: $FloatBuffer);
        constructor(arg0: $PoseStack);
        constructor(arg0: $Matrix4);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number);
        constructor();
        constructor(arg0: $Matrix4f);
    }
    export class $Transformation extends $ITransformation<$Vector3, $Transformation> implements $IVertexOperation {
        operationID(): number;
        applyN(arg0: $Vector3): void;
        operate(arg0: $CCRenderState): void;
        at(arg0: $Vector3): $Transformation;
        load(arg0: $CCRenderState): boolean;
        apply(arg0: $Matrix4): void;
        with(arg0: $Transformation): $TransformationList;
        static operationIndex: number;
        constructor();
    }
    export class $Translation extends $Transformation {
        apply(arg0: $Vector3): void;
        merge(arg0: $Transformation): $Transformation;
        static CENTER: $Translation;
        vec: $Vector3;
        static operationIndex: number;
        constructor(arg0: $Vector3);
        constructor(arg0: number, arg1: number, arg2: number);
        constructor(arg0: $Vec3i);
        constructor(arg0: $Translation);
    }
    export class $Quat implements $Copyable<$Quat> {
        rotation(): $Rotation;
        setAroundAxis(arg0: $Vector3, arg1: number): $Quat;
        setAroundAxis(arg0: number, arg1: number, arg2: number, arg3: number): $Quat;
        rightMultiply(arg0: $Quat): $Quat;
        toQuaternionF(): $Quaternionf;
        toQuaternionD(): $Quaterniond;
        static aroundAxis(arg0: $Vector3, arg1: number): $Quat;
        static aroundAxis(arg0: number, arg1: number, arg2: number, arg3: number): $Quat;
        mag(): number;
        multiply(arg0: $Quat): $Quat;
        rotate(arg0: $Vector3): void;
        normalize(): $Quat;
        set(arg0: $Quat): $Quat;
        set(arg0: number, arg1: number, arg2: number, arg3: number): $Quat;
        copy(): $Quat;
        s: number;
        x: number;
        y: number;
        z: number;
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: $Quaterniond);
        constructor(arg0: $Quaternionf);
        constructor(arg0: $Quat);
        constructor();
    }
}
