import { $ItemStackAPI } from "@package/org/figuramc/figura/lua/api/world";
import { $Entity } from "@package/net/minecraft/world/entity";
import { $FiguraVec2, $FiguraVec3 } from "@package/org/figuramc/figura/math/vector";
import { $Object } from "@package/java/lang";
import { $List } from "@package/java/util";
import { $LuaValue, $LuaTable } from "@package/org/luaj/vm2";

declare module "@package/org/figuramc/figura/lua/api/entity" {
    export class $EntityAPI<T extends $Entity> {
        getUUID(): string;
        isGlowing(): boolean;
        isInWater(): boolean;
        getBoundingBox(): $FiguraVec3;
        isInvisible(): boolean;
        getPassengers(): $List<$EntityAPI<never>>;
        getVehicle(): $EntityAPI<never>;
        isSprinting(): boolean;
        isInLava(): boolean;
        getControllingPassenger(): $EntityAPI<never>;
        getEyeY(): number;
        getPose(): string;
        isPlayer(): boolean;
        isOnFire(): boolean;
        getVelocity(): $FiguraVec3;
        isSneaking(): boolean;
        isCrouching(): boolean;
        isInRain(): boolean;
        getEyeHeight(): number;
        getControlledVehicle(): $EntityAPI<never>;
        getPermissionLevel(): number;
        isWet(): boolean;
        getPos(delta: number): $FiguraVec3;
        isMoving(ignoreY: boolean): boolean;
        getNearestEntity(type: string, radius: number): $EntityAPI<never>;
        __eq(rhs: $EntityAPI<never>): boolean;
        __tostring(): string;
        isUnderwater(): boolean;
        getEntity(): T;
        getLookDir(): $FiguraVec3;
        getFrozenTicks(): number;
        getMaxAir(): number;
        hasAvatar(): boolean;
        hasContainer(): boolean;
        getTargetedBlock(ignoreLiquids: boolean, distance: number): $Object[];
        isLiving(): boolean;
        getItem(index: number): $ItemStackAPI;
        getRot(delta: number): $FiguraVec2;
        getTargetedEntity(distance: number): $Object[];
        getDimensionName(): string;
        isFalling(): boolean;
        isOnGround(): boolean;
        hasInventory(): boolean;
        getNbt(): $LuaTable;
        isLoaded(): boolean;
        getVariable(key: string): $LuaValue;
        isSilent(): boolean;
        getName(): string;
        static wrap(e: $Entity): $EntityAPI<never>;
        isAlive(): boolean;
        getType(): string;
        constructor(entity: T);
        get UUID(): string;
        get glowing(): boolean;
        get inWater(): boolean;
        get boundingBox(): $FiguraVec3;
        get invisible(): boolean;
        get passengers(): $List<$EntityAPI<never>>;
        get vehicle(): $EntityAPI<never>;
        get sprinting(): boolean;
        get inLava(): boolean;
        get controllingPassenger(): $EntityAPI<never>;
        get eyeY(): number;
        get pose(): string;
        get player(): boolean;
        get onFire(): boolean;
        get velocity(): $FiguraVec3;
        get sneaking(): boolean;
        get crouching(): boolean;
        get inRain(): boolean;
        get eyeHeight(): number;
        get controlledVehicle(): $EntityAPI<never>;
        get permissionLevel(): number;
        get wet(): boolean;
        get underwater(): boolean;
        get entity(): T;
        get lookDir(): $FiguraVec3;
        get frozenTicks(): number;
        get maxAir(): number;
        get living(): boolean;
        get dimensionName(): string;
        get falling(): boolean;
        get onGround(): boolean;
        get nbt(): $LuaTable;
        get loaded(): boolean;
        get silent(): boolean;
        get name(): string;
        get alive(): boolean;
        get type(): string;
    }
}
