import { $ItemStackAPI } from "@package/org/figuramc/figura/lua/api/world";
import { $EntityAPI } from "@package/org/figuramc/figura/lua/api/entity";
import { $ResourceLocation } from "@package/net/minecraft/resources";
import { $Avatar } from "@package/org/figuramc/figura/avatar";
import { $FiguraTexture } from "@package/org/figuramc/figura/model/rendering/texture";
import { $FiguraVec2, $FiguraVec4, $FiguraVec3 } from "@package/org/figuramc/figura/math/vector";
import { $Object } from "@package/java/lang";
import { $NativeImage } from "@package/com/mojang/blaze3d/platform";
import { $List, $Map } from "@package/java/util";
import { $LuaValue, $LuaTable } from "@package/org/luaj/vm2";
import { $FiguraMat3, $FiguraMat4 } from "@package/org/figuramc/figura/math/matrix";
export * as keybind from "@package/org/figuramc/figura/lua/api/keybind";
export * as data from "@package/org/figuramc/figura/lua/api/data";
export * as nameplate from "@package/org/figuramc/figura/lua/api/nameplate";
export * as action_wheel from "@package/org/figuramc/figura/lua/api/action_wheel";
export * as world from "@package/org/figuramc/figura/lua/api/world";
export * as vanilla_model from "@package/org/figuramc/figura/lua/api/vanilla_model";
export * as entity from "@package/org/figuramc/figura/lua/api/entity";
export * as event from "@package/org/figuramc/figura/lua/api/event";
export * as ping from "@package/org/figuramc/figura/lua/api/ping";
export * as sound from "@package/org/figuramc/figura/lua/api/sound";

declare module "@package/org/figuramc/figura/lua/api" {
    export class $AvatarAPI {
        getAuthors(): string;
        getColor(): string;
        getUUID(): string;
        getVolume(): number;
        getPermissionLevel(): string;
        getTickCount(): number;
        hasTexture(): boolean;
        getBadges(): string;
        getEntityName(): string;
        getNBT(): $LuaTable;
        getCurrentInstructions(): number;
        hasScriptError(): boolean;
        getEntityInitCount(): number;
        getMaxInitCount(): number;
        getMaxTickCount(): number;
        getRenderCount(): number;
        getMaxRenderCount(): number;
        getWorldTickCount(): number;
        getMaxWorldTickCount(): number;
        getWorldRenderCount(): number;
        getMaxWorldRenderCount(): number;
        getMaxComplexity(): number;
        getRemainingParticles(): number;
        getRemainingSounds(): number;
        getMaxSounds(): number;
        getAnimationComplexity(): number;
        getMaxAnimationComplexity(): number;
        getAnimationCount(): number;
        getMaxAnimationCount(): number;
        getBuffersCount(): number;
        getMaxBuffersCount(): number;
        getMaxTextureSize(): number;
        getMaxBufferSize(): number;
        canEditVanillaModel(): boolean;
        canEditNameplate(): boolean;
        canRenderOffscreen(): boolean;
        canUseCustomSounds(): boolean;
        canHaveCustomSkull(): boolean;
        setColor(r: $Object, g: $Object, b: number, badge: string): $AvatarAPI;
        getVersion(): string;
        getComplexity(): number;
        getMaxParticles(): number;
        getSize(): number;
        color(r: $Object, g: $Object, b: number, badge: string): $AvatarAPI;
        getInitCount(): number;
        getName(): string;
        store(key: string, value: $LuaValue): $AvatarAPI;
        storedStuff: $LuaTable;
        constructor(avatar: $Avatar);
        get authors(): string;
        get UUID(): string;
        get volume(): number;
        get permissionLevel(): string;
        get tickCount(): number;
        get badges(): string;
        get entityName(): string;
        get NBT(): $LuaTable;
        get currentInstructions(): number;
        get entityInitCount(): number;
        get maxInitCount(): number;
        get maxTickCount(): number;
        get renderCount(): number;
        get maxRenderCount(): number;
        get worldTickCount(): number;
        get maxWorldTickCount(): number;
        get worldRenderCount(): number;
        get maxWorldRenderCount(): number;
        get maxComplexity(): number;
        get remainingParticles(): number;
        get remainingSounds(): number;
        get maxSounds(): number;
        get animationComplexity(): number;
        get maxAnimationComplexity(): number;
        get animationCount(): number;
        get maxAnimationCount(): number;
        get buffersCount(): number;
        get maxBuffersCount(): number;
        get maxTextureSize(): number;
        get maxBufferSize(): number;
        get version(): string;
        get complexity(): number;
        get maxParticles(): number;
        get size(): number;
        get initCount(): number;
        get name(): string;
    }
    export class $HostAPI {
        getScreen(): string;
        setClipboard(text: string): $HostAPI;
        sendChatMessage(message: string): $HostAPI;
        setTitle(text: string): $HostAPI;
        screenshot(name: string): $FiguraTexture;
        isFlying(): boolean;
        isJumping(): boolean;
        chatColor(x: $Object, y: number, z: number): $HostAPI;
        __index(arg: string): $Object;
        __newindex(key: string, value: $Object): void;
        getClipboard(): string;
        subtitle(text: string): $HostAPI;
        setSubtitle(text: string): $HostAPI;
        clipboard(text: string): $HostAPI;
        getAttackCharge(): number;
        getStatusEffects(): $List<$Map<string, $Object>>;
        isCursorUnlocked(): boolean;
        setUnlockCursor(bool: boolean): $HostAPI;
        setTitleTimes(x: $Object, y: number, z: number): $HostAPI;
        titleTimes(x: $Object, y: number, z: number): $HostAPI;
        clearTitle(): $HostAPI;
        setActionbar(text: string, animated: boolean): $HostAPI;
        actionbar(text: string, animated: boolean): $HostAPI;
        sendChatCommand(command: string): $HostAPI;
        appendChatHistory(message: string): $HostAPI;
        setChatMessage(index: number, newMessage: string, backgroundColor: $FiguraVec3): $HostAPI;
        swingArm(offhand: boolean): $HostAPI;
        setBadge(index: number, value: boolean, pride: boolean): $HostAPI;
        setChatColor(x: $Object, y: number, z: number): $HostAPI;
        getChatText(): string;
        setChatText(text: string): $HostAPI;
        chatText(text: string): $HostAPI;
        getScreenSlotCount(): number;
        getScreenSlot(slot: $Object): $ItemStackAPI;
        isChatOpen(): boolean;
        isContainerOpen(): boolean;
        isAvatarUploaded(): boolean;
        getPickEntity(): $EntityAPI<never>;
        isChatVerified(): boolean;
        writeToLog(string: string): void;
        warnToLog(string: string): void;
        isHost(): boolean;
        getChatMessage(index: number): $Map<string, $Object>;
        getPickBlock(): $Object[];
        getReachDistance(): number;
        getAir(): number;
        getChatColor(): number;
        badge(index: number, value: boolean, pride: boolean): $HostAPI;
        getSlot(slot: $Object): $ItemStackAPI;
        title(text: string): $HostAPI;
        setSlot(slot: $Object, item: $Object): $HostAPI;
        unlockCursor: boolean;
        constructor(owner: $Avatar);
        get screen(): string;
        get flying(): boolean;
        get jumping(): boolean;
        get attackCharge(): number;
        get statusEffects(): $List<$Map<string, $Object>>;
        get cursorUnlocked(): boolean;
        get screenSlotCount(): number;
        get chatOpen(): boolean;
        get containerOpen(): boolean;
        get avatarUploaded(): boolean;
        get pickEntity(): $EntityAPI<never>;
        get chatVerified(): boolean;
        get host(): boolean;
        get pickBlock(): $Object[];
        get reachDistance(): number;
        get air(): number;
    }
    export class $RendererAPI {
        isFirstPerson(): boolean;
        eyeOffset(x: $Object, y: number, z: number): $RendererAPI;
        postEffect(effect: string): $RendererAPI;
        fov(fov: number): $RendererAPI;
        cameraRot(x: $Object, y: number, z: number): $RendererAPI;
        cameraPos(x: $Object, y: number, z: number): $RendererAPI;
        outlineColor(r: $Object, g: number, b: number): $RendererAPI;
        blockOutlineColor(r: $Object, g: number, b: number, a: number): $RendererAPI;
        cameraNormal(matrix: $FiguraMat3): $RendererAPI;
        __index(arg: string): $Object;
        __newindex(key: string, value: boolean): void;
        renderLeftArm(bool: boolean): $RendererAPI;
        renderRightArm(bool: boolean): $RendererAPI;
        upsideDown(upsideDown: boolean): $RendererAPI;
        setShadowRadius(shadowRadius: number): $RendererAPI;
        getShadowRadius(): number;
        shadowRadius(shadowRadius: number): $RendererAPI;
        getOutlineColor(): $FiguraVec3;
        setOutlineColor(r: $Object, g: number, b: number): $RendererAPI;
        crosshairOffset(x: $Object, y: number): $RendererAPI;
        shouldRenderFire(): boolean;
        setRenderFire(renderFire: boolean): $RendererAPI;
        shouldRenderVehicle(): boolean;
        setRenderVehicle(renderVehicle: boolean): $RendererAPI;
        shouldRenderCrosshair(): boolean;
        setRenderCrosshair(renderCrosshair: boolean): $RendererAPI;
        shouldForcePaperdoll(): boolean;
        setForcePaperdoll(forcePaperdoll: boolean): $RendererAPI;
        shouldRenderHUD(): boolean;
        setRenderHUD(renderHUD: boolean): $RendererAPI;
        setUpsideDown(upsideDown: boolean): $RendererAPI;
        isCameraBackwards(): boolean;
        setCameraPos(x: $Object, y: number, z: number): $RendererAPI;
        getCameraPivot(): $FiguraVec3;
        setCameraPivot(x: $Object, y: number, z: number): $RendererAPI;
        getCameraOffsetPivot(): $FiguraVec3;
        setOffsetCameraPivot(x: $Object, y: number, z: number): $RendererAPI;
        offsetCameraPivot(x: $Object, y: number, z: number): $RendererAPI;
        getCameraRot(): $FiguraVec3;
        setCameraRot(x: $Object, y: number, z: number): $RendererAPI;
        getCameraOffsetRot(): $FiguraVec3;
        setOffsetCameraRot(x: $Object, y: number, z: number): $RendererAPI;
        offsetCameraRot(x: $Object, y: number, z: number): $RendererAPI;
        getCameraMatrix(): $FiguraMat4;
        setCameraMatrix(matrix: $FiguraMat4): $RendererAPI;
        cameraMatrix(matrix: $FiguraMat4): $RendererAPI;
        getCameraNormal(): $FiguraMat3;
        setCameraNormal(matrix: $FiguraMat3): $RendererAPI;
        setPostEffect(effect: string): $RendererAPI;
        getCrosshairOffset(): $FiguraVec2;
        setCrosshairOffset(x: $Object, y: number): $RendererAPI;
        getPrimaryFireTexture(): string;
        getSecondaryFireTexture(): string;
        setPrimaryFireTexture(id: string): $RendererAPI;
        primaryFireTexture(id: string): $RendererAPI;
        setSecondaryFireTexture(id: string): $RendererAPI;
        secondaryFireTexture(id: string): $RendererAPI;
        setRenderLeftArm(bool: boolean): $RendererAPI;
        getRenderLeftArm(): boolean;
        setRenderRightArm(bool: boolean): $RendererAPI;
        getRenderRightArm(): boolean;
        setEyeOffset(x: $Object, y: number, z: number): $RendererAPI;
        getEyeOffset(): $FiguraVec3;
        setBlockOutlineColor(r: $Object, g: number, b: number, a: number): $RendererAPI;
        getBlockOutlineColor(): $FiguraVec4;
        setRootRotationAllowed(bool: boolean): $RendererAPI;
        rootRotationAllowed(bool: boolean): $RendererAPI;
        cameraPivot(x: $Object, y: number, z: number): $RendererAPI;
        getCameraPos(): $FiguraVec3;
        getFOV(): number;
        setFOV(fov: number): $RendererAPI;
        getRootRotationAllowed(): boolean;
        isUpsideDown(): boolean;
        renderFire: boolean;
        rootRotation: boolean;
        cameraOffsetRot: $FiguraVec3;
        forcePaperdoll: boolean;
        cameraMat: $FiguraMat4;
        renderHUD: boolean;
        cameraOffsetPivot: $FiguraVec3;
        renderVehicle: boolean;
        postShader: $ResourceLocation;
        renderCrosshair: boolean;
        fireLayer2: $ResourceLocation;
        fireLayer1: $ResourceLocation;
        constructor(owner: $Avatar);
        get firstPerson(): boolean;
        get cameraBackwards(): boolean;
    }
    export class $TextureAPI {
        getTextures(): $List<$FiguraTexture>;
        __index(name: string): $FiguraTexture;
        fromVanilla(name: string, path: string): $FiguraTexture;
        newTexture(name: string, width: number, height: number): $FiguraTexture;
        get(name: string): $FiguraTexture;
        register(name: string, image: $NativeImage, ignoreSize: boolean): $FiguraTexture;
        read(name: string, object: $Object): $FiguraTexture;
        copy(name: string, texture: $FiguraTexture): $FiguraTexture;
        static TEXTURE_LIMIT: number;
        constructor(owner: $Avatar);
        get textures(): $List<$FiguraTexture>;
    }
}
