import { $Level_ } from "@package/net/minecraft/world/level";
import { $HolderLookup$Provider, $GlobalPos } from "@package/net/minecraft/core";
import { $TransferHandler, $FluxNetwork, $FluxMenu } from "@package/sonar/fluxnetworks/common/connection";
import { $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $IFluxDevice } from "@package/sonar/fluxnetworks/api/device";
import { $Component } from "@package/net/minecraft/network/chat";
import { $RegistryFriendlyByteBuf, $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $Player, $Inventory } from "@package/net/minecraft/world/entity/player";
import { $ClientboundBlockEntityDataPacket } from "@package/net/minecraft/network/protocol/game";
import { $AbstractContainerMenu } from "@package/net/minecraft/world/inventory";
import { $UUID_, $UUID } from "@package/java/util";
import { $BlockEntity, $BlockEntityTicker } from "@package/net/minecraft/world/level/block/entity";

declare module "@package/sonar/fluxnetworks/common/device" {
    export class $TileFluxDevice extends $BlockEntity implements $IFluxDevice {
        setOwnerUUID(arg0: $UUID_): void;
        getCustomName(): string;
        getUpdatePacket(): $ClientboundBlockEntityDataPacket;
        loadAdditional(arg0: $CompoundTag_, arg1: $HolderLookup$Provider): void;
        static getTicker<T extends $BlockEntity>(arg0: $Level_): $BlockEntityTicker<T>;
        createMenu(arg0: number, arg1: $Inventory, arg2: $Player): $FluxMenu;
        getNetwork(): $FluxNetwork;
        getOwnerUUID(): $UUID;
        getGlobalPos(): $GlobalPos;
        onPlayerInteract(arg0: $Player): void;
        getRawPriority(): number;
        getRawLimit(): number;
        getSurgeMode(): boolean;
        getDisableLimit(): boolean;
        isForcedLoading(): boolean;
        onPlayerOpened(arg0: $Player): void;
        isChunkLoaded(): boolean;
        onPlayerClosed(arg0: $Player): void;
        getNetworkID(): number;
        getTransferBuffer(): number;
        canPlayerAccess(arg0: $Player): boolean;
        readCustomTag(arg0: $CompoundTag_, arg1: number): void;
        getTransferHandler(): $TransferHandler;
        writeCustomTag(arg0: $CompoundTag_, arg1: number): void;
        getMaxTransferLimit(): number;
        getTransferChange(): number;
        sendBlockUpdate(): void;
        markChunkUnsaved(): void;
        setForcedLoading(arg0: boolean): void;
        writePacketBuffer(arg0: $FriendlyByteBuf, arg1: number): void;
        readPacketBuffer(arg0: $FriendlyByteBuf, arg1: number): void;
        markEnergyChanged(): void;
        disconnect(): void;
        connect(arg0: $FluxNetwork): boolean;
        getDisplayName(): $Component;
        shouldTriggerClientSideContainerClosingOnOpen(): boolean;
        writeClientSideData(arg0: $AbstractContainerMenu, arg1: $RegistryFriendlyByteBuf): void;
        shouldCloseCurrentScreen(): boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static MAX_CUSTOM_NAME_LENGTH: number;
        static INVALID_CLIENT_COLOR: number;
        mClientColor: number;
        get customName(): string;
        get updatePacket(): $ClientboundBlockEntityDataPacket;
        get network(): $FluxNetwork;
        get globalPos(): $GlobalPos;
        get rawPriority(): number;
        get rawLimit(): number;
        get surgeMode(): boolean;
        get disableLimit(): boolean;
        get chunkLoaded(): boolean;
        get networkID(): number;
        get transferBuffer(): number;
        get transferHandler(): $TransferHandler;
        get maxTransferLimit(): number;
        get transferChange(): number;
        get displayName(): $Component;
    }
}
