import { $ChunkPos, $Level } from "@package/net/minecraft/world/level";
import { $ItemStack_ } from "@package/net/minecraft/world/item";
import { $MCDataByteBuf } from "@package/codechicken/lib/data";
import { $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $Component_ } from "@package/net/minecraft/network/chat";
import { $Vector3 } from "@package/codechicken/lib/vec";
import { $CustomPacketPayload } from "@package/net/minecraft/network/protocol/common/custom";
import { $UUID_ } from "@package/java/util";
import { $FloatBuffer, $ShortBuffer } from "@package/java/nio";
import { $ServerPlayer, $ServerLevel } from "@package/net/minecraft/server/level";
import { $BlockPos_, $Direction_, $RegistryAccess, $Registry, $Vec3i } from "@package/net/minecraft/core";
import { $ResourceLocation_, $ResourceKey_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $Packet } from "@package/net/minecraft/network/protocol";
import { $ByteBuf } from "@package/io/netty/buffer";
import { $Enum } from "@package/java/lang";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";

declare module "@package/codechicken/lib/packet" {
    export class $PacketCustom extends $MCDataByteBuf {
        sendToServer(): void;
        sendToPlayer(arg0: $ServerPlayer): void;
        writeUUID(arg0: $UUID_): $PacketCustom;
        writeByteBuf(arg0: $ByteBuf): $PacketCustom;
        writeVarInt(arg0: number): $PacketCustom;
        writeResourceLocation(arg0: $ResourceLocation_): $PacketCustom;
        sendToAllPlayers(): void;
        writeEnum(arg0: $Enum<never>): $PacketCustom;
        writeInts(arg0: number[]): $PacketCustom;
        writeInts(arg0: number[], arg1: number, arg2: number): $PacketCustom;
        writeFloats(arg0: number[]): $PacketCustom;
        writeDoubles(arg0: number[]): $PacketCustom;
        writeShorts(arg0: number[], arg1: number, arg2: number): $PacketCustom;
        writeBooleans(arg0: boolean[], arg1: number, arg2: number): $PacketCustom;
        sendToAllAround(arg0: number, arg1: number, arg2: number, arg3: number, arg4: $ResourceKey_<$Level>): void;
        sendToAllAround(arg0: $BlockPos_, arg1: number, arg2: $ResourceKey_<$Level>): void;
        writeVector(arg0: $Vector3): $PacketCustom;
        toClientPacket(): $Packet<never>;
        writePos(arg0: $BlockPos_): $PacketCustom;
        writeTextComponent(arg0: $Component_): $PacketCustom;
        sendToChunk(arg0: $ServerLevel, arg1: number, arg2: number): void;
        sendToChunk(arg0: $ServerLevel, arg1: $BlockPos_): void;
        sendToChunk(arg0: $ServerLevel, arg1: $ChunkPos): void;
        sendToChunk(arg0: $BlockEntity): void;
        writeVarInts(arg0: number[], arg1: number, arg2: number): $PacketCustom;
        writeVarLongs(arg0: number[], arg1: number, arg2: number): $PacketCustom;
        writeVec3i(arg0: $Vec3i): $PacketCustom;
        writeCompoundNBT(arg0: $CompoundTag_): $PacketCustom;
        writeRegistryIdDirect<T>(arg0: $Registry<T>, arg1: T): $PacketCustom;
        writeShortBuffer(arg0: $ShortBuffer): $PacketCustom;
        writeFloatBuffer(arg0: $FloatBuffer): $PacketCustom;
        writeDirection(arg0: $Direction_): $PacketCustom;
        writeItemStack(arg0: $ItemStack_): $PacketCustom;
        isInbound(): boolean;
        toCustomPayload(): $CustomPacketPayload;
        sendToDimension(arg0: $ResourceKey_<$Level>): void;
        sendToOps(): void;
        toServerPacket(): $Packet<never>;
        getChannel(): $ResourceLocation;
        writeChar(arg0: number): $PacketCustom;
        writeString(arg0: string, arg1: number): $PacketCustom;
        writeBoolean(arg0: boolean): $PacketCustom;
        writeByte(arg0: number): $PacketCustom;
        writeLong(arg0: number): $PacketCustom;
        writeDouble(arg0: number): $PacketCustom;
        writeChars(arg0: string[]): $PacketCustom;
        getType(): number;
        constructor(arg0: $ResourceLocation_, arg1: number, arg2: $RegistryAccess);
        get inbound(): boolean;
        get channel(): $ResourceLocation;
        get type(): number;
    }
}
