import { $EntityDataAccessor, $EntityDataAccessor_ } from "@package/net/minecraft/network/syncher";
import { $Level_, $Level } from "@package/net/minecraft/world/level";
import { $HolderLookup$Provider, $BlockPos, $Direction } from "@package/net/minecraft/core";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $Entity, $PortalProcessor } from "@package/net/minecraft/world/entity";
import { $RigidBodyHandle } from "@package/dev/ryanhcode/sable/api/physics/handle";
import { $ThrowableProjectile } from "@package/net/minecraft/world/entity/projectile";
import { $UUID } from "@package/java/util";
import { $ServerSubLevel } from "@package/dev/ryanhcode/sable/sublevel";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";

declare module "@package/dev/simulated_team/simulated/content/entities/launched_plunger" {
    export class $LaunchedPlungerEntity extends $ThrowableProjectile {
        physicsTick(arg0: $ServerSubLevel, arg1: $RigidBodyHandle, arg2: number): void;
        setData<T>(arg0: $EntityDataAccessor_<T>, arg1: T): void;
        getOther(): $LaunchedPlungerEntity;
        resetPlunged(): void;
        isPlunged(): boolean;
        getAttachmentPos(arg0: number): $Vec3;
        getAttachmentPos(): $Vec3;
        setOther(arg0: $LaunchedPlungerEntity): void;
        getClientTarget(arg0: number): $Vec3;
        getPlungedTime(): number;
        getAnimationOffset(): number;
        getClientSmoothedVelocity(arg0: number): $Vec3;
        static create(arg0: $EntityType_<$LaunchedPlungerEntity>, arg1: $Level_): $LaunchedPlungerEntity;
        getTarget(): $Vec3;
        getData<T>(arg0: $EntityDataAccessor_<T>): T;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        xRot: number;
        hasImpulse: boolean;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        leftOwner: boolean;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        static PLUNGED_BLOCK_POS: $EntityDataAccessor<$BlockPos>;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        yRot: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static OTHER_PLUNGER_ID: $EntityDataAccessor<number>;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static IS_FIRST: $EntityDataAccessor<boolean>;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        static PLUNGED_DIRECTION: $EntityDataAccessor<$Direction>;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        ownerUUID: $UUID;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        hasBeenShot: boolean;
        cachedOwner: $Entity;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static OTHER_PLUNGER: $EntityDataAccessor<($UUID) | undefined>;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static TARGET_POS: $EntityDataAccessor<$Vec3>;
        static IS_PLUNGED: $EntityDataAccessor<boolean>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$LaunchedPlungerEntity>, arg1: $Level_);
        get plunged(): boolean;
        get plungedTime(): number;
        get animationOffset(): number;
        get target(): $Vec3;
    }
}
