import { $Consumer_, $Consumer, $Supplier_, $Function_, $BiFunction_, $Supplier } from "@package/java/util/function";
import { $Holder_, $Holder } from "@package/net/minecraft/core";
import { $SoundEvent } from "@package/net/minecraft/sounds";
import { $ModularGui } from "@package/codechicken/lib/gui/modular";
import { $ItemStack } from "@package/net/minecraft/world/item";
import { $Component_, $Component } from "@package/net/minecraft/network/chat";
import { $GuiRender, $ForegroundRender, $ElementEvents, $TooltipHandler } from "@package/codechicken/lib/gui/modular/lib";
import { $List, $List_ } from "@package/java/util";
import { $Runnable_ } from "@package/java/lang";
import { $ConstrainedGeometry, $Align_, $Position, $GuiParent, $Align, $Rectangle } from "@package/codechicken/lib/gui/modular/lib/geometry";

declare module "@package/codechicken/lib/gui/modular/elements" {
    export class $GuiElement<T extends $GuiElement<T>> extends $ConstrainedGeometry<T> implements $ElementEvents, $TooltipHandler<T> {
        isTooltipEnabled(): boolean;
        isRemoved(): boolean;
        setEnabled(arg0: $Supplier_<boolean>): T;
        setEnabled(arg0: boolean): T;
        isMouseOver(): boolean;
        getTooltip(): $Supplier<$List<$Component>>;
        setTooltip(arg0: $Supplier_<$List<$Component>>): T;
        jeiExclude(): T;
        hoverTime(): number;
        zStacking(): boolean;
        isJeiExcluded(): boolean;
        initElement(arg0: $GuiParent<never>): void;
        sendChildToIndex(arg0: $GuiElement<never>, arg1: number): void;
        getCombinedElementDepth(): number;
        showToolTip(): boolean;
        getTooltipDelay(): number;
        addJeiExclusions(arg0: $List_<$GuiElement<never>>): $List<$GuiElement<never>>;
        isJeiDropTarget(): boolean;
        addJeiDropTargets(arg0: $List_<$GuiElement<never>>): $List<$GuiElement<never>>;
        bringChildToForeground(arg0: $GuiElement<never>): void;
        sendChildToBackground(arg0: $GuiElement<never>): void;
        setEnableToolTip(arg0: $Supplier_<boolean>): T;
        blockMouseEvents(): boolean;
        setRenderCull(arg0: $Rectangle): T;
        setZStacking(arg0: boolean): T;
        setJeiExcluded(arg0: boolean): T;
        setJeiDropTarget(arg0: $Consumer_<$ItemStack>, arg1: boolean): T;
        getJeiDropConsumer(): $Consumer<$ItemStack>;
        tick(arg0: number, arg1: number): void;
        renderOverlay(arg0: $GuiRender, arg1: number, arg2: number, arg3: number, arg4: boolean): boolean;
        updateMouseOver(arg0: number, arg1: number, arg2: boolean): boolean;
        setOpaque(arg0: boolean): T;
        isOpaque(): boolean;
        render(arg0: $GuiRender, arg1: number, arg2: number, arg3: number): void;
        isEnabled(): boolean;
        mouseMoved(arg0: number, arg1: number): void;
        mouseScrolled(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        mouseScrolled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean): boolean;
        charTyped(arg0: string, arg1: number, arg2: boolean): boolean;
        charTyped(arg0: string, arg1: number): boolean;
        keyPressed(arg0: number, arg1: number, arg2: number): boolean;
        keyPressed(arg0: number, arg1: number, arg2: number, arg3: boolean): boolean;
        keyReleased(arg0: number, arg1: number, arg2: number): boolean;
        keyReleased(arg0: number, arg1: number, arg2: number, arg3: boolean): boolean;
        mouseClicked(arg0: number, arg1: number, arg2: number, arg3: boolean): boolean;
        mouseClicked(arg0: number, arg1: number, arg2: number): boolean;
        mouseReleased(arg0: number, arg1: number, arg2: number): boolean;
        mouseReleased(arg0: number, arg1: number, arg2: number, arg3: boolean): boolean;
        renderTooltip(arg0: $GuiRender, arg1: number, arg2: number): boolean;
        setTooltip(arg0: $List_<$Component_>): T;
        setTooltip(arg0: $Supplier_<$List<$Component>>, arg1: number): T;
        setTooltip(...arg0: $Component_[]): T;
        setTooltipSingle(arg0: $Supplier_<$Component>): T;
        setTooltipSingle(arg0: $Component_): T;
        setTooltipDelay(arg0: number): T;
        initialized: boolean;
        constructor(arg0: $GuiParent<never>);
        get tooltipEnabled(): boolean;
        get removed(): boolean;
        get mouseOver(): boolean;
        get combinedElementDepth(): number;
        set enableToolTip(value: $Supplier_<boolean>);
        set renderCull(value: $Rectangle);
        set ZStacking(value: boolean);
        get jeiDropConsumer(): $Consumer<$ItemStack>;
    }
    export class $GuiContextMenu extends $GuiElement<$GuiContextMenu> {
        actionOnClick(): $GuiContextMenu;
        setCloseOnItemClicked(arg0: boolean): $GuiContextMenu;
        setCloseOnOutsideClick(arg0: boolean): $GuiContextMenu;
        setButtonBuilder(arg0: $BiFunction_<$GuiContextMenu, $Supplier<$Component>, $GuiButton>): $GuiContextMenu;
        setNormalizedPos(arg0: number, arg1: number): $GuiContextMenu;
        static tooltipStyleMenu(arg0: $GuiParent<never>): $GuiContextMenu;
        addOption(arg0: $Supplier_<$Component>, arg1: $List_<$Component_>, arg2: $Runnable_): $GuiContextMenu;
        addOption(arg0: $Supplier_<$Component>, arg1: $Runnable_): $GuiContextMenu;
        addOption(arg0: $Supplier_<$Component>, arg1: $Runnable_, ...arg2: $Component_[]): $GuiContextMenu;
        addOption(arg0: $Supplier_<$Component>, arg1: $Supplier_<$List<$Component>>, arg2: $Runnable_): $GuiContextMenu;
        close(): void;
        initialized: boolean;
        constructor(arg0: $ModularGui);
        set closeOnItemClicked(value: boolean);
        set closeOnOutsideClick(value: boolean);
        set buttonBuilder(value: $BiFunction_<$GuiContextMenu, $Supplier<$Component>, $GuiButton>);
    }
    export class $GuiText extends $GuiElement<$GuiText> implements $ForegroundRender {
        setAlignment(arg0: $Align_): $GuiText;
        setScroll(arg0: boolean): $GuiText;
        setTextSupplier(arg0: $Supplier_<$Component>): $GuiText;
        setRotation(arg0: $Supplier_<number>): $GuiText;
        setRotation(arg0: number): $GuiText;
        getForegroundDepth(): number;
        autoHeight(): $GuiText;
        getTrim(): boolean;
        autoWidth(): $GuiText;
        getWrap(): boolean;
        setRotatePoint(arg0: $Position): $GuiText;
        setText(arg0: string): $GuiText;
        setText(arg0: $Component_): $GuiText;
        setShadow(arg0: $Supplier_<boolean>): $GuiText;
        setShadow(arg0: boolean): $GuiText;
        getShadow(): boolean;
        renderForeground(arg0: $GuiRender, arg1: number, arg2: number, arg3: number): void;
        getTextColour(): number;
        setTextColour(arg0: number): $GuiText;
        setTextColour(arg0: $Supplier_<number>): $GuiText;
        setWrap(arg0: boolean): $GuiText;
        getScroll(): boolean;
        setTranslatable(arg0: string): $GuiText;
        setTrim(arg0: boolean): $GuiText;
        getText(): $Component;
        getAlignment(): $Align;
        initialized: boolean;
        constructor(arg0: $GuiParent<never>);
        constructor(arg0: $GuiParent<never>, arg1: $Supplier_<$Component>);
        constructor(arg0: $GuiParent<never>, arg1: $Component_);
        set textSupplier(value: $Supplier_<$Component>);
        get foregroundDepth(): number;
        set rotatePoint(value: $Position);
        set translatable(value: string);
    }
    export class $GuiButton extends $GuiElement<$GuiButton> {
        static vanilla(arg0: $GuiParent<never>, arg1: $Component_): $GuiButton;
        static vanilla(arg0: $GuiParent<never>, arg1: $Component_, arg2: $Runnable_): $GuiButton;
        onClick(arg0: $Runnable_, arg1: number): $GuiButton;
        onClick(arg0: $Runnable_): $GuiButton;
        isPressed(): boolean;
        onPress(arg0: $Runnable_): $GuiButton;
        onPress(arg0: $Runnable_, arg1: number): $GuiButton;
        setDisabled(arg0: $Supplier_<boolean>): $GuiButton;
        setDisabled(arg0: boolean): $GuiButton;
        isDisabled(): boolean;
        toggleState(): boolean;
        static flatColourButton(arg0: $GuiParent<never>, arg1: $Supplier_<$Component>, arg2: $Function_<boolean, number>): $GuiButton;
        static flatColourButton(arg0: $GuiParent<never>, arg1: $Supplier_<$Component>, arg2: $Function_<boolean, number>, arg3: $Function_<boolean, number>): $GuiButton;
        getPressSound(): $Holder<$SoundEvent>;
        getReleaseSound(): $Holder<$SoundEvent>;
        setResetHoverOnPress(arg0: boolean): $GuiButton;
        setToggleMode(arg0: $Supplier_<boolean>): $GuiButton;
        setPressSound(arg0: $Holder_<$SoundEvent>): $GuiButton;
        setReleaseSound(arg0: $Holder_<$SoundEvent>): $GuiButton;
        static vanillaAnimated(arg0: $GuiParent<never>, arg1: $Supplier_<$Component>): $GuiButton;
        static vanillaAnimated(arg0: $GuiParent<never>, arg1: $Supplier_<$Component>, arg2: $Runnable_): $GuiButton;
        static vanillaAnimated(arg0: $GuiParent<never>, arg1: $Component_, arg2: $Runnable_): $GuiButton;
        static vanillaAnimated(arg0: $GuiParent<never>, arg1: $Component_): $GuiButton;
        getLabel(): $GuiText;
        setLabel(arg0: $GuiText): $GuiButton;
        static MIDDLE_CLICK: number;
        static RIGHT_CLICK: number;
        initialized: boolean;
        static LEFT_CLICK: number;
        constructor(arg0: $GuiParent<never>);
        get pressed(): boolean;
        set resetHoverOnPress(value: boolean);
        set toggleMode(value: $Supplier_<boolean>);
    }
}
