import { $BlockPos, $BlockPos_ } from "@package/net/minecraft/core";
import { $Object } from "@package/java/lang";
import { $Vec3_, $Vec3 } from "@package/net/minecraft/world/phys";
import { $LuaFunction } from "@package/org/luaj/vm2";
import { $FiguraMatrix, $FiguraMat2, $FiguraMat3, $FiguraMat4 } from "@package/org/figuramc/figura/math/matrix";
import { $Vector3f } from "@package/org/joml";

declare module "@package/org/figuramc/figura/math/vector" {
    export class $FiguraVector<T extends $FiguraVector<T, M>, M extends $FiguraMatrix<M, T>> {
        lengthSquared(): number;
        clampLength(minLength: number, maxLength: number): T;
        toRad(): T;
        toDeg(): T;
        offseted(factor: number): T;
        clamped(minLength: number, maxLength: number): T;
        scaled(factor: number): T;
        times(other: T): T;
        subtract(arg0: T): T;
        divide(arg0: T): T;
        plus(other: T): T;
        dividedBy(other: T): T;
        minus(other: T): T;
        w(): number;
        y(): number;
        reduce(arg0: T): T;
        multiply(arg0: T): T;
        normalize(): T;
        normalized(): T;
        unpack(): number[];
        index(arg0: number): number;
        size(): number;
        length(): number;
        scale(arg0: number): T;
        add(arg0: T): T;
        offset(arg0: number): T;
        x(): number;
        transform(arg0: M): T;
        dot(arg0: T): number;
        set(arg0: T): T;
        mod(other: T): T;
        copy(): T;
        z(): number;
        constructor();
    }
    export class $FiguraVec2 extends $FiguraVector<$FiguraVec2, $FiguraMat2> {
        augmented(d: number): $FiguraVec3;
        static __add(a: $Object, b: $Object): $FiguraVec2;
        static __sub(a: $Object, b: $Object): $FiguraVec2;
        static __mul(a: $Object, b: $Object): $FiguraVec2;
        __div(rhs: $Object): $FiguraVec2;
        __mod(rhs: $Object): $FiguraVec2;
        __eq(other: $FiguraVec2): boolean;
        __unm(): $FiguraVec2;
        __len(): number;
        __lt(r: $FiguraVec2): boolean;
        __le(r: $FiguraVec2): boolean;
        __tostring(): string;
        __index(arg: $Object): $Object;
        __newindex(key: string, value: $Object): void;
        applyFunc(_function: $LuaFunction): $FiguraVec2;
        subtract(other: $FiguraVec2): $FiguraVec2;
        subtract(x: number, y: number): $FiguraVec2;
        divide(x: number, y: number): $FiguraVec2;
        divide(other: $FiguraVec2): $FiguraVec2;
        div(x: $Object, y: number): $FiguraVec2;
        mul(x: $Object, y: number): $FiguraVec2;
        reduce(x: number, y: number): $FiguraVec2;
        reduce(other: $FiguraVec2): $FiguraVec2;
        reduce(x: $Object, y: number): $FiguraVec2;
        multiply(x: number, y: number): $FiguraVec2;
        multiply(other: $FiguraVec2): $FiguraVec2;
        sub(x: $Object, y: number): $FiguraVec2;
        reset(): $FiguraVec2;
        floor(): $FiguraVec2;
        ceil(): $FiguraVec2;
        add(x: number, y: number): $FiguraVec2;
        add(x: $Object, y: number): $FiguraVec2;
        add(other: $FiguraVec2): $FiguraVec2;
        static of(x: number, y: number): $FiguraVec2;
        static of(): $FiguraVec2;
        offset(factor: number): $FiguraVec2;
        transform(mat: $FiguraMat2): $FiguraVec2;
        dot(other: $FiguraVec2): number;
        set(other: $FiguraVec2): $FiguraVec2;
        set(x: $Object, y: number): $FiguraVec2;
        set(x: number, y: number): $FiguraVec2;
        constructor();
    }
    export class $FiguraVec4 extends $FiguraVector<$FiguraVec4, $FiguraMat4> {
        clampLength(min: number, max: number): $FiguraVec4;
        toDeg(): $FiguraVec4;
        static __add(a: $Object, b: $Object): $FiguraVec4;
        static __sub(a: $Object, b: $Object): $FiguraVec4;
        static __mul(a: $Object, b: $Object): $FiguraVec4;
        __div(rhs: $Object): $FiguraVec4;
        __mod(rhs: $Object): $FiguraVec4;
        __eq(other: $FiguraVec4): boolean;
        __unm(): $FiguraVec4;
        __len(): number;
        __lt(r: $FiguraVec4): boolean;
        __le(r: $FiguraVec4): boolean;
        __tostring(): string;
        __index(arg: $Object): $Object;
        __newindex(key: string, value: $Object): void;
        applyFunc(_function: $LuaFunction): $FiguraVec4;
        subtract(x: number, y: number, z: number, w: number): $FiguraVec4;
        subtract(other: $FiguraVec4): $FiguraVec4;
        divide(x: number, y: number, z: number, w: number): $FiguraVec4;
        divide(other: $FiguraVec4): $FiguraVec4;
        div(x: $Object, y: number, z: number, w: number): $FiguraVec4;
        mul(x: $Object, y: number, z: number, w: number): $FiguraVec4;
        reduce(x: $Object, y: number, z: number, w: number): $FiguraVec4;
        reduce(x: number, y: number, z: number, w: number): $FiguraVec4;
        reduce(other: $FiguraVec4): $FiguraVec4;
        multiply(x: number, y: number, z: number, w: number): $FiguraVec4;
        multiply(other: $FiguraVec4): $FiguraVec4;
        normalize(): $FiguraVec4;
        sub(x: $Object, y: number, z: number, w: number): $FiguraVec4;
        reset(): $FiguraVec4;
        floor(): $FiguraVec4;
        ceil(): $FiguraVec4;
        scale(factor: number): $FiguraVec4;
        add(x: $Object, y: number, z: number, w: number): $FiguraVec4;
        add(x: number, y: number, z: number, w: number): $FiguraVec4;
        add(other: $FiguraVec4): $FiguraVec4;
        static of(x: number, y: number, z: number, w: number): $FiguraVec4;
        static of(): $FiguraVec4;
        offset(factor: number): $FiguraVec4;
        transform(mat: $FiguraMat4): $FiguraVec4;
        dot(other: $FiguraVec4): number;
        set(other: $FiguraVec4): $FiguraVec4;
        set(x: $Object, y: number, z: number, w: number): $FiguraVec4;
        set(x: number, y: number, z: number, w: number): $FiguraVec4;
        constructor();
    }
    export class $FiguraVec3 extends $FiguraVector<$FiguraVec3, $FiguraMat3> {
        cross(other: $FiguraVec3): $FiguraVec3;
        static fromVec3(vec: $Vec3_): $FiguraVec3;
        asVec3(): $Vec3;
        static fromVec3f(vec: $Vector3f): $FiguraVec3;
        augmented(d: number): $FiguraVec4;
        crossed(other: $FiguraVec3): $FiguraVec3;
        asBlockPos(): $BlockPos;
        static fromBlockPos(pos: $BlockPos_): $FiguraVec3;
        asVec3f(): $Vector3f;
        static __add(a: $Object, b: $Object): $FiguraVec3;
        static __sub(a: $Object, b: $Object): $FiguraVec3;
        static __mul(a: $Object, b: $Object): $FiguraVec3;
        __div(rhs: $Object): $FiguraVec3;
        __mod(rhs: $Object): $FiguraVec3;
        __eq(other: $FiguraVec3): boolean;
        __unm(): $FiguraVec3;
        __len(): number;
        __lt(r: $FiguraVec3): boolean;
        __le(r: $FiguraVec3): boolean;
        __tostring(): string;
        __index(arg: $Object): $Object;
        __newindex(key: string, value: $Object): void;
        clamped(min: number, max: number): $FiguraVec3;
        notNaN(): boolean;
        applyFunc(_function: $LuaFunction): $FiguraVec3;
        subtract(x: number, y: number, z: number): $FiguraVec3;
        subtract(other: $FiguraVec3): $FiguraVec3;
        divide(other: $FiguraVec3): $FiguraVec3;
        divide(x: number, y: number, z: number): $FiguraVec3;
        div(x: $Object, y: number, z: number): $FiguraVec3;
        mul(x: $Object, y: number, z: number): $FiguraVec3;
        reduce(x: number, y: number, z: number): $FiguraVec3;
        reduce(other: $FiguraVec3): $FiguraVec3;
        reduce(x: $Object, y: number, z: number): $FiguraVec3;
        multiply(x: number, y: number, z: number): $FiguraVec3;
        multiply(other: $FiguraVec3): $FiguraVec3;
        normalize(): $FiguraVec3;
        normalized(): $FiguraVec3;
        sub(x: $Object, y: number, z: number): $FiguraVec3;
        reset(): $FiguraVec3;
        floor(): $FiguraVec3;
        ceil(): $FiguraVec3;
        scale(factor: number): $FiguraVec3;
        add(x: $Object, y: number, z: number): $FiguraVec3;
        add(x: number, y: number, z: number): $FiguraVec3;
        add(other: $FiguraVec3): $FiguraVec3;
        static of(x: number, y: number, z: number): $FiguraVec3;
        static of(): $FiguraVec3;
        offset(factor: number): $FiguraVec3;
        transform(mat: $FiguraMat3): $FiguraVec3;
        dot(other: $FiguraVec3): number;
        set(x: $Object, y: number, z: number): $FiguraVec3;
        set(other: $FiguraVec3): $FiguraVec3;
        set(x: number, y: number, z: number): $FiguraVec3;
        constructor();
    }
}
