import { $GoalSelector } from "@package/net/minecraft/world/entity/ai/goal";
import { $LookControl } from "@package/net/minecraft/world/entity/ai/control";
import { $Codec } from "@package/com/mojang/serialization";
import { $Pair } from "@package/com/mojang/datafixers/util";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $SpellData } from "@package/io/redspace/ironsspellbooks/api/spells";
import { $EntityType_, $PortalProcessor, $Pose_, $Entity, $AnimationState, $EntityDimensions, $Entity$RemovalReason, $LivingEntity, $WalkAnimationState } from "@package/net/minecraft/world/entity";
import { $GameEvent, $GameEvent$Context_ } from "@package/net/minecraft/world/level/gameevent";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $HashMap, $UUID_, $List_, $Comparator, $Map, $OptionalInt } from "@package/java/util";
import { $InteractionHand } from "@package/net/minecraft/world";
import { $ToDoubleFunction_, $Function_, $Predicate_, $ToLongFunction_, $ToIntFunction_ } from "@package/java/util/function";
import { $HolderLookup$Provider, $BlockPos, $Holder_, $Holder, $BlockPos_ } from "@package/net/minecraft/core";
import { $ServerLevel, $ServerPlayer } from "@package/net/minecraft/server/level";
import { $SoundEvent } from "@package/net/minecraft/sounds";
import { $Enum, $Record, $Comparable } from "@package/java/lang";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";
import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey } from "@package/net/minecraft/tags";
import { $MobEffectInstance, $MobEffect } from "@package/net/minecraft/world/effect";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $VibrationSystem$User, $VibrationSystem$Data, $VibrationSystem } from "@package/net/minecraft/world/level/gameevent/vibrations";
import { $ResourceKey } from "@package/net/minecraft/resources";
import { $Monster } from "@package/net/minecraft/world/entity/monster";
import { $Vec3, $Vec3_ } from "@package/net/minecraft/world/phys";

declare module "@package/net/minecraft/world/entity/monster/warden" {
    export class $Warden$VibrationUser implements $VibrationSystem$User {
        requiresAdjacentChunksToBeTicking(): boolean;
        calculateTravelTimeInTicks(arg0: number): number;
        isValidVibration(arg0: $Holder_<$GameEvent>, arg1: $GameEvent$Context_): boolean;
        onDataChanged(): void;
        getListenableEvents(): $TagKey<$GameEvent>;
        canTriggerAvoidVibration(): boolean;
        get listenableEvents(): $TagKey<$GameEvent>;
    }
    export class $WardenAi {
        static updateActivity(arg0: $Warden): void;
        static setDigCooldown(arg0: $LivingEntity): void;
        static setDisturbanceLocation(arg0: $Warden, arg1: $BlockPos_): void;
        static DIGGING_COOLDOWN: number;
        static ROAR_DURATION: number;
        static EMERGE_DURATION: number;
        constructor();
        static set digCooldown(value: $LivingEntity);
    }
    export class $WardenSpawnTracker {
        getWarningLevel(): number;
        setWarningLevel(arg0: number): void;
        static tryWarn(arg0: $ServerLevel, arg1: $BlockPos_, arg2: $ServerPlayer): $OptionalInt;
        tick(): void;
        reset(): void;
        static CODEC: $Codec<$WardenSpawnTracker>;
        static MAX_WARNING_LEVEL: number;
        constructor(arg0: number, arg1: number, arg2: number);
    }
    export class $AngerLevel extends $Enum<$AngerLevel> {
        getMinimumAnger(): number;
        getAmbientSound(): $SoundEvent;
        isAngry(): boolean;
        getListeningSound(): $SoundEvent;
        static byAnger(arg0: number): $AngerLevel;
        static values(): $AngerLevel[];
        static valueOf(arg0: string): $AngerLevel;
        static CALM: $AngerLevel;
        static AGITATED: $AngerLevel;
        static ANGRY: $AngerLevel;
        get minimumAnger(): number;
        get ambientSound(): $SoundEvent;
        get angry(): boolean;
        get listeningSound(): $SoundEvent;
    }
    /**
     * Values that may be interpreted as {@link $AngerLevel}.
     */
    export type $AngerLevel_ = "calm" | "agitated" | "angry";
    export class $Warden extends $Monster implements $VibrationSystem {
        static createAttributes(): $AttributeSupplier$Builder;
        getDefaultDimensions(arg0: $Pose_): $EntityDimensions;
        getClientAngerLevel(): number;
        getVibrationUser(): $VibrationSystem$User;
        getVibrationData(): $VibrationSystem$Data;
        static applyDarknessAround(arg0: $ServerLevel, arg1: $Vec3_, arg2: $Entity, arg3: number): void;
        setAttackTarget(arg0: $LivingEntity): void;
        canTargetEntity(arg0: $Entity): boolean;
        getAngerLevel(): $AngerLevel;
        getTendrilAnimation(arg0: number): number;
        getHeartAnimation(arg0: number): number;
        clearAnger(arg0: $Entity): void;
        increaseAngerAt(arg0: $Entity): void;
        increaseAngerAt(arg0: $Entity, arg1: number, arg2: boolean): void;
        getEntityAngryAt(): ($LivingEntity) | undefined;
        getAngerManagement(): $AngerManagement;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        static MAX_WEARING_ARMOR_CHANCE: number;
        lastHurtByPlayerTime: number;
        static PRESERVE_ITEM_DROP_CHANCE_THRESHOLD: number;
        static DEFAULT_BASE_GRAVITY: number;
        xRot: number;
        hasImpulse: boolean;
        sonicBoomAnimationState: $AnimationState;
        static USE_ITEM_INTERVAL: number;
        static MAX_PICKUP_LOOT_CHANCE: number;
        lootTable: $ResourceKey<$LootTable>;
        yHeadRot: number;
        noPhysics: boolean;
        yo: number;
        yBodyRotO: number;
        removalReason: $Entity$RemovalReason;
        zza: number;
        goalSelector: $GoalSelector;
        handDropChances: number[];
        swingingArm: $InteractionHand;
        static ID_TAG: string;
        armorDropChances: number[];
        persistenceRequired: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        diggingAnimationState: $AnimationState;
        walkDist: number;
        lastHurt: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        yya: number;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        hurtDuration: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        dead: boolean;
        verticalCollision: boolean;
        verticalCollisionBelow: boolean;
        static DEFAULT_BABY_SCALE: number;
        static ATTRIBUTES_FIELD: string;
        static UPDATE_GOAL_SELECTOR_EVERY_N_TICKS: number;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        flyDist: number;
        sniffAnimationState: $AnimationState;
        static PASSENGERS_TAG: string;
        wasOnFire: boolean;
        attackAnim: number;
        emergeAnimationState: $AnimationState;
        zOld: number;
        timeOffs: number;
        wasTouchingWater: boolean;
        activeEffects: $Map<$Holder<$MobEffect>, $MobEffectInstance>;
        rotA: number;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        castingSpell: $SpellData;
        static DEFAULT_EQUIPMENT_DROP_CHANCE: number;
        static ARMOR_SLOT_OFFSET: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        static MAX_ENCHANTED_ARMOR_CHANCE: number;
        static MAX_ENCHANTED_WEAPON_CHANCE: number;
        hasUsedSingleAttack: boolean;
        lastHurtByPlayer: $Player;
        asbTickCount: number;
        static BOARDING_COOLDOWN: number;
        static PRESERVE_ITEM_DROP_CHANCE: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        level: $Level;
        ambientSoundTime: number;
        yRot: number;
        moveDist: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        attackAnimationState: $AnimationState;
        targetSelector: $GoalSelector;
        lookControl: $LookControl;
        drinkTime: number;
        create_diesel_generators$turretPos: $BlockPos;
        xOld: number;
        wasInPowderSnow: boolean;
        hurtTime: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        deathTime: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        jumping: boolean;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        roarAnimationState: $AnimationState;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        spells: $HashMap<any, any>;
        lastDamageStamp: number;
        levelCallback: $EntityInLevelCallback;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        removeArrowTime: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        target: $LivingEntity;
        yBodyRot: number;
        blocksBuilding: boolean;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        invulnerableDuration: number;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        effectsDirty: boolean;
        constructor(arg0: $EntityType_<$Monster>, arg1: $Level_);
        get clientAngerLevel(): number;
        get vibrationUser(): $VibrationSystem$User;
        get vibrationData(): $VibrationSystem$Data;
        set attackTarget(value: $LivingEntity);
        get angerLevel(): $AngerLevel;
        get entityAngryAt(): ($LivingEntity) | undefined;
        get angerManagement(): $AngerManagement;
    }
    export class $AngerManagement {
        static codec(arg0: $Predicate_<$Entity>): $Codec<$AngerManagement>;
        getActiveAnger(arg0: $Entity): number;
        clearAnger(arg0: $Entity): void;
        increaseAnger(arg0: $Entity, arg1: number): number;
        getActiveEntity(): ($LivingEntity) | undefined;
        tick(arg0: $ServerLevel, arg1: $Predicate_<$Entity>): void;
        constructor(arg0: $Predicate_<$Entity>, arg1: $List_<$Pair<$UUID_, number>>);
        get activeEntity(): ($LivingEntity) | undefined;
    }
    export class $AngerManagement$Sorter extends $Record implements $Comparator<$Entity> {
        reversed(): $Comparator<$Entity>;
        thenComparing<U extends $Comparable<U>>(arg0: $Function_<$Entity, U>): $Comparator<$Entity>;
        thenComparing(arg0: $Comparator<$Entity>): $Comparator<$Entity>;
        thenComparing<U>(arg0: $Function_<$Entity, U>, arg1: $Comparator<U>): $Comparator<$Entity>;
        thenComparingInt(arg0: $ToIntFunction_<$Entity>): $Comparator<$Entity>;
        thenComparingLong(arg0: $ToLongFunction_<$Entity>): $Comparator<$Entity>;
        thenComparingDouble(arg0: $ToDoubleFunction_<$Entity>): $Comparator<$Entity>;
    }
    /**
     * Values that may be interpreted as {@link $AngerManagement$Sorter}.
     */
    export type $AngerManagement$Sorter_ = { angerManagement?: $AngerManagement,  } | [angerManagement?: $AngerManagement, ];
}
