import { $FiguraVector, $FiguraVec2, $FiguraVec4, $FiguraVec3 } from "@package/org/figuramc/figura/math/vector";
import { $Object } from "@package/java/lang";
import { $Vec3_ } from "@package/net/minecraft/world/phys";
import { $Matrix4f, $Matrix3f, $Matrix4d } from "@package/org/joml";

declare module "@package/org/figuramc/figura/math/matrix" {
    export class $FiguraMat2 extends $FiguraMatrix<$FiguraMat2, $FiguraVec2> {
        getRow(row: number): $FiguraVec2;
        augmented(): $FiguraMat3;
        __add(mat: $FiguraMat2): $FiguraMat2;
        __sub(mat: $FiguraMat2): $FiguraMat2;
        __mul(o: $Object): $Object;
        __eq(o: $Object): boolean;
        __len(): number;
        __tostring(): string;
        __index(string: string): $Object;
        __newindex(string: string, value: $Object): void;
        rightMultiply(o: $FiguraMat2): $FiguraMat2;
        invert(): $FiguraMat2;
        resetIdentity(): void;
        transposed(): $FiguraMat2;
        applyDir(x: number): number;
        multiply(o: $FiguraMat2): $FiguraMat2;
        rotate(degrees: number): $FiguraMat2;
        sub(o: $FiguraMat2): $FiguraMat2;
        inverted(): $FiguraMat2;
        equals(o: $FiguraMat2): boolean;
        scale(vec: $FiguraVec2): $FiguraMat2;
        scale(x: $Object, y: number): $FiguraMat2;
        scale(x: number, y: number): $FiguraMat2;
        add(o: $FiguraMat2): $FiguraMat2;
        apply(x: number): number;
        apply(vec: $FiguraVec2): number;
        static of(n11: number, n21: number, n12: number, n22: number): $FiguraMat2;
        static of(): $FiguraMat2;
        set(n11: number, n21: number, n12: number, n22: number): $FiguraMat2;
        set(o: $FiguraMat2): $FiguraMat2;
        v21: number;
        v12: number;
        v11: number;
        v22: number;
        constructor();
    }
    export class $FiguraMat3 extends $FiguraMatrix<$FiguraMat3, $FiguraVec3> {
        translate(amount: $FiguraVec2): $FiguraMat3;
        translate(x: number, y: number): $FiguraMat3;
        translate(x: $Object, y: number): $FiguraMat3;
        rotateZYX(vec: $FiguraVec3): void;
        rotateZYX(x: number, y: number, z: number): void;
        rotateX(degrees: number): $FiguraMat3;
        rotateY(degrees: number): $FiguraMat3;
        rotateZ(degrees: number): $FiguraMat3;
        getRow(row: number): $FiguraVec3;
        toMatrix3f(): $Matrix3f;
        augmented(): $FiguraMat4;
        __add(mat: $FiguraMat3): $FiguraMat3;
        __sub(mat: $FiguraMat3): $FiguraMat3;
        __mul(o: $Object): $Object;
        __eq(o: $Object): boolean;
        __len(): number;
        __tostring(): string;
        __index(string: string): $Object;
        __newindex(string: string, value: $Object): void;
        rightMultiply(o: $FiguraMat3): $FiguraMat3;
        copyDataTo(vanillaMatrix: $Matrix3f): void;
        resetIdentity(): void;
        applyDir(x: $Object, y: number, z: number): $FiguraVec2;
        deaugmented(): $FiguraMat2;
        multiply(o: $FiguraMat3): $FiguraMat3;
        rotate(x: $Object, y: number, z: number): $FiguraMat3;
        sub(o: $FiguraMat3): $FiguraMat3;
        inverted(): $FiguraMat3;
        equals(o: $FiguraMat3): boolean;
        scale(x: $Object, y: number, z: number): $FiguraMat3;
        scale(x: number, y: number, z: number): $FiguraMat3;
        scale(vec: $FiguraVec3): $FiguraMat3;
        add(o: $FiguraMat3): $FiguraMat3;
        apply(x: $Object, y: number): $FiguraVec2;
        apply(vec: $FiguraVec3): $FiguraVec2;
        static of(): $FiguraMat3;
        static of(n11: number, n21: number, n31: number, n12: number, n22: number, n32: number, n13: number, n23: number, n33: number): $FiguraMat3;
        set(mat: $Matrix3f): $FiguraMat3;
        set(o: $FiguraMat3): $FiguraMat3;
        set(n11: number, n21: number, n31: number, n12: number, n22: number, n32: number, n13: number, n23: number, n33: number): $FiguraMat3;
        v21: number;
        v32: number;
        v31: number;
        v12: number;
        v23: number;
        v11: number;
        v22: number;
        v33: number;
        v13: number;
        constructor();
    }
    export class $FiguraMat4 extends $FiguraMatrix<$FiguraMat4, $FiguraVec4> {
        translate(x: number, y: number, z: number): $FiguraMat4;
        translate(amount: $FiguraVec3): $FiguraMat4;
        translate(amount: $Vec3_): $FiguraMat4;
        translate(x: $Object, y: number, z: number): $FiguraMat4;
        rotateZYX(vec: $FiguraVec3): void;
        rotateZYX(x: number, y: number, z: number): void;
        rotateX(degrees: number): $FiguraMat4;
        rotateY(degrees: number): $FiguraMat4;
        rotateZ(degrees: number): $FiguraMat4;
        getRow(row: number): $FiguraVec4;
        toMatrix4f(): $Matrix4f;
        __add(mat: $FiguraMat4): $FiguraMat4;
        __sub(mat: $FiguraMat4): $FiguraMat4;
        __mul(o: $Object): $Object;
        __eq(o: $Object): boolean;
        __len(): number;
        __tostring(): string;
        __index(string: string): $Object;
        __newindex(string: string, value: $Object): void;
        rightMultiply(o: $FiguraMat4): $FiguraMat4;
        copyDataTo(vanillaMatrix: $Matrix4f): void;
        transpose(): $FiguraMat4;
        invert(): $FiguraMat4;
        translateFirst(x: number, y: number, z: number): $FiguraMat4;
        resetIdentity(): void;
        applyDir(x: $Object, y: number, z: number): $FiguraVec3;
        deaugmented(): $FiguraMat3;
        multiply(o: $FiguraMat4): $FiguraMat4;
        rotate(x: $Object, y: number, z: number): $FiguraMat4;
        sub(o: $FiguraMat4): $FiguraMat4;
        equals(o: $FiguraMat4): boolean;
        scale(x: $Object, y: number, z: number): $FiguraMat4;
        scale(vec: $FiguraVec3): $FiguraMat4;
        scale(x: number, y: number, z: number): $FiguraMat4;
        add(o: $FiguraMat4): $FiguraMat4;
        apply(x: $Object, y: number, z: number): $FiguraVec3;
        apply(vec: $FiguraVec4): $FiguraVec3;
        static of(n11: number, n21: number, n31: number, n41: number, n12: number, n22: number, n32: number, n42: number, n13: number, n23: number, n33: number, n43: number, n14: number, n24: number, n34: number, n44: number): $FiguraMat4;
        static of(): $FiguraMat4;
        set(mat: $Matrix4f): $FiguraMat4;
        set(o: $FiguraMat4): $FiguraMat4;
        set(n11: number, n21: number, n31: number, n41: number, n12: number, n22: number, n32: number, n42: number, n13: number, n23: number, n33: number, n43: number, n14: number, n24: number, n34: number, n44: number): $FiguraMat4;
        set(mat: $Matrix4d): $FiguraMat4;
        v41: number;
        v21: number;
        v32: number;
        v43: number;
        v31: number;
        v42: number;
        v12: number;
        v23: number;
        v34: number;
        v11: number;
        v22: number;
        v33: number;
        v44: number;
        v14: number;
        v13: number;
        v24: number;
        constructor();
    }
    export class $FiguraMatrix<T extends $FiguraMatrix<T, V>, V extends $FiguraVector<V, T>> {
        getRow(arg0: number): V;
        det(): number;
        rightMultiply(arg0: T): T;
        transpose(): T;
        invert(): T;
        transposed(): T;
        times(vec: V): V;
        times(o: T): T;
        rows(): number;
        plus(o: T): T;
        minus(o: T): T;
        multiply(arg0: T): T;
        sub(arg0: T): T;
        getColumn(arg0: number): V;
        cols(): number;
        inverted(): T;
        reset(): T;
        equals(arg0: T): boolean;
        add(arg0: T): T;
        set(arg0: T): T;
        copy(): T;
    }
}
