import { $Codec } from "@package/com/mojang/serialization";
import { $HashMap } from "@package/java/util";

declare module "@package/team/lodestar/lodestone/systems/easing" {
    export class $Easing {
        clamped(arg0: number, arg1: number, arg2: number, arg3: number): number;
        clamped(arg0: number, arg1: number, arg2: number): number;
        clamped(arg0: number, arg1: number, arg2: number): number;
        clamped(arg0: number, arg1: number, arg2: number, arg3: number): number;
        ease(arg0: number, arg1: number, arg2: number): number;
        ease(arg0: number, arg1: number, arg2: number, arg3: number): number;
        ease(arg0: number, arg1: number, arg2: number): number;
        ease(arg0: number, arg1: number, arg2: number, arg3: number): number;
        static valueOf(arg0: string): $Easing;
        static CUBIC_IN_OUT: $Easing;
        static BOUNCE_IN: $Easing;
        static QUAD_IN: $Easing;
        static ELASTIC_IN: $Easing$Elastic;
        static QUINTIC_IN_OUT: $Easing;
        static SINE_OUT: $Easing;
        static QUARTIC_OUT: $Easing;
        static QUINTIC_IN: $Easing;
        static QUARTIC_IN_OUT: $Easing;
        static EXPO_IN: $Easing;
        static BOUNCE_IN_OUT: $Easing;
        static CIRC_OUT: $Easing;
        static BACK_IN_OUT: $Easing$Back;
        static SINE_IN_OUT: $Easing;
        static CODEC: $Codec<$Easing>;
        static CIRC_IN_OUT: $Easing;
        static EASINGS: $HashMap<string, $Easing>;
        static QUAD_IN_OUT: $Easing;
        static BACK_IN: $Easing$Back;
        static ELASTIC_OUT: $Easing$Elastic;
        static QUINTIC_OUT: $Easing;
        static ELASTIC_IN_OUT: $Easing$Elastic;
        static CUBIC_OUT: $Easing;
        static QUAD_OUT: $Easing;
        static BACK_OUT: $Easing$Back;
        static BOUNCE_OUT: $Easing;
        static SINE_IN: $Easing;
        static QUARTIC_IN: $Easing;
        name: string;
        static EXPO_IN_OUT: $Easing;
        static CIRC_IN: $Easing;
        static LINEAR: $Easing;
        static CUBIC_IN: $Easing;
        static EXPO_OUT: $Easing;
        constructor(arg0: string);
    }
    export class $Easing$Back extends $Easing {
        setOvershoot(arg0: number): void;
        getOvershoot(): number;
        static CUBIC_IN_OUT: $Easing;
        static BOUNCE_IN: $Easing;
        static QUAD_IN: $Easing;
        static ELASTIC_IN: $Easing$Elastic;
        static QUINTIC_IN_OUT: $Easing;
        static SINE_OUT: $Easing;
        static QUARTIC_OUT: $Easing;
        static QUINTIC_IN: $Easing;
        static QUARTIC_IN_OUT: $Easing;
        static EXPO_IN: $Easing;
        static BOUNCE_IN_OUT: $Easing;
        static CIRC_OUT: $Easing;
        static BACK_IN_OUT: $Easing$Back;
        static SINE_IN_OUT: $Easing;
        static CODEC: $Codec<$Easing>;
        static CIRC_IN_OUT: $Easing;
        static EASINGS: $HashMap<string, $Easing>;
        static QUAD_IN_OUT: $Easing;
        static BACK_IN: $Easing$Back;
        static ELASTIC_OUT: $Easing$Elastic;
        static QUINTIC_OUT: $Easing;
        static ELASTIC_IN_OUT: $Easing$Elastic;
        static CUBIC_OUT: $Easing;
        static QUAD_OUT: $Easing;
        static BACK_OUT: $Easing$Back;
        static BOUNCE_OUT: $Easing;
        static SINE_IN: $Easing;
        static DEFAULT_OVERSHOOT: number;
        static QUARTIC_IN: $Easing;
        name: string;
        static EXPO_IN_OUT: $Easing;
        static CIRC_IN: $Easing;
        static LINEAR: $Easing;
        static CUBIC_IN: $Easing;
        static EXPO_OUT: $Easing;
        constructor(arg0: string, arg1: number);
        constructor(arg0: string);
    }
    export class $Easing$Elastic extends $Easing {
        setAmplitude(arg0: number): void;
        getPeriod(): number;
        getAmplitude(): number;
        setPeriod(arg0: number): void;
        static CUBIC_IN_OUT: $Easing;
        static BOUNCE_IN: $Easing;
        static QUAD_IN: $Easing;
        static ELASTIC_IN: $Easing$Elastic;
        static QUINTIC_IN_OUT: $Easing;
        static SINE_OUT: $Easing;
        static QUARTIC_OUT: $Easing;
        static QUINTIC_IN: $Easing;
        static QUARTIC_IN_OUT: $Easing;
        static EXPO_IN: $Easing;
        static BOUNCE_IN_OUT: $Easing;
        static CIRC_OUT: $Easing;
        static BACK_IN_OUT: $Easing$Back;
        static SINE_IN_OUT: $Easing;
        static CODEC: $Codec<$Easing>;
        static CIRC_IN_OUT: $Easing;
        static EASINGS: $HashMap<string, $Easing>;
        static QUAD_IN_OUT: $Easing;
        static BACK_IN: $Easing$Back;
        static ELASTIC_OUT: $Easing$Elastic;
        static QUINTIC_OUT: $Easing;
        static ELASTIC_IN_OUT: $Easing$Elastic;
        static CUBIC_OUT: $Easing;
        static QUAD_OUT: $Easing;
        static BACK_OUT: $Easing$Back;
        static BOUNCE_OUT: $Easing;
        static SINE_IN: $Easing;
        static QUARTIC_IN: $Easing;
        name: string;
        static EXPO_IN_OUT: $Easing;
        static CIRC_IN: $Easing;
        static LINEAR: $Easing;
        static CUBIC_IN: $Easing;
        static EXPO_OUT: $Easing;
        constructor(arg0: string);
        constructor(arg0: string, arg1: number, arg2: number);
    }
}
