import { $RecipeUpdateListener, $AbstractFurnaceRecipeBookComponent, $RecipeBookComponent } from "@package/net/minecraft/client/gui/screens/recipebook";
import { $LivingEntity } from "@package/net/minecraft/world/entity";
import { $IAntiquable } from "@package/net/mehvahdjukaar/supplementaries/common/block";
import { $CallbackInfo, $CallbackInfoReturnable } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $Minecraft } from "@package/net/minecraft/client";
import { $FeatureFlagSet } from "@package/net/minecraft/world/flag";
import { $AccessorSmithingScreen } from "@package/com/illusivesoulworks/polymorph/mixin/core";
import { $FormattedCharSequence_, $RandomSource } from "@package/net/minecraft/util";
import { $SimpleContainer, $InteractionHand_, $Container } from "@package/net/minecraft/world";
import { $AbstractContainerScreenAccessor as $AbstractContainerScreenAccessor$1 } from "@package/io/wispforest/accessories/mixin/client";
import { $HandledScreenAccessor } from "@package/io/wispforest/owo/mixin/ui/layers";
import { $CreativeInventoryScreenAccessor } from "@package/io/wispforest/owo/mixin/itemgroup";
import { $HorseInventoryMenu, $ChestMenu, $FurnaceMenu, $LecternMenu, $ClickType_, $BeaconMenu, $CartographyTableMenu, $StonecutterMenu, $AnvilMenu, $Slot, $ShulkerBoxMenu, $ItemCombinerMenu, $EnchantmentMenu, $CrafterMenu, $CraftingMenu, $SmokerMenu, $BlastFurnaceMenu, $MerchantMenu, $SmithingMenu, $HopperMenu, $GrindstoneMenu, $DispenserMenu, $AbstractContainerMenu, $BrewingStandMenu, $AbstractFurnaceMenu, $InventoryMenu, $LoomMenu, $ContainerListener } from "@package/net/minecraft/world/inventory";
import { $CreativeModeInventoryScreenAccessor as $CreativeModeInventoryScreenAccessor$1 } from "@package/com/blackgear/vanillabackport/core/mixin/access";
import { $CreativeModeTab, $CreativeModeTab_, $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $MutableComponent, $Component_, $FormattedText, $MutableComponent_, $Style, $Component } from "@package/net/minecraft/network/chat";
import { $ContainerScreenLockTooltip, $ContainerScreenDrawTooltip } from "@package/com/misterpemodder/shulkerboxtooltip/impl/hook";
import { $Player, $Inventory } from "@package/net/minecraft/world/entity/player";
import { $CreativeTabsScreenPage } from "@package/net/neoforged/neoforge/client/gui";
import { $ISubTabLocation } from "@package/de/dafuqs/fractal/interfaces";
import { $CreativeModeInventoryScreenAccessor } from "@package/de/dafuqs/fractal/mixin/client";
import { $AtomicBoolean } from "@package/java/util/concurrent/atomic";
import { $ContainerScreenExtension } from "@package/io/wispforest/accessories/pond";
import { $Vector3f, $Quaternionf } from "@package/org/joml";
import { $AbstractContainerScreenAccessor as $AbstractContainerScreenAccessor$2 } from "@package/yalter/mousetweaks/mixin";
import { $Random, $Map, $List, $List_, $Optional } from "@package/java/util";
import { $Event } from "@package/net/fabricmc/fabric/api/event";
import { $AbstractHorse } from "@package/net/minecraft/world/entity/animal/horse";
import { $AbstractContainerScreenAccessor as $AbstractContainerScreenAccessor$3 } from "@package/net/blay09/mods/balm/mixin";
import { $AbstractContainerScreenAccessor } from "@package/it/hurts/octostudios/immersiveui/mixin";
import { $NonNullList } from "@package/net/minecraft/core";
import { $OwoCreativeInventoryScreenExtensions } from "@package/io/wispforest/owo/util/pond";
import { $DrawsOnLeft } from "@package/dev/shadowsoffire/placebo/util";
import { $Record } from "@package/java/lang";
import { $CreativeScreen } from "@package/org/dawnoftime/dawnoftime/mixin/api";
import { $ExtraScreenData } from "@package/it/hurts/octostudios/immersiveui/compat";
import { $FabricCreativeInventoryScreen } from "@package/net/fabricmc/fabric/api/client/itemgroup/v1";
import { $BaseCommandBlock } from "@package/net/minecraft/world/level";
import { $ComponentUtils$CreativeScreenExtension } from "@package/io/wispforest/accessories/client/gui/components";
import { $NarratableEntry } from "@package/net/minecraft/client/gui/narration";
import { $LocalPlayer } from "@package/net/minecraft/client/player";
import { $EditBox, $AbstractButton, $Renderable, $Button, $Button$OnPress_ } from "@package/net/minecraft/client/gui/components";
import { $SlotWrapperAccessor, $AbstractContainerScreenAccessor as $AbstractContainerScreenAccessor$4, $CreativeModeInventoryScreenAccessor as $CreativeModeInventoryScreenAccessor$3 } from "@package/net/blay09/mods/inventoryessentials/mixin";
import { $Screen, $Screen$DeferredTooltipRendering } from "@package/net/minecraft/client/gui/screens";
import { $ResourceLocation, $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $RenderInfo, $MouseInfo } from "@package/it/hurts/octostudios/immersiveui/client";
import { $ApothEnchantmentScreen$SuperRender } from "@package/dev/shadowsoffire/apothic_enchanting/table";
import { $AbstractContainerScreenAccessor as $AbstractContainerScreenAccessor$5 } from "@package/thelm/jeidrawables/mixin";
import { $Font, $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $SignBlockEntity, $StructureBlockEntity, $JigsawBlockEntity, $CommandBlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $CreativeModeInventoryScreenAccessor as $CreativeModeInventoryScreenAccessor$2 } from "@package/dev/simulated_team/simulated/mixin/accessor";
import { $AccessorCustomCreativeSlot } from "@package/org/violetmoon/quark/mixin/mixins/client/accessor";
export * as tooltip from "@package/net/minecraft/client/gui/screens/inventory/tooltip";

declare module "@package/net/minecraft/client/gui/screens/inventory" {
    export class $SmithingScreen extends $ItemCombinerScreen<$SmithingMenu> implements $AccessorSmithingScreen {
        containerTick(): void;
        callUpdateArmorStandPreview(arg0: $ItemStack_): void;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        static ARMOR_STAND_TRANSLATION: $Vector3f;
        snapbackStartY: number;
        static EMPTY_SLOT_SMITHING_TEMPLATES: $List<$ResourceLocation>;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static ARMOR_STAND_ANGLE: $Quaternionf;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        static MISSING_TEMPLATE_TOOLTIP: $Component;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        static ERROR_TOOLTIP: $Component;
        topPos: number;
        font: $Font;
        constructor(arg0: $SmithingMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $EnchantmentScreen extends $AbstractContainerScreen<$EnchantmentMenu> implements $ApothEnchantmentScreen$SuperRender {
        containerTick(): void;
        renderBook(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number): void;
        tickBook(): void;
        handler$bjk000$immersiveui$onMouseClicked(d: number, e: number, i: number, ci: $CallbackInfoReturnable<any>): void;
        apoth_superRender(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number): void;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        oFlip: number;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        static ENCHANTMENT_SLOT_SPRITE: $ResourceLocation;
        title: $Component;
        random: $RandomSource;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        flipT: number;
        oOpen: number;
        snapbackItem: $ItemStack;
        static ENCHANTMENT_SLOT_DISABLED_SPRITE: $ResourceLocation;
        flip: number;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        flipA: number;
        last: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        static ENABLED_LEVEL_SPRITES: $ResourceLocation[];
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static ENCHANTMENT_SLOT_HIGHLIGHTED_SPRITE: $ResourceLocation;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        static DISABLED_LEVEL_SPRITES: $ResourceLocation[];
        narratables: $List<$NarratableEntry>;
        width: number;
        time: number;
        topPos: number;
        static ENCHANTING_TABLE_LOCATION: $ResourceLocation;
        open: number;
        font: $Font;
        constructor(arg0: $EnchantmentMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $BookViewScreen$BookAccess extends $Record implements $IAntiquable {
        pages(): $List<$Component>;
        getPage(arg0: number): $FormattedText;
        supplementaries$isAntique(): boolean;
        supplementaries$setAntique(hasInk: boolean): void;
        static fromItem(arg0: $ItemStack_): $BookViewScreen$BookAccess;
        getPageCount(): number;
        constructor(arg0: $List_<$Component_>);
        get pageCount(): number;
    }
    /**
     * Values that may be interpreted as {@link $BookViewScreen$BookAccess}.
     */
    export type $BookViewScreen$BookAccess_ = { pages?: $List_<$Component_>,  } | [pages?: $List_<$Component_>, ];
    export class $BeaconScreen$BeaconPowerButton extends $BeaconScreen$BeaconScreenButton {
        static UNSET_FG_COLOR: number;
        visible: boolean;
        active: boolean;
    }
    export class $CyclingSlotBackground {
        tick(arg0: $List_<$ResourceLocation_>): void;
        render(arg0: $AbstractContainerMenu, arg1: $GuiGraphics, arg2: number, arg3: number, arg4: number): void;
        constructor(arg0: number);
    }
    export class $ShulkerBoxScreen extends $AbstractContainerScreen<$ShulkerBoxMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $ShulkerBoxMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $CreativeModeInventoryScreen$SlotWrapper extends $Slot implements $SlotWrapperAccessor {
        getTarget(): $Slot;
        container: $Container;
        x: number;
        index: number;
        y: number;
        slot: number;
        target: $Slot;
        constructor(arg0: $Slot, arg1: number, arg2: number, arg3: number);
    }
    export class $CommandBlockEditScreen extends $AbstractCommandBlockEditScreen {
        updateGui(): void;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $CommandBlockEntity);
    }
    export class $BrewingStandScreen extends $AbstractContainerScreen<$BrewingStandMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $BrewingStandMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $CreativeModeInventoryScreen extends $EffectRenderingInventoryScreen<$CreativeModeInventoryScreen$ItemPickerMenu> implements $ComponentUtils$CreativeScreenExtension, $CreativeModeInventoryScreenAccessor, $ISubTabLocation, $CreativeModeInventoryScreenAccessor$1, $FabricCreativeInventoryScreen, $CreativeScreen, $CreativeModeInventoryScreenAccessor$3, $CreativeInventoryScreenAccessor, $OwoCreativeInventoryScreenExtensions {
        static handleHotbarLoadOrSave(arg0: $Minecraft, arg1: number, arg2: boolean, arg3: boolean): void;
        getTooltipFromContainerItem(arg0: $ItemStack_): $List<$Component>;
        containerTick(): void;
        getPage(arg0: $CreativeModeTab_): number;
        getTab(): $CreativeModeTab;
        handler$jjp00b$dawnoftimebuilder$init(arg0: $CallbackInfo): void;
        wrapWithCondition$dpe000$fractal$wrapParentTitle(arg0: $GuiGraphics, arg1: $Font, arg2: $Component_, arg3: number, arg4: number, arg5: number, arg6: boolean): boolean;
        handler$dpe000$fractal$mouseClicked(arg0: number, arg1: number, arg2: number, arg3: $CallbackInfoReturnable<any>): void;
        handler$jjp000$dawnoftimebuilder$selectTab(arg0: $CreativeModeTab_, arg1: $CallbackInfo): void;
        handler$jjp000$dawnoftimebuilder$mouseScrolled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: $CallbackInfoReturnable<any>): void;
        handler$jjp006$dawnoftimebuilder$render(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number, arg4: $CallbackInfo): void;
        handler$dpe000$fractal$renderSubTabs(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number, arg4: $CallbackInfo): void;
        setCurrentPage(arg0: $CreativeTabsScreenPage): void;
        switchToPage(arg0: number): boolean;
        switchToNextPage(): boolean;
        hasAdditionalPages(): boolean;
        switchToPreviousPage(): boolean;
        getItemGroupsOnPage(arg0: number): $List<any>;
        getSelectedItemGroup(): $CreativeModeTab;
        setSelectedItemGroup(arg0: $CreativeModeTab_): boolean;
        dOTBuilder$getPage(): number;
        static getSelectedTab$fractal_$md$68cb88$2(): $CreativeModeTab;
        static getSelectedTab$vanillabackport_$md$68cb88$3(): $CreativeModeTab;
        static getSelectedTab$owo_$md$68cb88$14(): $CreativeModeTab;
        fractal$getY(): number;
        fractal$getX(): number;
        fractal$getH(): number;
        fractal$getX2(): number;
        fractal$getH2(): number;
        getPageCount(): number;
        getEvent(): $Event<any>;
        getCurrentPage(): number;
        isInventoryOpen(): boolean;
        getCONTAINER(): $SimpleContainer;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        static selectedTab: $CreativeModeTab;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        destroyItemSlot: $Slot;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $LocalPlayer, arg1: $FeatureFlagSet, arg2: boolean);
        get tab(): $CreativeModeTab;
        static get selectedTab$fractal_$md$68cb88$2(): $CreativeModeTab;
        static get selectedTab$vanillabackport_$md$68cb88$3(): $CreativeModeTab;
        static get selectedTab$owo_$md$68cb88$14(): $CreativeModeTab;
        get pageCount(): number;
        get event(): $Event<any>;
        get inventoryOpen(): boolean;
        get CONTAINER(): $SimpleContainer;
    }
    export class $AbstractCommandBlockEditScreen extends $Screen {
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor();
    }
    export class $EffectRenderingInventoryScreen<T extends $AbstractContainerMenu> extends $AbstractContainerScreen<T> {
        canSeeEffects(): boolean;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: T, arg1: $Inventory, arg2: $Component_);
    }
    export class $DispenserScreen extends $AbstractContainerScreen<$DispenserMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $DispenserMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $CreativeModeInventoryScreen$CustomCreativeSlot extends $Slot implements $AccessorCustomCreativeSlot {
        container: $Container;
        x: number;
        index: number;
        y: number;
        slot: number;
    }
    export class $BookViewScreen extends $Screen {
        getClickedComponentStyleAt(arg0: number, arg1: number): $Style;
        setBookAccess(arg0: $BookViewScreen$BookAccess_): void;
        redirect$hmp000$figura$render(graphics: $GuiGraphics, font: $Font, formattedCharSequence: $FormattedCharSequence_, x: number, y: number, color: number, shadowed: boolean): number;
        modify$bhm000$supplementaries$supp$setTatteredBookTexture(resourceLocation: $ResourceLocation_): $ResourceLocation;
        setPage(arg0: number): boolean;
        static BOOK_LOCATION: $ResourceLocation;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        static PAGE_TEXT_X_OFFSET: number;
        static PAGE_TEXT_Y_OFFSET: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static PAGE_INDICATOR_TEXT_Y_OFFSET: number;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        static EMPTY_ACCESS: $BookViewScreen$BookAccess;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor();
        constructor(arg0: $BookViewScreen$BookAccess_);
        set bookAccess(value: $BookViewScreen$BookAccess_);
        set page(value: number);
    }
    export class $BeaconScreen extends $AbstractContainerScreen<$BeaconMenu> {
        containerTick(): void;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $BeaconMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $ContainerScreen extends $AbstractContainerScreen<$ChestMenu> implements $MenuAccess<$ChestMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $ChestMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $BeaconScreen$BeaconCancelButton extends $BeaconScreen$BeaconSpriteScreenButton {
        static UNSET_FG_COLOR: number;
        visible: boolean;
        active: boolean;
    }
    export class $InventoryScreen extends $EffectRenderingInventoryScreen<$InventoryMenu> implements $RecipeUpdateListener {
        containerTick(): void;
        handler$jjk000$patchouli$onGuiInitPost(arg0: $CallbackInfo): void;
        static renderEntityInInventoryFollowsMouse(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: $LivingEntity): void;
        static renderEntityInInventoryFollowsAngle(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: $LivingEntity): void;
        static renderEntityInInventory(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number, arg4: $Vector3f, arg5: $Quaternionf, arg6: $Quaternionf, arg7: $LivingEntity): void;
        recipesUpdated(): void;
        getRecipeBookComponent(): $RecipeBookComponent;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        yMouse: number;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        xMouse: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $Player);
        get recipeBookComponent(): $RecipeBookComponent;
    }
    export class $HopperScreen extends $AbstractContainerScreen<$HopperMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $HopperMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $BookEditScreen$DisplayCache {
    }
    export class $FurnaceScreen extends $AbstractFurnaceScreen<$FurnaceMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        shouldBurst: $AtomicBoolean;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        recipeBookComponent: $AbstractFurnaceRecipeBookComponent;
        topPos: number;
        font: $Font;
        constructor(arg0: $FurnaceMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $MerchantScreen$TradeOfferButton extends $Button {
        visible: boolean;
        active: boolean;
        static DEFAULT_WIDTH: number;
        static UNSET_FG_COLOR: number;
        static DEFAULT_HEIGHT: number;
        static SMALL_WIDTH: number;
        static BIG_WIDTH: number;
        static DEFAULT_SPACING: number;
    }
    export class $CartographyTableScreen extends $AbstractContainerScreen<$CartographyTableMenu> {
        localvar$bho000$supplementaries$supp$setAntiqueInk(stack: $ItemStack_): $ItemStack;
        handler$bho000$supplementaries$supp$animateSlots(graphics: $GuiGraphics, ticks: number, mouseX: number, mouseY: number, ci: $CallbackInfo): void;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $CartographyTableMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $LoomScreen extends $AbstractContainerScreen<$LoomMenu> {
        modifyExpressionValue$bii000$supplementaries$supp$swapFlag(original: $ItemStack_): $ItemStack;
        handler$bii000$supplementaries$supp$renderFlags(graphics: $GuiGraphics, ticks: number, mouseX: number, mouseY: number, ci: $CallbackInfo): void;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $LoomMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $AbstractFurnaceScreen<T extends $AbstractFurnaceMenu> extends $AbstractContainerScreen<T> implements $RecipeUpdateListener {
        containerTick(): void;
        recipesUpdated(): void;
        getRecipeBookComponent(): $RecipeBookComponent;
        handler$bjg000$immersiveui$render(guiGraphics: $GuiGraphics, i: number, j: number, f: number, ci: $CallbackInfo): void;
        init(): void;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        shouldBurst: $AtomicBoolean;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        recipeBookComponent: $AbstractFurnaceRecipeBookComponent;
        topPos: number;
        font: $Font;
        constructor(arg0: T, arg1: $AbstractFurnaceRecipeBookComponent, arg2: $Inventory, arg3: $Component_, arg4: $ResourceLocation_, arg5: $ResourceLocation_, arg6: $ResourceLocation_);
    }
    export class $SmokerScreen extends $AbstractFurnaceScreen<$SmokerMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        shouldBurst: $AtomicBoolean;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        recipeBookComponent: $AbstractFurnaceRecipeBookComponent;
        topPos: number;
        font: $Font;
        constructor(arg0: $SmokerMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $EnchantmentNames {
        initSeed(arg0: number): void;
        getRandomName(arg0: $Font, arg1: number): $FormattedText;
        static getInstance(): $EnchantmentNames;
        static get instance(): $EnchantmentNames;
    }
    export class $AbstractContainerScreen<T extends $AbstractContainerMenu> extends $Screen implements $MenuAccess<T>, $AbstractContainerScreenAccessor, $ExtraScreenData, $AbstractContainerScreenAccessor$1, $ContainerScreenExtension, $AbstractContainerScreenAccessor$5, $DrawsOnLeft, $ContainerScreenLockTooltip, $ContainerScreenDrawTooltip, $AbstractContainerScreenAccessor$3, $AbstractContainerScreenAccessor$2, $CreativeModeInventoryScreenAccessor$2, $AbstractContainerScreenAccessor$4, $HandledScreenAccessor {
        getGuiTop(): number;
        getGuiLeft(): number;
        getMenu(): T;
        getRandom(): $Random;
        handler$bjf000$immersiveui$fixHovering(guiGraphics: $GuiGraphics, mouseX: number, mouseY: number, partialTick: number, ci: $CallbackInfo, i: number, j: number, k: number, slot: $Slot): void;
        renderSlot(arg0: $GuiGraphics, arg1: $Slot): void;
        static renderSlotHighlight(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number, arg4: number): void;
        static renderSlotHighlight(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number): void;
        renderFloatingItem(arg0: $GuiGraphics, arg1: $ItemStack_, arg2: number, arg3: number, arg4: string): void;
        handler$bjf000$immersiveui$resetOldMouse2(guiGraphics: $GuiGraphics, mouseX: number, mouseY: number, partialTick: number, ci: $CallbackInfo): void;
        handler$bjf000$immersiveui$resetOldMouse(guiGraphics: $GuiGraphics, mouseX: number, mouseY: number, partialTick: number, ci: $CallbackInfo): void;
        handler$bjf000$immersiveui$renderBg(guiGraphics: $GuiGraphics, i: number, j: number, f: number, ci: $CallbackInfo): void;
        getSlotColor(arg0: number): number;
        handler$bjf000$immersiveui$renderFunkyItem(guiGraphics: $GuiGraphics, itemStack: $ItemStack_, i: number, j: number, string: string, ci: $CallbackInfo): void;
        isHovering(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
        isHovering(arg0: $Slot, arg1: number, arg2: number): boolean;
        slotClicked(arg0: $Slot, arg1: number, arg2: number, arg3: $ClickType_): void;
        recalculateQuickCraftRemaining(): void;
        handler$bjo000$immersiveui$renderSize(guiGraphics: $GuiGraphics, itemstack: $ItemStack_, slot: $Slot, countString: string, ci: $CallbackInfo): void;
        handler$mgg000$itemborders$renderSlotContents(graphics: $GuiGraphics, itemStack: $ItemStack_, slot: $Slot, countString: string, info: $CallbackInfo): void;
        findSlot(arg0: number, arg1: number): $Slot;
        handler$gbh000$apothic_attributes$apoth_superMouseDragged(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: $CallbackInfoReturnable<any>): void;
        clearDraggingState(): void;
        getSlotUnderMouse(): $Slot;
        getXSize(): number;
        getYSize(): number;
        getMouseInfo(): $MouseInfo;
        getRenderInfo(): $RenderInfo;
        getExpandingProgress(): $Map<any, any>;
        handler$bjf000$immersiveui$renderSize(guiGraphics: $GuiGraphics, slot: $Slot, ci: $CallbackInfo): void;
        forceRenderSlot(context: $GuiGraphics, slot: $Slot): void;
        shulkerboxtooltip$lockTooltipPosition(graphics: $GuiGraphics, font: $Font, text: $List_<any>, data: $Optional<any>, stack: $ItemStack_, x: number, y: number): void;
        shulkerboxtooltip$drawMouseoverTooltip(graphics: $GuiGraphics, font: $Font, text: $List_<any>, data: $Optional<any>, stack: $ItemStack_, x: number, y: number): void;
        isHovering_Logical(slot: $Slot, mouseX: number, mouseY: number): boolean;
        shouldRenderSlot(slot: $Slot): boolean;
        hoverStackOffset(): number;
        isHovering_Rendering(slot: $Slot, mouseX: number, mouseY: number): boolean;
        __ths(): $AbstractContainerScreen<never>;
        drawOnLeft(arg0: $GuiGraphics, arg1: $List_<$FormattedText>, arg2: number): void;
        drawOnLeft(arg0: $GuiGraphics, arg1: $List_<$FormattedText>, arg2: number, arg3: number): void;
        getHoveredSlot(): $Slot;
        accessories$getClickedSlot(): $Slot;
        accessories$getDraggingItem(): $ItemStack;
        accessories$isSplittingStack(): boolean;
        accessories$getQuickCraftingType(): number;
        accessories$recalculateQuickCraftRemaining(): void;
        accessories$leftPos(): number;
        accessories$topPos(): number;
        jeidas$leftPos(): number;
        jeidas$topPos(): number;
        getLeftPos(): number;
        getTopPos(): number;
        getImageWidth(): number;
        getImageHeight(): number;
        callIsHovering(arg0: $Slot, arg1: number, arg2: number): boolean;
        callRenderSlot(arg0: $GuiGraphics, arg1: $Slot): void;
        mousetweaks$invokeFindSlot(arg0: number, arg1: number): $Slot;
        mousetweaks$invokeSlotClicked(arg0: $Slot, arg1: number, arg2: number, arg3: $ClickType_): void;
        mousetweaks$getIsQuickCrafting(): boolean;
        mousetweaks$setIsQuickCrafting(arg0: boolean): void;
        mousetweaks$getQuickCraftingButton(): number;
        mousetweaks$setSkipNextRelease(arg0: boolean): void;
        callHasClickedOutside(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): boolean;
        owo$getRootX(): number;
        owo$getRootY(): number;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: T, arg1: $Inventory, arg2: $Component_);
        get guiTop(): number;
        get guiLeft(): number;
        get menu(): T;
        get random(): $Random;
        get slotUnderMouse(): $Slot;
        get XSize(): number;
        get YSize(): number;
        get mouseInfo(): $MouseInfo;
        get renderInfo(): $RenderInfo;
        get expandingProgress(): $Map<any, any>;
    }
    export class $CreativeInventoryListener implements $ContainerListener {
        slotChanged(arg0: $AbstractContainerMenu, arg1: number, arg2: $ItemStack_): void;
        dataChanged(arg0: $AbstractContainerMenu, arg1: number, arg2: number): void;
        constructor(arg0: $Minecraft);
    }
    export class $BlastFurnaceScreen extends $AbstractFurnaceScreen<$BlastFurnaceMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        shouldBurst: $AtomicBoolean;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        recipeBookComponent: $AbstractFurnaceRecipeBookComponent;
        topPos: number;
        font: $Font;
        constructor(arg0: $BlastFurnaceMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $CrafterScreen extends $AbstractContainerScreen<$CrafterMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $CrafterMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $HorseInventoryScreen extends $AbstractContainerScreen<$HorseInventoryMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $HorseInventoryMenu, arg1: $Inventory, arg2: $AbstractHorse, arg3: number);
    }
    export class $BeaconScreen$BeaconConfirmButton extends $BeaconScreen$BeaconSpriteScreenButton {
        static UNSET_FG_COLOR: number;
        visible: boolean;
        active: boolean;
    }
    export class $BeaconScreen$BeaconUpgradePowerButton extends $BeaconScreen$BeaconPowerButton {
        static UNSET_FG_COLOR: number;
        visible: boolean;
        active: boolean;
    }
    export class $MinecartCommandBlockEditScreen extends $AbstractCommandBlockEditScreen {
        getCommandBlock(): $BaseCommandBlock;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $BaseCommandBlock);
        get commandBlock(): $BaseCommandBlock;
    }
    export class $ItemCombinerScreen<T extends $ItemCombinerMenu> extends $AbstractContainerScreen<T> implements $ContainerListener {
        slotChanged(arg0: $AbstractContainerMenu, arg1: number, arg2: $ItemStack_): void;
        dataChanged(arg0: $AbstractContainerMenu, arg1: number, arg2: number): void;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: T, arg1: $Inventory, arg2: $Component_, arg3: $ResourceLocation_);
    }
    export class $LecternScreen extends $BookViewScreen implements $MenuAccess<$LecternMenu> {
        getMenu(): $LecternMenu;
        static BOOK_LOCATION: $ResourceLocation;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        static PAGE_TEXT_X_OFFSET: number;
        static PAGE_TEXT_Y_OFFSET: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static PAGE_INDICATOR_TEXT_Y_OFFSET: number;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        static EMPTY_ACCESS: $BookViewScreen$BookAccess;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $LecternMenu, arg1: $Inventory, arg2: $Component_);
        get menu(): $LecternMenu;
    }
    export class $SignEditScreen extends $AbstractSignEditScreen {
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        static MAGIC_TEXT_SCALE: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        static MAGIC_SCALE_NUMBER: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $SignBlockEntity, arg1: boolean, arg2: boolean);
    }
    export class $CraftingScreen extends $AbstractContainerScreen<$CraftingMenu> implements $RecipeUpdateListener {
        containerTick(): void;
        recipesUpdated(): void;
        getRecipeBookComponent(): $RecipeBookComponent;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $CraftingMenu, arg1: $Inventory, arg2: $Component_);
        get recipeBookComponent(): $RecipeBookComponent;
    }
    export class $MerchantScreen extends $AbstractContainerScreen<$MerchantMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $MerchantMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $BeaconScreen$BeaconSpriteScreenButton extends $BeaconScreen$BeaconScreenButton {
        static UNSET_FG_COLOR: number;
        visible: boolean;
        active: boolean;
    }
    export class $BookEditScreen$Pos2i {
    }
    export class $JigsawBlockEditScreen extends $Screen {
        static isValidResourceLocation(arg0: string): boolean;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $JigsawBlockEntity);
    }
    export class $BeaconScreen$BeaconScreenButton extends $AbstractButton implements $BeaconScreen$BeaconButton {
        static UNSET_FG_COLOR: number;
        visible: boolean;
        active: boolean;
    }
    export class $CreativeModeInventoryScreen$ItemPickerMenu extends $AbstractContainerMenu {
        canScroll(): boolean;
        scrollTo(arg0: number): void;
        carried: $ItemStack;
        stateId: number;
        static QUICKCRAFT_HEADER_START: number;
        remoteSlots: $NonNullList<$ItemStack>;
        lastSlots: $NonNullList<$ItemStack>;
        static QUICKCRAFT_HEADER_CONTINUE: number;
        static QUICKCRAFT_TYPE_CLONE: number;
        static QUICKCRAFT_TYPE_GREEDY: number;
        static QUICKCRAFT_HEADER_END: number;
        slots: $NonNullList<$Slot>;
        static CARRIED_SLOT_SIZE: number;
        static SLOT_CLICKED_OUTSIDE: number;
        containerId: number;
        items: $NonNullList<$ItemStack>;
        static QUICKCRAFT_TYPE_CHARITABLE: number;
        constructor(arg0: $Player);
    }
    export class $BookEditScreen$LineInfo {
        redirect$hna000$figura$test(instance: $MutableComponent_, style: $Style): $MutableComponent;
        constructor(arg0: $Style, arg1: string, arg2: number, arg3: number);
    }
    export class $BeaconScreen$BeaconButton {
    }
    export interface $BeaconScreen$BeaconButton {
    }
    /**
     * Values that may be interpreted as {@link $BeaconScreen$BeaconButton}.
     */
    export type $BeaconScreen$BeaconButton_ = (() => void);
    export class $BookEditScreen extends $Screen {
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $Player, arg1: $ItemStack_, arg2: $InteractionHand_);
    }
    export class $HangingSignEditScreen extends $AbstractSignEditScreen {
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static MAGIC_BACKGROUND_SCALE: number;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $SignBlockEntity, arg1: boolean, arg2: boolean);
    }
    export class $StonecutterScreen extends $AbstractContainerScreen<$StonecutterMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $StonecutterMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $MenuAccess<T extends $AbstractContainerMenu> {
    }
    export interface $MenuAccess<T extends $AbstractContainerMenu> {
        getMenu(): T;
        get menu(): T;
    }
    /**
     * Values that may be interpreted as {@link $MenuAccess}.
     */
    export type $MenuAccess_<T> = (() => T);
    export class $AnvilScreen extends $ItemCombinerScreen<$AnvilMenu> {
        handler$mgb001$equipmentcompare$keyPressed(i: number, j: number, k: number, info: $CallbackInfoReturnable<any>): void;
        constant$gih001$apothic_enchanting$apoth_removeLevelCap(arg0: number): number;
        modifyExpressionValue$ekf001$taxfreelevels$removeAnvilLimit(original: boolean): boolean;
        renderFg(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number): void;
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        name: $EditBox;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $AnvilMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $AbstractSignEditScreen extends $Screen {
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $SignBlockEntity, arg1: boolean, arg2: boolean, arg3: $Component_);
        constructor(arg0: $SignBlockEntity, arg1: boolean, arg2: boolean);
    }
    export class $GrindstoneScreen extends $AbstractContainerScreen<$GrindstoneMenu> {
        leftPos: number;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        clickedSlot: $Slot;
        title: $Component;
        snapbackStartY: number;
        renderables: $List<$Renderable>;
        hoveredSlot: $Slot;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        isSplittingStack: boolean;
        snapbackItem: $ItemStack;
        snapbackStartX: number;
        static INVENTORY_LOCATION: $ResourceLocation;
        snapbackTime: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        imageWidth: number;
        snapbackEnd: $Slot;
        draggingItem: $ItemStack;
        static SLOT_ITEM_BLIT_OFFSET: number;
        quickCraftingRemainder: number;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static FOOTER_SEPARATOR: $ResourceLocation;
        imageHeight: number;
        quickCraftingType: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        topPos: number;
        font: $Font;
        constructor(arg0: $GrindstoneMenu, arg1: $Inventory, arg2: $Component_);
    }
    export class $PageButton extends $Button implements $IAntiquable {
        renderWidget(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number): void;
        supplementaries$isAntique(): boolean;
        supplementaries$setAntique(hasInk: boolean): void;
        visible: boolean;
        active: boolean;
        static DEFAULT_WIDTH: number;
        static UNSET_FG_COLOR: number;
        static DEFAULT_HEIGHT: number;
        static SMALL_WIDTH: number;
        static BIG_WIDTH: number;
        static DEFAULT_SPACING: number;
        constructor(arg0: number, arg1: number, arg2: boolean, arg3: $Button$OnPress_, arg4: boolean);
    }
    export class $StructureBlockEditScreen extends $Screen {
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        narratables: $List<$NarratableEntry>;
        width: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        constructor(arg0: $StructureBlockEntity);
    }
}
