import { $Cloneable } from "@package/java/lang";
import { $ImGuiStructDestroyable, $ImGuiStruct } from "@package/imgui/binding";
export * as binding from "@package/imgui/binding";

declare module "@package/imgui" {
    export class $ImVec4 implements $Cloneable {
        times(arg0: number, arg1: number, arg2: number, arg3: number): $ImVec4;
        times(arg0: $ImVec4): $ImVec4;
        plus(arg0: number, arg1: number, arg2: number, arg3: number): $ImVec4;
        plus(arg0: $ImVec4): $ImVec4;
        minus(arg0: number, arg1: number, arg2: number, arg3: number): $ImVec4;
        minus(arg0: $ImVec4): $ImVec4;
        clone(): $ImVec4;
        set(arg0: number, arg1: number, arg2: number, arg3: number): $ImVec4;
        set(arg0: $ImVec4): $ImVec4;
        w: number;
        x: number;
        y: number;
        z: number;
        constructor();
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: $ImVec4);
    }
    export class $ImVec2 implements $Cloneable {
        times(arg0: number, arg1: number): $ImVec2;
        times(arg0: $ImVec2): $ImVec2;
        plus(arg0: number, arg1: number): $ImVec2;
        plus(arg0: $ImVec2): $ImVec2;
        minus(arg0: number, arg1: number): $ImVec2;
        minus(arg0: $ImVec2): $ImVec2;
        clone(): $ImVec2;
        set(arg0: number, arg1: number): $ImVec2;
        set(arg0: $ImVec2): $ImVec2;
        x: number;
        y: number;
        constructor();
        constructor(arg0: number, arg1: number);
        constructor(arg0: $ImVec2);
    }
    export class $ImDrawList extends $ImGuiStruct {
        pushClipRectFullScreen(): void;
        popTextureID(): void;
        getClipRectMin(arg0: $ImVec2): void;
        getClipRectMin(): $ImVec2;
        getClipRectMinX(): number;
        getClipRectMinY(): number;
        getClipRectMax(arg0: $ImVec2): void;
        getClipRectMax(): $ImVec2;
        getClipRectMaxX(): number;
        getClipRectMaxY(): number;
        addRectFilledMultiColor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): void;
        addRectFilledMultiColor(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number, arg4: number, arg5: number): void;
        addQuadFilled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): void;
        addQuadFilled(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: number): void;
        addTriangle(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: number): void;
        addTriangle(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): void;
        addTriangle(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: number, arg4: number): void;
        addTriangle(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        addTriangleFilled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        addTriangleFilled(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: number): void;
        addCircle(arg0: $ImVec2, arg1: number, arg2: number): void;
        addCircle(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        addCircle(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addCircle(arg0: $ImVec2, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addCircle(arg0: $ImVec2, arg1: number, arg2: number, arg3: number): void;
        addCircle(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addCircle(arg0: number, arg1: number, arg2: number, arg3: number): void;
        addCircle(arg0: $ImVec2, arg1: number, arg2: number, arg3: number): void;
        addCircleFilled(arg0: number, arg1: number, arg2: number, arg3: number): void;
        addCircleFilled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addCircleFilled(arg0: $ImVec2, arg1: number, arg2: number, arg3: number): void;
        addCircleFilled(arg0: $ImVec2, arg1: number, arg2: number): void;
        addNgon(arg0: $ImVec2, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addNgon(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addNgon(arg0: $ImVec2, arg1: number, arg2: number, arg3: number): void;
        addNgon(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        addNgonFilled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addNgonFilled(arg0: $ImVec2, arg1: number, arg2: number, arg3: number): void;
        addPolyline(arg0: $ImVec2[], arg1: number, arg2: number, arg3: number, arg4: number): void;
        addConvexPolyFilled(arg0: $ImVec2[], arg1: number, arg2: number): void;
        addBezierCubic(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addBezierCubic(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: number, arg5: number, arg6: number): void;
        addBezierCubic(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: number, arg5: number): void;
        addBezierCubic(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): void;
        addBezierQuadratic(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): void;
        addBezierQuadratic(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: number, arg4: number, arg5: number): void;
        addBezierQuadratic(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): void;
        addBezierQuadratic(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: number, arg4: number): void;
        addImageQuad(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): void;
        addImageQuad(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number): void;
        addImageQuad(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: $ImVec2, arg6: $ImVec2, arg7: $ImVec2): void;
        addImageQuad(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number): void;
        addImageQuad(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: number): void;
        addImageQuad(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: $ImVec2, arg6: $ImVec2, arg7: $ImVec2, arg8: $ImVec2, arg9: number): void;
        addImageQuad(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: number, arg17: number): void;
        addImageQuad(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: $ImVec2, arg6: $ImVec2, arg7: $ImVec2, arg8: $ImVec2): void;
        addImageQuad(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2): void;
        addImageQuad(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: $ImVec2): void;
        addImageQuad(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: $ImVec2, arg6: $ImVec2): void;
        addImageQuad(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addImageRounded(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number): void;
        addImageRounded(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addImageRounded(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: number, arg6: number, arg7: number): void;
        addImageRounded(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: number, arg6: number): void;
        pathClear(): void;
        pathLineTo(arg0: $ImVec2): void;
        pathLineTo(arg0: number, arg1: number): void;
        pathLineToMergeDuplicate(arg0: number, arg1: number): void;
        pathLineToMergeDuplicate(arg0: $ImVec2): void;
        pathFillConvex(arg0: number): void;
        pathStroke(arg0: number, arg1: number): void;
        pathStroke(arg0: number, arg1: number, arg2: number): void;
        pathStroke(arg0: number, arg1: number): void;
        pathStroke(arg0: number): void;
        pathArcTo(arg0: $ImVec2, arg1: number, arg2: number, arg3: number): void;
        pathArcTo(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        pathArcTo(arg0: $ImVec2, arg1: number, arg2: number, arg3: number, arg4: number): void;
        pathArcTo(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        pathArcToFast(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        pathArcToFast(arg0: $ImVec2, arg1: number, arg2: number, arg3: number): void;
        pathBezierCubicCurveTo(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2): void;
        pathBezierCubicCurveTo(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        pathBezierCubicCurveTo(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        pathBezierCubicCurveTo(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: number): void;
        pathBezierQuadraticCurveTo(arg0: $ImVec2, arg1: $ImVec2): void;
        pathBezierQuadraticCurveTo(arg0: number, arg1: number, arg2: number, arg3: number): void;
        pathBezierQuadraticCurveTo(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        pathBezierQuadraticCurveTo(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        pathRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        pathRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        pathRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        pathRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        pathRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number): void;
        pathRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        pathRect(arg0: $ImVec2, arg1: $ImVec2): void;
        pathRect(arg0: number, arg1: number, arg2: number, arg3: number): void;
        channelsSplit(arg0: number): void;
        channelsMerge(): void;
        channelsSetCurrent(arg0: number): void;
        primUnreserve(arg0: number, arg1: number): void;
        primRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        primRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        primRectUV(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: number): void;
        primRectUV(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): void;
        primWriteVtx(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        primWriteVtx(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        primWriteIdx(arg0: number): void;
        primVtx(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        primVtx(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addQuad(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: number, arg5: number): void;
        addQuad(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: number): void;
        addQuad(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): void;
        addQuad(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): void;
        addRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        addRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        addRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        addRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number, arg4: number): void;
        addRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        addRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number, arg4: number, arg5: number): void;
        addRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): void;
        addRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number, arg4: number): void;
        addRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number): void;
        addRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        addRect(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number, arg4: number): void;
        pushClipRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: boolean): void;
        pushClipRect(arg0: number, arg1: number, arg2: number, arg3: number): void;
        pushClipRect(arg0: $ImVec2, arg1: $ImVec2): void;
        pushClipRect(arg0: $ImVec2, arg1: $ImVec2, arg2: boolean): void;
        popClipRect(): void;
        addRectFilled(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number, arg4: number): void;
        addRectFilled(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number): void;
        addRectFilled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        addRectFilled(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        addRectFilled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addRectFilled(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number): void;
        addRectFilled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        addRectFilled(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        primReserve(arg0: number, arg1: number): void;
        primQuadUV(arg0: $ImVec2, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: $ImVec2, arg6: $ImVec2, arg7: $ImVec2, arg8: number): void;
        primQuadUV(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: number): void;
        pushTextureID(arg0: number): void;
        getFlags(): number;
        hasFlags(arg0: number): boolean;
        addLine(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        addLine(arg0: $ImVec2, arg1: $ImVec2, arg2: number, arg3: number): void;
        addLine(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addLine(arg0: $ImVec2, arg1: $ImVec2, arg2: number): void;
        addImage(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addImage(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2): void;
        addImage(arg0: number, arg1: $ImVec2, arg2: $ImVec2): void;
        addImage(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): void;
        addImage(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): void;
        addImage(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2): void;
        addImage(arg0: number, arg1: $ImVec2, arg2: $ImVec2, arg3: $ImVec2, arg4: $ImVec2, arg5: number): void;
        addImage(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        setFlags(arg0: number): void;
        removeFlags(arg0: number): void;
        addFlags(arg0: number): void;
        addText(arg0: $ImFont, arg1: number, arg2: $ImVec2, arg3: number, arg4: string): void;
        addText(arg0: $ImFont, arg1: number, arg2: number, arg3: number, arg4: number, arg5: string): void;
        addText(arg0: $ImFont, arg1: number, arg2: $ImVec2, arg3: number, arg4: string, arg5: string): void;
        addText(arg0: $ImFont, arg1: number, arg2: number, arg3: number, arg4: number, arg5: string, arg6: string): void;
        addText(arg0: $ImFont, arg1: number, arg2: $ImVec2, arg3: number, arg4: string, arg5: string, arg6: number): void;
        addText(arg0: $ImVec2, arg1: number, arg2: string): void;
        addText(arg0: number, arg1: number, arg2: number, arg3: string): void;
        addText(arg0: $ImVec2, arg1: number, arg2: string, arg3: string): void;
        addText(arg0: number, arg1: number, arg2: number, arg3: string, arg4: string): void;
        addText(arg0: $ImFont, arg1: number, arg2: number, arg3: number, arg4: number, arg5: string, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addText(arg0: $ImFont, arg1: number, arg2: $ImVec2, arg3: number, arg4: string, arg5: $ImVec4): void;
        addText(arg0: $ImFont, arg1: number, arg2: number, arg3: number, arg4: number, arg5: string, arg6: number, arg7: number, arg8: number, arg9: number): void;
        addText(arg0: $ImFont, arg1: number, arg2: $ImVec2, arg3: number, arg4: string, arg5: string, arg6: $ImVec4): void;
        addText(arg0: $ImFont, arg1: number, arg2: number, arg3: number, arg4: number, arg5: string, arg6: string, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addText(arg0: $ImFont, arg1: number, arg2: number, arg3: number, arg4: number, arg5: string, arg6: string, arg7: number): void;
        addText(arg0: $ImFont, arg1: number, arg2: $ImVec2, arg3: number, arg4: string, arg5: string, arg6: number, arg7: $ImVec4): void;
        addText(arg0: $ImFont, arg1: number, arg2: number, arg3: number, arg4: number, arg5: string, arg6: string, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number): void;
        addText(arg0: $ImFont, arg1: number, arg2: $ImVec2, arg3: number, arg4: string, arg5: number, arg6: $ImVec4): void;
        ptr: number;
        constructor(arg0: number);
        get clipRectMinX(): number;
        get clipRectMinY(): number;
        get clipRectMaxX(): number;
        get clipRectMaxY(): number;
    }
    export class $ImFont extends $ImGuiStructDestroyable {
        getScale(): number;
        renderChar(arg0: $ImDrawList, arg1: number, arg2: $ImVec2, arg3: number, arg4: number): void;
        renderChar(arg0: $ImDrawList, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        getConfigDataCount(): number;
        setConfigDataCount(arg0: number): void;
        getEllipsisChar(): number;
        setEllipsisChar(arg0: number): void;
        setDotChar(arg0: number): void;
        getDirtyLookupTables(): boolean;
        setDirtyLookupTables(arg0: boolean): void;
        getAscent(): number;
        setAscent(arg0: number): void;
        getDescent(): number;
        setDescent(arg0: number): void;
        getMetricsTotalSurface(): number;
        setMetricsTotalSurface(arg0: number): void;
        findGlyphNoFallback(arg0: number): $ImFontGlyph;
        getDebugName(): string;
        calcTextSizeA(arg0: $ImVec2, arg1: number, arg2: number, arg3: number, arg4: string, arg5: string): void;
        calcTextSizeA(arg0: number, arg1: number, arg2: number, arg3: string, arg4: string): $ImVec2;
        calcTextSizeA(arg0: $ImVec2, arg1: number, arg2: number, arg3: number, arg4: string): void;
        calcTextSizeA(arg0: number, arg1: number, arg2: number, arg3: string): $ImVec2;
        calcTextSizeAY(arg0: number, arg1: number, arg2: number, arg3: string, arg4: string): number;
        calcTextSizeAY(arg0: number, arg1: number, arg2: number, arg3: string): number;
        calcWordWrapPositionA(arg0: number, arg1: string, arg2: string, arg3: number): string;
        getFallbackAdvanceX(): number;
        setFallbackAdvanceX(arg0: number): void;
        setFontSize(arg0: number): void;
        getFallbackGlyph(): $ImFontGlyph;
        setFallbackGlyph(arg0: $ImFontGlyph): void;
        getDotChar(): number;
        calcTextSizeAX(arg0: number, arg1: number, arg2: number, arg3: string): number;
        calcTextSizeAX(arg0: number, arg1: number, arg2: number, arg3: string, arg4: string): number;
        findGlyph(arg0: number): $ImFontGlyph;
        getCharAdvance(arg0: number): number;
        renderText(arg0: $ImDrawList, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: string, arg10: string, arg11: number, arg12: boolean): void;
        renderText(arg0: $ImDrawList, arg1: number, arg2: $ImVec2, arg3: number, arg4: $ImVec4, arg5: string, arg6: string, arg7: number, arg8: boolean): void;
        renderText(arg0: $ImDrawList, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: string, arg10: string, arg11: number): void;
        renderText(arg0: $ImDrawList, arg1: number, arg2: $ImVec2, arg3: number, arg4: $ImVec4, arg5: string, arg6: string, arg7: boolean): void;
        renderText(arg0: $ImDrawList, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: string, arg10: string, arg11: boolean): void;
        renderText(arg0: $ImDrawList, arg1: number, arg2: $ImVec2, arg3: number, arg4: $ImVec4, arg5: string, arg6: string): void;
        renderText(arg0: $ImDrawList, arg1: number, arg2: $ImVec2, arg3: number, arg4: $ImVec4, arg5: string, arg6: string, arg7: number): void;
        renderText(arg0: $ImDrawList, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: string, arg10: string): void;
        setScale(arg0: number): void;
        isLoaded(): boolean;
        getFontSize(): number;
        ptr: number;
        constructor();
        constructor(arg0: number);
        get debugName(): string;
        get loaded(): boolean;
    }
    export class $ImFontGlyph extends $ImGuiStructDestroyable {
        getVisible(): number;
        setVisible(arg0: number): void;
        getU0(): number;
        getU1(): number;
        getV0(): number;
        setColored(arg0: number): void;
        getCodepoint(): number;
        setCodepoint(arg0: number): void;
        getAdvanceX(): number;
        setAdvanceX(arg0: number): void;
        setX0(arg0: number): void;
        setY0(arg0: number): void;
        setX1(arg0: number): void;
        setY1(arg0: number): void;
        setU0(arg0: number): void;
        setV0(arg0: number): void;
        setU1(arg0: number): void;
        setV1(arg0: number): void;
        getY1(): number;
        getX0(): number;
        getX1(): number;
        getY0(): number;
        getColored(): number;
        getV1(): number;
        ptr: number;
        constructor(arg0: number);
        constructor();
    }
}
