import { $Consumer_ } from "@package/java/util/function";
import { $FocusHandler } from "@package/io/wispforest/owo/ui/util";
import { $EventSource } from "@package/io/wispforest/owo/util";
import { $Component_ } from "@package/net/minecraft/network/chat";
import { $AnimatableProperty, $PositionedRectangle, $CursorStyle_, $Sizing, $Positioning, $Component$DismountReason_, $Component, $Component$FocusSource_, $ParentComponent, $CursorStyle, $OwoUIDrawContext, $Size, $Size_, $Insets_, $Insets } from "@package/io/wispforest/owo/ui/core";
import { $MouseScroll, $MouseDown, $MouseUp, $MouseLeave, $CharTyped, $MouseEnter, $FocusLost, $KeyPress, $MouseDrag, $FocusGained } from "@package/io/wispforest/owo/ui/event";
import { $UIModel } from "@package/io/wispforest/owo/ui/parsing";
import { $ClientTooltipComponent } from "@package/net/minecraft/client/gui/screens/inventory/tooltip";
import { $List, $Map_, $Collection_, $List_ } from "@package/java/util";
import { $Element } from "@package/org/w3c/dom";
import { $ComponentExtension } from "@package/io/wispforest/accessories/pond/owo";

declare module "@package/io/wispforest/owo/ui/base" {
    export class $BaseComponent implements $Component, $ComponentExtension<any> {
        charTyped(): $EventSource<$CharTyped>;
        tooltip(tooltip: $List_<$ClientTooltipComponent>): $Component;
        tooltip(): $List<$ClientTooltipComponent>;
        allowIndividualOverdraw(value: boolean): $BaseComponent;
        allowIndividualOverdraw(): boolean;
        dismount(reason: $Component$DismountReason_): void;
        focusHandler(): $FocusHandler;
        positioning(): $AnimatableProperty<$Positioning>;
        positioning(positioning: $Positioning): $BaseComponent;
        margins(margins: $Insets_): $BaseComponent;
        margins(): $AnimatableProperty<$Insets>;
        horizontalSizing(): $AnimatableProperty<$Sizing>;
        horizontalSizing(horizontalSizing: $Sizing): $Component;
        verticalSizing(verticalSizing: $Sizing): $Component;
        verticalSizing(): $AnimatableProperty<$Sizing>;
        mouseDown(): $EventSource<$MouseDown>;
        cursorStyle(style: $CursorStyle_): $BaseComponent;
        cursorStyle(): $CursorStyle;
        onMouseDown(mouseX: number, mouseY: number, button: number): boolean;
        onMouseUp(mouseX: number, mouseY: number, button: number): boolean;
        mouseUp(): $EventSource<$MouseUp>;
        mouseScroll(): $EventSource<$MouseScroll>;
        mouseDrag(): $EventSource<$MouseDrag>;
        keyPress(): $EventSource<$KeyPress>;
        focusGained(): $EventSource<$FocusGained>;
        focusLost(): $EventSource<$FocusLost>;
        mouseEnter(): $EventSource<$MouseEnter>;
        mouseLeave(): $EventSource<$MouseLeave>;
        onMouseScroll(mouseX: number, mouseY: number, amount: number): boolean;
        onMouseDrag(mouseX: number, mouseY: number, deltaX: number, deltaY: number, button: number): boolean;
        onKeyPress(keyCode: number, scanCode: number, modifiers: number): boolean;
        onCharTyped(chr: string, modifiers: number): boolean;
        onFocusGained(source: $Component$FocusSource_): void;
        onFocusLost(): void;
        zIndex(zIndex: number): $Component;
        zIndex(): number;
        updateX(x: number): void;
        updateY(y: number): void;
        y(): number;
        width(): number;
        height(): number;
        configure<C extends $Component>(closure: $Consumer_<C>): C;
        parent(): $ParentComponent;
        inflate(space: $Size_): void;
        update(delta: number, mouseX: number, mouseY: number): void;
        x(): number;
        id(): string;
        id(id: string): $Component;
        mount(parent: $ParentComponent, x: number, y: number): void;
        sizing(horizontalSizing: $Sizing, verticalSizing: $Sizing): $Component;
        sizing(sizing: $Sizing): $Component;
        tooltip(tooltip: $Component_): $Component;
        tooltip(tooltip: $Collection_<$Component_>): $Component;
        moveTo(x: number, y: number): void;
        shouldDrawTooltip(mouseX: number, mouseY: number): boolean;
        canFocus(source: $Component$FocusSource_): boolean;
        parseProperties(model: $UIModel, element: $Element, children: $Map_<string, $Element>): void;
        drawTooltip(context: $OwoUIDrawContext, mouseX: number, mouseY: number, partialTicks: number, delta: number): void;
        drawFocusHighlight(context: $OwoUIDrawContext, mouseX: number, mouseY: number, partialTicks: number, delta: number): void;
        isInBoundingBox(x: number, y: number): boolean;
        hasParent(): boolean;
        baseX(): number;
        baseY(): number;
        fullSize(): $Size;
        remove(): void;
        root(): $ParentComponent;
        intersection(other: $PositionedRectangle): $PositionedRectangle;
        intersects(other: $PositionedRectangle): boolean;
        interpolate(next: $PositionedRectangle, delta: number): $PositionedRectangle;
    }
}
