#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 27 09:28:16 CDT 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=
