import { $BlockPos_ } from "@package/net/minecraft/core";
import { $ItemStack, $ItemStack_ } from "@package/net/minecraft/world/item";
import { $BlockState_, $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $FiguraVec3 } from "@package/org/figuramc/figura/math/vector";
import { $Object } from "@package/java/lang";
import { $HashMap, $List, $Map, $Set } from "@package/java/util";
import { $LuaTable } from "@package/org/luaj/vm2";

declare module "@package/org/figuramc/figura/lua/api/world" {
    export class $BlockStateAPI {
        asItem(): $ItemStackAPI;
        getTags(): $List<string>;
        isTranslucent(): boolean;
        isAir(): boolean;
        hasBlockEntity(): boolean;
        getCollisionShape(): $List<$List<$FiguraVec3>>;
        setPos(x: $Object, y: number, z: number): $BlockStateAPI;
        getFriction(): number;
        getEntityData(): $LuaTable;
        getPos(): $FiguraVec3;
        getTextures(): $HashMap<string, $Set<string>>;
        __eq(other: $BlockStateAPI): boolean;
        __index(arg: string): $Object;
        hasCollision(): boolean;
        getMapColor(): $FiguraVec3;
        getLuminance(): number;
        getComparatorOutput(): number;
        isSolidBlock(): boolean;
        hasEmissiveLighting(): boolean;
        getHardness(): number;
        emitsRedstonePower(): boolean;
        getVelocityMultiplier(): number;
        getJumpVelocityMultiplier(): number;
        getBlastResistance(): number;
        getOutlineShape(): $List<$List<$FiguraVec3>>;
        getFluidTags(): $List<string>;
        toStateString(): string;
        getID(): string;
        getOpacity(): number;
        getSounds(): $Map<string, $Object>;
        isFullCube(): boolean;
        pos(x: $Object, y: number, z: number): $BlockStateAPI;
        isOpaque(): boolean;
        getProperties(): $LuaTable;
        blockState: $BlockState;
        id: string;
        properties: $LuaTable;
        constructor(blockstate: $BlockState_, pos: $BlockPos_);
        get tags(): $List<string>;
        get translucent(): boolean;
        get air(): boolean;
        get collisionShape(): $List<$List<$FiguraVec3>>;
        get friction(): number;
        get entityData(): $LuaTable;
        get textures(): $HashMap<string, $Set<string>>;
        get mapColor(): $FiguraVec3;
        get luminance(): number;
        get comparatorOutput(): number;
        get solidBlock(): boolean;
        get hardness(): number;
        get velocityMultiplier(): number;
        get jumpVelocityMultiplier(): number;
        get blastResistance(): number;
        get outlineShape(): $List<$List<$FiguraVec3>>;
        get fluidTags(): $List<string>;
        get ID(): string;
        get opacity(): number;
        get sounds(): $Map<string, $Object>;
        get fullCube(): boolean;
        get opaque(): boolean;
    }
    export class $ItemStackAPI {
        getTags(): $List<string>;
        getEquipmentSlot(): string;
        getUseDuration(): number;
        isArmor(): boolean;
        getDamage(): number;
        isBlockItem(): boolean;
        __eq(other: $ItemStackAPI): boolean;
        __index(arg: string): $Object;
        hasGlint(): boolean;
        getRepairCost(): number;
        getRarity(): string;
        getMaxDamage(): number;
        isEnchantable(): boolean;
        isDamageable(): boolean;
        isStackable(): boolean;
        getPopTime(): number;
        isFood(): boolean;
        getUseAction(): string;
        toStackString(): string;
        getBlockstate(): $BlockStateAPI;
        getID(): string;
        getTag(): $LuaTable;
        getMaxCount(): number;
        isTool(): boolean;
        static verify(itemStack: $ItemStack_): $ItemStackAPI;
        getName(): string;
        getCount(): number;
        copy(): $ItemStackAPI;
        itemStack: $ItemStack;
        id: string;
        tag: $LuaTable;
        constructor(itemStack: $ItemStack_);
        constructor(itemStack: $ItemStack_, tag: $LuaTable);
        get tags(): $List<string>;
        get equipmentSlot(): string;
        get useDuration(): number;
        get armor(): boolean;
        get damage(): number;
        get blockItem(): boolean;
        get repairCost(): number;
        get rarity(): string;
        get maxDamage(): number;
        get enchantable(): boolean;
        get damageable(): boolean;
        get stackable(): boolean;
        get popTime(): number;
        get food(): boolean;
        get useAction(): string;
        get blockstate(): $BlockStateAPI;
        get ID(): string;
        get maxCount(): number;
        get tool(): boolean;
        get name(): string;
        get count(): number;
    }
}
