import { $Ingredient } from "@package/net/minecraft/world/item/crafting";
import { $GearPropertyValue, $GearProperty_ } from "@package/net/silentchaos512/gear/api/property";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $Codec } from "@package/com/mojang/serialization";
import { $MutableComponent, $Component } from "@package/net/minecraft/network/chat";
import { $PartType, $PartType_ } from "@package/net/silentchaos512/gear/api/part";
import { $IMaterialModifierType_, $IMaterialModifier } from "@package/net/silentchaos512/gear/api/material/modifier";
import { $TraitInstance } from "@package/net/silentchaos512/gear/api/traits";
import { $Set, $Collection_, $Collection } from "@package/java/util";
import { $GearType_ } from "@package/net/silentchaos512/gear/api/item";
import { $Supplier_ } from "@package/java/util/function";
import { $IMaterialCategory, $IMaterialCategory_, $TextureType, $Material } from "@package/net/silentchaos512/gear/api/material";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $RepairContext$Type_ } from "@package/net/silentchaos512/gear/gear/part";
import { $ResourceLocation } from "@package/net/minecraft/resources";
import { $PropertyKey, $GearComponentInstance, $DataResource, $PartGearKey_ } from "@package/net/silentchaos512/gear/api/util";
import { $StreamCodec } from "@package/net/minecraft/network/codec";

declare module "@package/net/silentchaos512/gear/gear/material" {
    export class $MaterialInstance implements $GearComponentInstance<$Material> {
        getColor(arg0: $GearType_, arg1: $PartType_): number;
        getModifier<T extends $IMaterialModifier>(arg0: $IMaterialModifierType_<T>): T;
        canRepair(arg0: $ItemStack_): boolean;
        getCategories(): $Collection<$IMaterialCategory>;
        getNullable(): $Material;
        getDisplayName(arg0: $PartType_, arg1: $ItemStack_): $Component;
        isValid(): boolean;
        getItem(): $ItemStack;
        onSalvage(): $MaterialInstance;
        getPartTypes(): $Set<$PartType>;
        getDisplayNamePrefix(arg0: $PartType_): $Component;
        getMainTextureType(): $TextureType;
        getNameColor(arg0: $PartType_, arg1: $GearType_): number;
        getModelKey(): string;
        isCraftingAllowed(arg0: $PartType_, arg1: $GearType_): boolean;
        getSalvageItem(): $ItemStack;
        getTraits(arg0: $PartGearKey_): $Collection<$TraitInstance>;
        getPropertyModifiers<T, V extends $GearPropertyValue<T>>(arg0: $PartType_, arg1: $PropertyKey<T, V>): $Collection<V>;
        getSimpleNameWithModifiers(): $MutableComponent;
        getRepairValue(arg0: $ItemStack_, arg1: $RepairContext$Type_): number;
        getRepairValue(arg0: $ItemStack_): number;
        hasAnyCategory(arg0: $Collection_<$IMaterialCategory_>): boolean;
        getDisplayNameWithModifiers(arg0: $PartType_, arg1: $ItemStack_): $MutableComponent;
        allowedInPart(arg0: $PartType_): boolean;
        getIngredient(): $Ingredient;
        is(arg0: $DataResource<$Material>): boolean;
        isSimple(): boolean;
        getProperty<T, V extends $GearPropertyValue<T>>(arg0: $PartType_, arg1: $PropertyKey<T, V>): T;
        getModifiers(): $Collection<$IMaterialModifier>;
        static of(arg0: $DataResource<$Material>): $MaterialInstance;
        static of(arg0: $Material): $MaterialInstance;
        static of(arg0: $DataResource<$Material>, arg1: $ItemStack_): $MaterialInstance;
        static of(arg0: $Material, arg1: $ItemStack_): $MaterialInstance;
        static from(arg0: $ItemStack_): $MaterialInstance;
        getSimpleName(): $Component;
        getId(): $ResourceLocation;
        getDisplayName(arg0: $PartType_): $Component;
        getNameColor(): number;
        getPropertyModifiers<T, V extends $GearPropertyValue<T>>(arg0: $Supplier_<$PartType>, arg1: $PropertyKey<T, V>): $Collection<V>;
        getProperty<T, V extends $GearPropertyValue<T>>(arg0: $Supplier_<$PartType>, arg1: $PropertyKey<T, V>): T;
        getProperty<T, V extends $GearPropertyValue<T>>(arg0: $PartType_, arg1: $GearProperty_<T, V>): T;
        get(): $Material;
        static CODEC: $Codec<$MaterialInstance>;
        static STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $MaterialInstance>;
        get categories(): $Collection<$IMaterialCategory>;
        get nullable(): $Material;
        get valid(): boolean;
        get item(): $ItemStack;
        get partTypes(): $Set<$PartType>;
        get mainTextureType(): $TextureType;
        get modelKey(): string;
        get salvageItem(): $ItemStack;
        get simpleNameWithModifiers(): $MutableComponent;
        get ingredient(): $Ingredient;
        get simple(): boolean;
        get modifiers(): $Collection<$IMaterialModifier>;
        get simpleName(): $Component;
        get id(): $ResourceLocation;
    }
}
