import { $Serializable } from "@package/java/io";
import { $WeightedItem, $Weighted, $WeightedEffect } from "@package/com/crackerjackbox/mobcontrol/data";
import { $ArrayList, $Set } from "@package/java/util";

declare module "@package/com/crackerjackbox/mobcontrol/rule" {
    export class $MobExSet implements $Serializable {
        movementSpeedFrom: number;
        nameAlwaysShown: boolean;
        plantFlowers: number;
        cutGrass: number;
        healthTo: number;
        sunburn: number;
        canLead: number;
        placeBlock: number;
        climb: number;
        xpFrom: number;
        onHurt: string;
        attack: $ArrayList<string>;
        damageFrom: number;
        snbt: string;
        breakBlock: number;
        flyingSpeedFrom: number;
        allowAttack: $ArrayList<string>;
        sizeTo: number;
        eatPlants: number;
        followRangeTo: number;
        xpTo: number;
        climbFallTicks: number;
        followRangeFrom: number;
        knockbackFrom: number;
        movementSpeedTo: number;
        mount: string;
        plantTrees: number;
        healthFrom: number;
        bossBar: string;
        flyingSpeedTo: number;
        damageTo: number;
        eatPlantsHeals: number;
        knockbackTo: number;
        baby: number;
        name: string;
        spreadFire: number;
        sizeFrom: number;
        constructor();
    }
    export class $MobExRule implements $Serializable {
        isBaby: boolean;
        repeatTo: number;
        feet: $Weighted<$WeightedItem>;
        lightBlockFrom: number;
        moonPhaseTo: number;
        run: number;
        type: $ArrayList<string>;
        maxPerMob: number;
        maxSpawnerBlock: $ArrayList<string>;
        legs: $Weighted<$WeightedItem>;
        mobExName: string;
        weather: $ArrayList<string>;
        dayTo: number;
        season: $ArrayList<string>;
        maxHealth: number;
        loot: $Weighted<$WeightedItem>;
        currentHealth: number;
        mainhand: $Weighted<$WeightedItem>;
        coolDownNextSpawnTick: number;
        coolDownFrom: number;
        chest: $Weighted<$WeightedItem>;
        timeOfDayFrom: number;
        canSeeSky: boolean;
        biome: $ArrayList<string>;
        effect: $Weighted<$WeightedEffect>;
        name: string;
        maxNearby: number;
        maxPerPlayer: number;
        head: $Weighted<$WeightedItem>;
        timeOfDayTo: number;
        lightSkyFrom: number;
        moonPhaseFrom: number;
        coolDownTo: number;
        dayFrom: number;
        copy: string;
        dimension: $ArrayList<string>;
        biomeTag: $ArrayList<string>;
        lightBlockTo: number;
        hasLoadedOnce: boolean;
        lightSkyTo: number;
        commandOverride: string;
        set: $MobExSet;
        structure: $ArrayList<string>;
        offhand: $Weighted<$WeightedItem>;
        repeatFrom: number;
        spawn: $MobExSpawn;
        ignoredTypes: $Set<string>;
        maxSpawner: number;
        maxNearbyRange: number;
        constructor();
    }
    export class $MobExSpawn implements $Serializable {
        flameBurst: number;
        tries: number;
        poof: number;
        distanceDownTo: number;
        additionalChecks: boolean;
        atYFrom: number;
        sound: string;
        countSpread: boolean;
        convert: $ArrayList<string>;
        distanceFrom: number;
        atYTo: number;
        distanceTo: number;
        point: $ArrayList<string>;
        distanceUpFrom: number;
        countFrom: number;
        distanceUpTo: number;
        distanceDownFrom: number;
        finalize: boolean;
        countTo: number;
        group: $ArrayList<string>;
        constructor();
    }
}
