import { $EntryObjectHandler } from "@package/com/sammy/malum/client/screen/codex/handlers";
import { $Component } from "@package/net/minecraft/network/chat";
import { $NarratableEntry } from "@package/net/minecraft/client/gui/narration";
import { $Renderable } from "@package/net/minecraft/client/gui/components";
import { $Minecraft } from "@package/net/minecraft/client";
import { $List, $Collection } from "@package/java/util";
import { $Consumer_ } from "@package/java/util/function";
import { $AbstractMalumCodexScreen } from "@package/com/sammy/malum/client/screen/codex/screens";
import { $PlacedBookEntry, $PlacedBookEntryBuilder, $PlacedEntryAcceptor } from "@package/com/sammy/malum/client/screen/codex";
import { $Screen$DeferredTooltipRendering } from "@package/net/minecraft/client/gui/screens";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $BookObject } from "@package/com/sammy/malum/client/screen/codex/objects";
import { $Color } from "@package/java/awt";
import { $Font } from "@package/net/minecraft/client/gui";
import { $Vec2 } from "@package/net/minecraft/world/phys";

declare module "@package/com/sammy/malum/client/screen/codex/screens/progression" {
    export class $AbstractProgressionCodexScreen extends $AbstractMalumCodexScreen implements $PlacedEntryAcceptor {
        getGuiTop(): number;
        getGuiLeft(): number;
        renderBackground(arg0: $PoseStack, arg1: $ResourceLocation_, arg2: number, arg3: number): void;
        renderBackground(arg0: $PoseStack): void;
        isInView(arg0: number, arg1: number): boolean;
        clampOffsets(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): $Vec2;
        getInsideLeft(): number;
        getInsideTop(): number;
        setupEntries(): void;
        setupObjects(): void;
        faceOrigin(): void;
        constrictEntryRendering(): void;
        renderFade(arg0: $PoseStack): void;
        faceObject(arg0: $BookObject<never>): void;
        getVoidFadeoutDuration(): number;
        correctOOBB(): void;
        getVoidFadeoutDelta(): number;
        getOutlineColor(): $Color;
        init(): void;
        addEntry(arg0: string, arg1: number, arg2: number, arg3: $Consumer_<$PlacedBookEntryBuilder>): void;
        addEntry(arg0: string, arg1: number, arg2: number): void;
        getEntries(): $Collection<$PlacedBookEntry>;
        static MENU_BACKGROUND: $ResourceLocation;
        minecraft: $Minecraft;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        static FRAME_TEXTURE: $ResourceLocation;
        static FRAME_FADE_TEXTURE: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static BOOK_HEIGHT: number;
        title: $Component;
        static FOOTER_SEPARATOR: $ResourceLocation;
        progressionObjects: $EntryObjectHandler;
        entries: $List<$PlacedBookEntry>;
        renderables: $List<$Renderable>;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        static BOOK_WIDTH: number;
        static BOOK_INSIDE_WIDTH: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        static BOOK_INSIDE_HEIGHT: number;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        font: $Font;
        get guiTop(): number;
        get guiLeft(): number;
        get insideLeft(): number;
        get insideTop(): number;
        get voidFadeoutDuration(): number;
        get voidFadeoutDelta(): number;
        get outlineColor(): $Color;
    }
}
